// Generated by the protocol buffer compiler.  DO NOT EDIT!

package net.freeback.entries;

public final class FBFileInfoProto {
  private FBFileInfoProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public static final class FBFileInfo extends
      com.google.protobuf.GeneratedMessage {
    // Use FBFileInfo.newBuilder() to construct.
    private FBFileInfo() {}
    
    private static final FBFileInfo defaultInstance = new FBFileInfo();
    public static FBFileInfo getDefaultInstance() {
      return defaultInstance;
    }
    
    public FBFileInfo getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return net.freeback.entries.FBFileInfoProto.internal_static_net_freeback_FBFileInfo_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return net.freeback.entries.FBFileInfoProto.internal_static_net_freeback_FBFileInfo_fieldAccessorTable;
    }
    
    // required string master = 1;
    public static final int MASTER_FIELD_NUMBER = 1;
    private boolean hasMaster;
    private java.lang.String master_ = "";
    public boolean hasMaster() { return hasMaster; }
    public java.lang.String getMaster() { return master_; }
    
    // repeated string Names = 2;
    public static final int NAMES_FIELD_NUMBER = 2;
    private java.util.List<java.lang.String> names_ =
      java.util.Collections.emptyList();
    public java.util.List<java.lang.String> getNamesList() {
      return names_;
    }
    public int getNamesCount() { return names_.size(); }
    public java.lang.String getNames(int index) {
      return names_.get(index);
    }
    
    public final boolean isInitialized() {
      if (!hasMaster) return false;
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (hasMaster()) {
        output.writeString(1, getMaster());
      }
      for (java.lang.String element : getNamesList()) {
        output.writeString(2, element);
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      if (hasMaster()) {
        size += com.google.protobuf.CodedOutputStream
          .computeStringSize(1, getMaster());
      }
      {
        int dataSize = 0;
        for (java.lang.String element : getNamesList()) {
          dataSize += com.google.protobuf.CodedOutputStream
            .computeStringSizeNoTag(element);
        }
        size += dataSize;
        size += 1 * getNamesList().size();
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    public static net.freeback.entries.FBFileInfoProto.FBFileInfo parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static net.freeback.entries.FBFileInfoProto.FBFileInfo parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static net.freeback.entries.FBFileInfoProto.FBFileInfo parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static net.freeback.entries.FBFileInfoProto.FBFileInfo parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static net.freeback.entries.FBFileInfoProto.FBFileInfo parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static net.freeback.entries.FBFileInfoProto.FBFileInfo parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static net.freeback.entries.FBFileInfoProto.FBFileInfo parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeDelimitedFrom(input).buildParsed();
    }
    public static net.freeback.entries.FBFileInfoProto.FBFileInfo parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeDelimitedFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static net.freeback.entries.FBFileInfoProto.FBFileInfo parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static net.freeback.entries.FBFileInfoProto.FBFileInfo parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(net.freeback.entries.FBFileInfoProto.FBFileInfo prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> {
      private net.freeback.entries.FBFileInfoProto.FBFileInfo result;
      
      // Construct using net.freeback.entries.FBFileInfoProto.FBFileInfo.newBuilder()
      private Builder() {}
      
      private static Builder create() {
        Builder builder = new Builder();
        builder.result = new net.freeback.entries.FBFileInfoProto.FBFileInfo();
        return builder;
      }
      
      protected net.freeback.entries.FBFileInfoProto.FBFileInfo internalGetResult() {
        return result;
      }
      
      public Builder clear() {
        if (result == null) {
          throw new IllegalStateException(
            "Cannot call clear() after build().");
        }
        result = new net.freeback.entries.FBFileInfoProto.FBFileInfo();
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(result);
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return net.freeback.entries.FBFileInfoProto.FBFileInfo.getDescriptor();
      }
      
      public net.freeback.entries.FBFileInfoProto.FBFileInfo getDefaultInstanceForType() {
        return net.freeback.entries.FBFileInfoProto.FBFileInfo.getDefaultInstance();
      }
      
      public boolean isInitialized() {
        return result.isInitialized();
      }
      public net.freeback.entries.FBFileInfoProto.FBFileInfo build() {
        if (result != null && !isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return buildPartial();
      }
      
      private net.freeback.entries.FBFileInfoProto.FBFileInfo buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        if (!isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return buildPartial();
      }
      
      public net.freeback.entries.FBFileInfoProto.FBFileInfo buildPartial() {
        if (result == null) {
          throw new IllegalStateException(
            "build() has already been called on this Builder.");
        }
        if (result.names_ != java.util.Collections.EMPTY_LIST) {
          result.names_ =
            java.util.Collections.unmodifiableList(result.names_);
        }
        net.freeback.entries.FBFileInfoProto.FBFileInfo returnMe = result;
        result = null;
        return returnMe;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof net.freeback.entries.FBFileInfoProto.FBFileInfo) {
          return mergeFrom((net.freeback.entries.FBFileInfoProto.FBFileInfo)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(net.freeback.entries.FBFileInfoProto.FBFileInfo other) {
        if (other == net.freeback.entries.FBFileInfoProto.FBFileInfo.getDefaultInstance()) return this;
        if (other.hasMaster()) {
          setMaster(other.getMaster());
        }
        if (!other.names_.isEmpty()) {
          if (result.names_.isEmpty()) {
            result.names_ = new java.util.ArrayList<java.lang.String>();
          }
          result.names_.addAll(other.names_);
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                return this;
              }
              break;
            }
            case 10: {
              setMaster(input.readString());
              break;
            }
            case 18: {
              addNames(input.readString());
              break;
            }
          }
        }
      }
      
      
      // required string master = 1;
      public boolean hasMaster() {
        return result.hasMaster();
      }
      public java.lang.String getMaster() {
        return result.getMaster();
      }
      public Builder setMaster(java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  result.hasMaster = true;
        result.master_ = value;
        return this;
      }
      public Builder clearMaster() {
        result.hasMaster = false;
        result.master_ = getDefaultInstance().getMaster();
        return this;
      }
      
      // repeated string Names = 2;
      public java.util.List<java.lang.String> getNamesList() {
        return java.util.Collections.unmodifiableList(result.names_);
      }
      public int getNamesCount() {
        return result.getNamesCount();
      }
      public java.lang.String getNames(int index) {
        return result.getNames(index);
      }
      public Builder setNames(int index, java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  result.names_.set(index, value);
        return this;
      }
      public Builder addNames(java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  if (result.names_.isEmpty()) {
          result.names_ = new java.util.ArrayList<java.lang.String>();
        }
        result.names_.add(value);
        return this;
      }
      public Builder addAllNames(
          java.lang.Iterable<? extends java.lang.String> values) {
        if (result.names_.isEmpty()) {
          result.names_ = new java.util.ArrayList<java.lang.String>();
        }
        super.addAll(values, result.names_);
        return this;
      }
      public Builder clearNames() {
        result.names_ = java.util.Collections.emptyList();
        return this;
      }
    }
    
    static {
      net.freeback.entries.FBFileInfoProto.getDescriptor();
    }
    
    static {
      net.freeback.entries.FBFileInfoProto.internalForceInit();
    }
  }
  
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_net_freeback_FBFileInfo_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_net_freeback_FBFileInfo_fieldAccessorTable;
  
  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\020FBFileInfo.proto\022\014net.freeback\"+\n\nFBFi" +
      "leInfo\022\016\n\006master\030\001 \002(\t\022\r\n\005Names\030\002 \003(\tB\'\n" +
      "\024net.freeback.entriesB\017FBFileInfoProto"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_net_freeback_FBFileInfo_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_net_freeback_FBFileInfo_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_net_freeback_FBFileInfo_descriptor,
              new java.lang.String[] { "Master", "Names", },
              net.freeback.entries.FBFileInfoProto.FBFileInfo.class,
              net.freeback.entries.FBFileInfoProto.FBFileInfo.Builder.class);
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }
  
  public static void internalForceInit() {}
}
