// Generated by the protocol buffer compiler.  DO NOT EDIT!

package net.freeback.entries;

public final class FBMessageProto {
  private FBMessageProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public enum Notify
      implements com.google.protobuf.ProtocolMessageEnum {
    Unknown(0, 256),
    ServerError(1, 257),
    SystemConnect(2, 1),
    SystemDisConnect(3, 2),
    SystemData(4, 3),
    SystemId(5, 4),
    UserRegister(6, 16),
    UserLogin(7, 17),
    UserVerify(8, 18),
    UserLogout(9, 19),
    UserInfo(10, 20),
    PhotoUser(11, 32),
    PhotoStore(12, 33),
    PhotoProduct(13, 34),
    StoreSave(14, 80),
    StoreFindById(15, 81),
    StoreFindByBoss(16, 82),
    StoreProduct(17, 83),
    StoreDict(18, 84),
    OrderChecked(21, 258),
    OrderUnChecked(22, 259),
    ;
    
    public static final Notify OrderCreate = Unknown;
    public static final Notify OrderAddProduct = ServerError;
    
    public final int getNumber() { return value; }
    
    public static Notify valueOf(int value) {
      switch (value) {
        case 256: return Unknown;
        case 257: return ServerError;
        case 1: return SystemConnect;
        case 2: return SystemDisConnect;
        case 3: return SystemData;
        case 4: return SystemId;
        case 16: return UserRegister;
        case 17: return UserLogin;
        case 18: return UserVerify;
        case 19: return UserLogout;
        case 20: return UserInfo;
        case 32: return PhotoUser;
        case 33: return PhotoStore;
        case 34: return PhotoProduct;
        case 80: return StoreSave;
        case 81: return StoreFindById;
        case 82: return StoreFindByBoss;
        case 83: return StoreProduct;
        case 84: return StoreDict;
        case 258: return OrderChecked;
        case 259: return OrderUnChecked;
        default: return null;
      }
    }
    
    public static com.google.protobuf.Internal.EnumLiteMap<Notify>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static com.google.protobuf.Internal.EnumLiteMap<Notify>
        internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<Notify>() {
            public Notify findValueByNumber(int number) {
              return Notify.valueOf(number)
    ;        }
          };
    
    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      return getDescriptor().getValues().get(index);
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return net.freeback.entries.FBMessageProto.getDescriptor().getEnumTypes().get(0);
    }
    
    private static final Notify[] VALUES = {
      Unknown, ServerError, SystemConnect, SystemDisConnect, SystemData, SystemId, UserRegister, UserLogin, UserVerify, UserLogout, UserInfo, PhotoUser, PhotoStore, PhotoProduct, StoreSave, StoreFindById, StoreFindByBoss, StoreProduct, StoreDict, OrderCreate, OrderAddProduct, OrderChecked, OrderUnChecked, 
    };
    public static Notify valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      return VALUES[desc.getIndex()];
    }
    private final int index;
    private final int value;
    private Notify(int index, int value) {
      this.index = index;
      this.value = value;
    }
    
    static {
      net.freeback.entries.FBMessageProto.getDescriptor();
    }
  }
  
  public enum Action
      implements com.google.protobuf.ProtocolMessageEnum {
    None(0, 0),
    Find(1, 1),
    Save(2, 2),
    Remove(3, 3),
    ;
    
    
    public final int getNumber() { return value; }
    
    public static Action valueOf(int value) {
      switch (value) {
        case 0: return None;
        case 1: return Find;
        case 2: return Save;
        case 3: return Remove;
        default: return null;
      }
    }
    
    public static com.google.protobuf.Internal.EnumLiteMap<Action>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static com.google.protobuf.Internal.EnumLiteMap<Action>
        internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<Action>() {
            public Action findValueByNumber(int number) {
              return Action.valueOf(number)
    ;        }
          };
    
    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      return getDescriptor().getValues().get(index);
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return net.freeback.entries.FBMessageProto.getDescriptor().getEnumTypes().get(1);
    }
    
    private static final Action[] VALUES = {
      None, Find, Save, Remove, 
    };
    public static Action valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      return VALUES[desc.getIndex()];
    }
    private final int index;
    private final int value;
    private Action(int index, int value) {
      this.index = index;
      this.value = value;
    }
    
    static {
      net.freeback.entries.FBMessageProto.getDescriptor();
    }
  }
  
  public static final class FBMessage extends
      com.google.protobuf.GeneratedMessage {
    // Use FBMessage.newBuilder() to construct.
    private FBMessage() {}
    
    private static final FBMessage defaultInstance = new FBMessage();
    public static FBMessage getDefaultInstance() {
      return defaultInstance;
    }
    
    public FBMessage getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return net.freeback.entries.FBMessageProto.internal_static_net_freeback_FBMessage_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return net.freeback.entries.FBMessageProto.internal_static_net_freeback_FBMessage_fieldAccessorTable;
    }
    
    // required .net.freeback.Header header = 1;
    public static final int HEADER_FIELD_NUMBER = 1;
    private boolean hasHeader;
    private net.freeback.entries.FBMessageProto.Header header_ = net.freeback.entries.FBMessageProto.Header.getDefaultInstance();
    public boolean hasHeader() { return hasHeader; }
    public net.freeback.entries.FBMessageProto.Header getHeader() { return header_; }
    
    // optional bytes bodies = 2;
    public static final int BODIES_FIELD_NUMBER = 2;
    private boolean hasBodies;
    private com.google.protobuf.ByteString bodies_ = com.google.protobuf.ByteString.EMPTY;
    public boolean hasBodies() { return hasBodies; }
    public com.google.protobuf.ByteString getBodies() { return bodies_; }
    
    public final boolean isInitialized() {
      if (!hasHeader) return false;
      if (!getHeader().isInitialized()) return false;
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (hasHeader()) {
        output.writeMessage(1, getHeader());
      }
      if (hasBodies()) {
        output.writeBytes(2, getBodies());
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      if (hasHeader()) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, getHeader());
      }
      if (hasBodies()) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(2, getBodies());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    public static net.freeback.entries.FBMessageProto.FBMessage parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static net.freeback.entries.FBMessageProto.FBMessage parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static net.freeback.entries.FBMessageProto.FBMessage parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static net.freeback.entries.FBMessageProto.FBMessage parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static net.freeback.entries.FBMessageProto.FBMessage parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static net.freeback.entries.FBMessageProto.FBMessage parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static net.freeback.entries.FBMessageProto.FBMessage parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeDelimitedFrom(input).buildParsed();
    }
    public static net.freeback.entries.FBMessageProto.FBMessage parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeDelimitedFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static net.freeback.entries.FBMessageProto.FBMessage parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static net.freeback.entries.FBMessageProto.FBMessage parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(net.freeback.entries.FBMessageProto.FBMessage prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> {
      private net.freeback.entries.FBMessageProto.FBMessage result;
      
      // Construct using net.freeback.entries.FBMessageProto.FBMessage.newBuilder()
      private Builder() {}
      
      private static Builder create() {
        Builder builder = new Builder();
        builder.result = new net.freeback.entries.FBMessageProto.FBMessage();
        return builder;
      }
      
      protected net.freeback.entries.FBMessageProto.FBMessage internalGetResult() {
        return result;
      }
      
      public Builder clear() {
        if (result == null) {
          throw new IllegalStateException(
            "Cannot call clear() after build().");
        }
        result = new net.freeback.entries.FBMessageProto.FBMessage();
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(result);
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return net.freeback.entries.FBMessageProto.FBMessage.getDescriptor();
      }
      
      public net.freeback.entries.FBMessageProto.FBMessage getDefaultInstanceForType() {
        return net.freeback.entries.FBMessageProto.FBMessage.getDefaultInstance();
      }
      
      public boolean isInitialized() {
        return result.isInitialized();
      }
      public net.freeback.entries.FBMessageProto.FBMessage build() {
        if (result != null && !isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return buildPartial();
      }
      
      private net.freeback.entries.FBMessageProto.FBMessage buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        if (!isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return buildPartial();
      }
      
      public net.freeback.entries.FBMessageProto.FBMessage buildPartial() {
        if (result == null) {
          throw new IllegalStateException(
            "build() has already been called on this Builder.");
        }
        net.freeback.entries.FBMessageProto.FBMessage returnMe = result;
        result = null;
        return returnMe;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof net.freeback.entries.FBMessageProto.FBMessage) {
          return mergeFrom((net.freeback.entries.FBMessageProto.FBMessage)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(net.freeback.entries.FBMessageProto.FBMessage other) {
        if (other == net.freeback.entries.FBMessageProto.FBMessage.getDefaultInstance()) return this;
        if (other.hasHeader()) {
          mergeHeader(other.getHeader());
        }
        if (other.hasBodies()) {
          setBodies(other.getBodies());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                return this;
              }
              break;
            }
            case 10: {
              net.freeback.entries.FBMessageProto.Header.Builder subBuilder = net.freeback.entries.FBMessageProto.Header.newBuilder();
              if (hasHeader()) {
                subBuilder.mergeFrom(getHeader());
              }
              input.readMessage(subBuilder, extensionRegistry);
              setHeader(subBuilder.buildPartial());
              break;
            }
            case 18: {
              setBodies(input.readBytes());
              break;
            }
          }
        }
      }
      
      
      // required .net.freeback.Header header = 1;
      public boolean hasHeader() {
        return result.hasHeader();
      }
      public net.freeback.entries.FBMessageProto.Header getHeader() {
        return result.getHeader();
      }
      public Builder setHeader(net.freeback.entries.FBMessageProto.Header value) {
        if (value == null) {
          throw new NullPointerException();
        }
        result.hasHeader = true;
        result.header_ = value;
        return this;
      }
      public Builder setHeader(net.freeback.entries.FBMessageProto.Header.Builder builderForValue) {
        result.hasHeader = true;
        result.header_ = builderForValue.build();
        return this;
      }
      public Builder mergeHeader(net.freeback.entries.FBMessageProto.Header value) {
        if (result.hasHeader() &&
            result.header_ != net.freeback.entries.FBMessageProto.Header.getDefaultInstance()) {
          result.header_ =
            net.freeback.entries.FBMessageProto.Header.newBuilder(result.header_).mergeFrom(value).buildPartial();
        } else {
          result.header_ = value;
        }
        result.hasHeader = true;
        return this;
      }
      public Builder clearHeader() {
        result.hasHeader = false;
        result.header_ = net.freeback.entries.FBMessageProto.Header.getDefaultInstance();
        return this;
      }
      
      // optional bytes bodies = 2;
      public boolean hasBodies() {
        return result.hasBodies();
      }
      public com.google.protobuf.ByteString getBodies() {
        return result.getBodies();
      }
      public Builder setBodies(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  result.hasBodies = true;
        result.bodies_ = value;
        return this;
      }
      public Builder clearBodies() {
        result.hasBodies = false;
        result.bodies_ = getDefaultInstance().getBodies();
        return this;
      }
    }
    
    static {
      net.freeback.entries.FBMessageProto.getDescriptor();
    }
    
    static {
      net.freeback.entries.FBMessageProto.internalForceInit();
    }
  }
  
  public static final class Header extends
      com.google.protobuf.GeneratedMessage {
    // Use Header.newBuilder() to construct.
    private Header() {}
    
    private static final Header defaultInstance = new Header();
    public static Header getDefaultInstance() {
      return defaultInstance;
    }
    
    public Header getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return net.freeback.entries.FBMessageProto.internal_static_net_freeback_Header_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return net.freeback.entries.FBMessageProto.internal_static_net_freeback_Header_fieldAccessorTable;
    }
    
    // required .net.freeback.Notify notify = 1;
    public static final int NOTIFY_FIELD_NUMBER = 1;
    private boolean hasNotify;
    private net.freeback.entries.FBMessageProto.Notify notify_ = net.freeback.entries.FBMessageProto.Notify.Unknown;
    public boolean hasNotify() { return hasNotify; }
    public net.freeback.entries.FBMessageProto.Notify getNotify() { return notify_; }
    
    // required .net.freeback.Action action = 2 [default = None];
    public static final int ACTION_FIELD_NUMBER = 2;
    private boolean hasAction;
    private net.freeback.entries.FBMessageProto.Action action_ = net.freeback.entries.FBMessageProto.Action.None;
    public boolean hasAction() { return hasAction; }
    public net.freeback.entries.FBMessageProto.Action getAction() { return action_; }
    
    // required int32 codecVersion = 3;
    public static final int CODECVERSION_FIELD_NUMBER = 3;
    private boolean hasCodecVersion;
    private int codecVersion_ = 0;
    public boolean hasCodecVersion() { return hasCodecVersion; }
    public int getCodecVersion() { return codecVersion_; }
    
    // optional string sender = 4;
    public static final int SENDER_FIELD_NUMBER = 4;
    private boolean hasSender;
    private java.lang.String sender_ = "";
    public boolean hasSender() { return hasSender; }
    public java.lang.String getSender() { return sender_; }
    
    // optional string receiver = 5;
    public static final int RECEIVER_FIELD_NUMBER = 5;
    private boolean hasReceiver;
    private java.lang.String receiver_ = "";
    public boolean hasReceiver() { return hasReceiver; }
    public java.lang.String getReceiver() { return receiver_; }
    
    // optional string sendtime = 6;
    public static final int SENDTIME_FIELD_NUMBER = 6;
    private boolean hasSendtime;
    private java.lang.String sendtime_ = "";
    public boolean hasSendtime() { return hasSendtime; }
    public java.lang.String getSendtime() { return sendtime_; }
    
    // optional bool response = 7;
    public static final int RESPONSE_FIELD_NUMBER = 7;
    private boolean hasResponse;
    private boolean response_ = false;
    public boolean hasResponse() { return hasResponse; }
    public boolean getResponse() { return response_; }
    
    // optional string text = 8;
    public static final int TEXT_FIELD_NUMBER = 8;
    private boolean hasText;
    private java.lang.String text_ = "";
    public boolean hasText() { return hasText; }
    public java.lang.String getText() { return text_; }
    
    public final boolean isInitialized() {
      if (!hasNotify) return false;
      if (!hasAction) return false;
      if (!hasCodecVersion) return false;
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (hasNotify()) {
        output.writeEnum(1, getNotify().getNumber());
      }
      if (hasAction()) {
        output.writeEnum(2, getAction().getNumber());
      }
      if (hasCodecVersion()) {
        output.writeInt32(3, getCodecVersion());
      }
      if (hasSender()) {
        output.writeString(4, getSender());
      }
      if (hasReceiver()) {
        output.writeString(5, getReceiver());
      }
      if (hasSendtime()) {
        output.writeString(6, getSendtime());
      }
      if (hasResponse()) {
        output.writeBool(7, getResponse());
      }
      if (hasText()) {
        output.writeString(8, getText());
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      if (hasNotify()) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(1, getNotify().getNumber());
      }
      if (hasAction()) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(2, getAction().getNumber());
      }
      if (hasCodecVersion()) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(3, getCodecVersion());
      }
      if (hasSender()) {
        size += com.google.protobuf.CodedOutputStream
          .computeStringSize(4, getSender());
      }
      if (hasReceiver()) {
        size += com.google.protobuf.CodedOutputStream
          .computeStringSize(5, getReceiver());
      }
      if (hasSendtime()) {
        size += com.google.protobuf.CodedOutputStream
          .computeStringSize(6, getSendtime());
      }
      if (hasResponse()) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(7, getResponse());
      }
      if (hasText()) {
        size += com.google.protobuf.CodedOutputStream
          .computeStringSize(8, getText());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    public static net.freeback.entries.FBMessageProto.Header parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static net.freeback.entries.FBMessageProto.Header parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static net.freeback.entries.FBMessageProto.Header parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static net.freeback.entries.FBMessageProto.Header parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static net.freeback.entries.FBMessageProto.Header parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static net.freeback.entries.FBMessageProto.Header parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static net.freeback.entries.FBMessageProto.Header parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeDelimitedFrom(input).buildParsed();
    }
    public static net.freeback.entries.FBMessageProto.Header parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeDelimitedFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static net.freeback.entries.FBMessageProto.Header parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static net.freeback.entries.FBMessageProto.Header parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(net.freeback.entries.FBMessageProto.Header prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> {
      private net.freeback.entries.FBMessageProto.Header result;
      
      // Construct using net.freeback.entries.FBMessageProto.Header.newBuilder()
      private Builder() {}
      
      private static Builder create() {
        Builder builder = new Builder();
        builder.result = new net.freeback.entries.FBMessageProto.Header();
        return builder;
      }
      
      protected net.freeback.entries.FBMessageProto.Header internalGetResult() {
        return result;
      }
      
      public Builder clear() {
        if (result == null) {
          throw new IllegalStateException(
            "Cannot call clear() after build().");
        }
        result = new net.freeback.entries.FBMessageProto.Header();
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(result);
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return net.freeback.entries.FBMessageProto.Header.getDescriptor();
      }
      
      public net.freeback.entries.FBMessageProto.Header getDefaultInstanceForType() {
        return net.freeback.entries.FBMessageProto.Header.getDefaultInstance();
      }
      
      public boolean isInitialized() {
        return result.isInitialized();
      }
      public net.freeback.entries.FBMessageProto.Header build() {
        if (result != null && !isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return buildPartial();
      }
      
      private net.freeback.entries.FBMessageProto.Header buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        if (!isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return buildPartial();
      }
      
      public net.freeback.entries.FBMessageProto.Header buildPartial() {
        if (result == null) {
          throw new IllegalStateException(
            "build() has already been called on this Builder.");
        }
        net.freeback.entries.FBMessageProto.Header returnMe = result;
        result = null;
        return returnMe;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof net.freeback.entries.FBMessageProto.Header) {
          return mergeFrom((net.freeback.entries.FBMessageProto.Header)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(net.freeback.entries.FBMessageProto.Header other) {
        if (other == net.freeback.entries.FBMessageProto.Header.getDefaultInstance()) return this;
        if (other.hasNotify()) {
          setNotify(other.getNotify());
        }
        if (other.hasAction()) {
          setAction(other.getAction());
        }
        if (other.hasCodecVersion()) {
          setCodecVersion(other.getCodecVersion());
        }
        if (other.hasSender()) {
          setSender(other.getSender());
        }
        if (other.hasReceiver()) {
          setReceiver(other.getReceiver());
        }
        if (other.hasSendtime()) {
          setSendtime(other.getSendtime());
        }
        if (other.hasResponse()) {
          setResponse(other.getResponse());
        }
        if (other.hasText()) {
          setText(other.getText());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                return this;
              }
              break;
            }
            case 8: {
              int rawValue = input.readEnum();
              net.freeback.entries.FBMessageProto.Notify value = net.freeback.entries.FBMessageProto.Notify.valueOf(rawValue);
              if (value == null) {
                unknownFields.mergeVarintField(1, rawValue);
              } else {
                setNotify(value);
              }
              break;
            }
            case 16: {
              int rawValue = input.readEnum();
              net.freeback.entries.FBMessageProto.Action value = net.freeback.entries.FBMessageProto.Action.valueOf(rawValue);
              if (value == null) {
                unknownFields.mergeVarintField(2, rawValue);
              } else {
                setAction(value);
              }
              break;
            }
            case 24: {
              setCodecVersion(input.readInt32());
              break;
            }
            case 34: {
              setSender(input.readString());
              break;
            }
            case 42: {
              setReceiver(input.readString());
              break;
            }
            case 50: {
              setSendtime(input.readString());
              break;
            }
            case 56: {
              setResponse(input.readBool());
              break;
            }
            case 66: {
              setText(input.readString());
              break;
            }
          }
        }
      }
      
      
      // required .net.freeback.Notify notify = 1;
      public boolean hasNotify() {
        return result.hasNotify();
      }
      public net.freeback.entries.FBMessageProto.Notify getNotify() {
        return result.getNotify();
      }
      public Builder setNotify(net.freeback.entries.FBMessageProto.Notify value) {
        if (value == null) {
          throw new NullPointerException();
        }
        result.hasNotify = true;
        result.notify_ = value;
        return this;
      }
      public Builder clearNotify() {
        result.hasNotify = false;
        result.notify_ = net.freeback.entries.FBMessageProto.Notify.Unknown;
        return this;
      }
      
      // required .net.freeback.Action action = 2 [default = None];
      public boolean hasAction() {
        return result.hasAction();
      }
      public net.freeback.entries.FBMessageProto.Action getAction() {
        return result.getAction();
      }
      public Builder setAction(net.freeback.entries.FBMessageProto.Action value) {
        if (value == null) {
          throw new NullPointerException();
        }
        result.hasAction = true;
        result.action_ = value;
        return this;
      }
      public Builder clearAction() {
        result.hasAction = false;
        result.action_ = net.freeback.entries.FBMessageProto.Action.None;
        return this;
      }
      
      // required int32 codecVersion = 3;
      public boolean hasCodecVersion() {
        return result.hasCodecVersion();
      }
      public int getCodecVersion() {
        return result.getCodecVersion();
      }
      public Builder setCodecVersion(int value) {
        result.hasCodecVersion = true;
        result.codecVersion_ = value;
        return this;
      }
      public Builder clearCodecVersion() {
        result.hasCodecVersion = false;
        result.codecVersion_ = 0;
        return this;
      }
      
      // optional string sender = 4;
      public boolean hasSender() {
        return result.hasSender();
      }
      public java.lang.String getSender() {
        return result.getSender();
      }
      public Builder setSender(java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  result.hasSender = true;
        result.sender_ = value;
        return this;
      }
      public Builder clearSender() {
        result.hasSender = false;
        result.sender_ = getDefaultInstance().getSender();
        return this;
      }
      
      // optional string receiver = 5;
      public boolean hasReceiver() {
        return result.hasReceiver();
      }
      public java.lang.String getReceiver() {
        return result.getReceiver();
      }
      public Builder setReceiver(java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  result.hasReceiver = true;
        result.receiver_ = value;
        return this;
      }
      public Builder clearReceiver() {
        result.hasReceiver = false;
        result.receiver_ = getDefaultInstance().getReceiver();
        return this;
      }
      
      // optional string sendtime = 6;
      public boolean hasSendtime() {
        return result.hasSendtime();
      }
      public java.lang.String getSendtime() {
        return result.getSendtime();
      }
      public Builder setSendtime(java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  result.hasSendtime = true;
        result.sendtime_ = value;
        return this;
      }
      public Builder clearSendtime() {
        result.hasSendtime = false;
        result.sendtime_ = getDefaultInstance().getSendtime();
        return this;
      }
      
      // optional bool response = 7;
      public boolean hasResponse() {
        return result.hasResponse();
      }
      public boolean getResponse() {
        return result.getResponse();
      }
      public Builder setResponse(boolean value) {
        result.hasResponse = true;
        result.response_ = value;
        return this;
      }
      public Builder clearResponse() {
        result.hasResponse = false;
        result.response_ = false;
        return this;
      }
      
      // optional string text = 8;
      public boolean hasText() {
        return result.hasText();
      }
      public java.lang.String getText() {
        return result.getText();
      }
      public Builder setText(java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  result.hasText = true;
        result.text_ = value;
        return this;
      }
      public Builder clearText() {
        result.hasText = false;
        result.text_ = getDefaultInstance().getText();
        return this;
      }
    }
    
    static {
      net.freeback.entries.FBMessageProto.getDescriptor();
    }
    
    static {
      net.freeback.entries.FBMessageProto.internalForceInit();
    }
  }
  
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_net_freeback_FBMessage_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_net_freeback_FBMessage_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_net_freeback_Header_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_net_freeback_Header_fieldAccessorTable;
  
  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\017FBMessage.proto\022\014net.freeback\"A\n\tFBMes" +
      "sage\022$\n\006header\030\001 \002(\0132\024.net.freeback.Head" +
      "er\022\016\n\006bodies\030\002 \001(\014\"\304\001\n\006Header\022$\n\006notify\030" +
      "\001 \002(\0162\024.net.freeback.Notify\022*\n\006action\030\002 " +
      "\002(\0162\024.net.freeback.Action:\004None\022\024\n\014codec" +
      "Version\030\003 \002(\005\022\016\n\006sender\030\004 \001(\t\022\020\n\010receive" +
      "r\030\005 \001(\t\022\020\n\010sendtime\030\006 \001(\t\022\020\n\010response\030\007 " +
      "\001(\010\022\014\n\004text\030\010 \001(\t*\227\003\n\006Notify\022\014\n\007Unknown\020" +
      "\200\002\022\020\n\013ServerError\020\201\002\022\021\n\rSystemConnect\020\001\022" +
      "\024\n\020SystemDisConnect\020\002\022\016\n\nSystemData\020\003\022\014\n",
      "\010SystemId\020\004\022\020\n\014UserRegister\020\020\022\r\n\tUserLog" +
      "in\020\021\022\016\n\nUserVerify\020\022\022\016\n\nUserLogout\020\023\022\014\n\010" +
      "UserInfo\020\024\022\r\n\tPhotoUser\020 \022\016\n\nPhotoStore\020" +
      "!\022\020\n\014PhotoProduct\020\"\022\r\n\tStoreSave\020P\022\021\n\rSt" +
      "oreFindById\020Q\022\023\n\017StoreFindByBoss\020R\022\020\n\014St" +
      "oreProduct\020S\022\r\n\tStoreDict\020T\022\020\n\013OrderCrea" +
      "te\020\200\002\022\024\n\017OrderAddProduct\020\201\002\022\021\n\014OrderChec" +
      "ked\020\202\002\022\023\n\016OrderUnChecked\020\203\002*2\n\006Action\022\010\n" +
      "\004None\020\000\022\010\n\004Find\020\001\022\010\n\004Save\020\002\022\n\n\006Remove\020\003B" +
      "&\n\024net.freeback.entriesB\016FBMessageProto"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_net_freeback_FBMessage_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_net_freeback_FBMessage_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_net_freeback_FBMessage_descriptor,
              new java.lang.String[] { "Header", "Bodies", },
              net.freeback.entries.FBMessageProto.FBMessage.class,
              net.freeback.entries.FBMessageProto.FBMessage.Builder.class);
          internal_static_net_freeback_Header_descriptor =
            getDescriptor().getMessageTypes().get(1);
          internal_static_net_freeback_Header_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_net_freeback_Header_descriptor,
              new java.lang.String[] { "Notify", "Action", "CodecVersion", "Sender", "Receiver", "Sendtime", "Response", "Text", },
              net.freeback.entries.FBMessageProto.Header.class,
              net.freeback.entries.FBMessageProto.Header.Builder.class);
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }
  
  public static void internalForceInit() {}
}
