// Generated by the protocol buffer compiler.  DO NOT EDIT!

package net.freeback.entries;

public final class FBRegionProto {
  private FBRegionProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public static final class FBRegion extends
      com.google.protobuf.GeneratedMessage {
    // Use FBRegion.newBuilder() to construct.
    private FBRegion() {}
    
    private static final FBRegion defaultInstance = new FBRegion();
    public static FBRegion getDefaultInstance() {
      return defaultInstance;
    }
    
    public FBRegion getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return net.freeback.entries.FBRegionProto.internal_static_net_freeback_FBRegion_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return net.freeback.entries.FBRegionProto.internal_static_net_freeback_FBRegion_fieldAccessorTable;
    }
    
    // repeated .net.freeback.FBProvince provinces = 2;
    public static final int PROVINCES_FIELD_NUMBER = 2;
    private java.util.List<net.freeback.entries.FBRegionProto.FBProvince> provinces_ =
      java.util.Collections.emptyList();
    public java.util.List<net.freeback.entries.FBRegionProto.FBProvince> getProvincesList() {
      return provinces_;
    }
    public int getProvincesCount() { return provinces_.size(); }
    public net.freeback.entries.FBRegionProto.FBProvince getProvinces(int index) {
      return provinces_.get(index);
    }
    
    public final boolean isInitialized() {
      for (net.freeback.entries.FBRegionProto.FBProvince element : getProvincesList()) {
        if (!element.isInitialized()) return false;
      }
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      for (net.freeback.entries.FBRegionProto.FBProvince element : getProvincesList()) {
        output.writeMessage(2, element);
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      for (net.freeback.entries.FBRegionProto.FBProvince element : getProvincesList()) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(2, element);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    public static net.freeback.entries.FBRegionProto.FBRegion parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static net.freeback.entries.FBRegionProto.FBRegion parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static net.freeback.entries.FBRegionProto.FBRegion parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static net.freeback.entries.FBRegionProto.FBRegion parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static net.freeback.entries.FBRegionProto.FBRegion parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static net.freeback.entries.FBRegionProto.FBRegion parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static net.freeback.entries.FBRegionProto.FBRegion parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeDelimitedFrom(input).buildParsed();
    }
    public static net.freeback.entries.FBRegionProto.FBRegion parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeDelimitedFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static net.freeback.entries.FBRegionProto.FBRegion parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static net.freeback.entries.FBRegionProto.FBRegion parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(net.freeback.entries.FBRegionProto.FBRegion prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> {
      private net.freeback.entries.FBRegionProto.FBRegion result;
      
      // Construct using net.freeback.entries.FBRegionProto.FBRegion.newBuilder()
      private Builder() {}
      
      private static Builder create() {
        Builder builder = new Builder();
        builder.result = new net.freeback.entries.FBRegionProto.FBRegion();
        return builder;
      }
      
      protected net.freeback.entries.FBRegionProto.FBRegion internalGetResult() {
        return result;
      }
      
      public Builder clear() {
        if (result == null) {
          throw new IllegalStateException(
            "Cannot call clear() after build().");
        }
        result = new net.freeback.entries.FBRegionProto.FBRegion();
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(result);
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return net.freeback.entries.FBRegionProto.FBRegion.getDescriptor();
      }
      
      public net.freeback.entries.FBRegionProto.FBRegion getDefaultInstanceForType() {
        return net.freeback.entries.FBRegionProto.FBRegion.getDefaultInstance();
      }
      
      public boolean isInitialized() {
        return result.isInitialized();
      }
      public net.freeback.entries.FBRegionProto.FBRegion build() {
        if (result != null && !isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return buildPartial();
      }
      
      private net.freeback.entries.FBRegionProto.FBRegion buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        if (!isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return buildPartial();
      }
      
      public net.freeback.entries.FBRegionProto.FBRegion buildPartial() {
        if (result == null) {
          throw new IllegalStateException(
            "build() has already been called on this Builder.");
        }
        if (result.provinces_ != java.util.Collections.EMPTY_LIST) {
          result.provinces_ =
            java.util.Collections.unmodifiableList(result.provinces_);
        }
        net.freeback.entries.FBRegionProto.FBRegion returnMe = result;
        result = null;
        return returnMe;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof net.freeback.entries.FBRegionProto.FBRegion) {
          return mergeFrom((net.freeback.entries.FBRegionProto.FBRegion)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(net.freeback.entries.FBRegionProto.FBRegion other) {
        if (other == net.freeback.entries.FBRegionProto.FBRegion.getDefaultInstance()) return this;
        if (!other.provinces_.isEmpty()) {
          if (result.provinces_.isEmpty()) {
            result.provinces_ = new java.util.ArrayList<net.freeback.entries.FBRegionProto.FBProvince>();
          }
          result.provinces_.addAll(other.provinces_);
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                return this;
              }
              break;
            }
            case 18: {
              net.freeback.entries.FBRegionProto.FBProvince.Builder subBuilder = net.freeback.entries.FBRegionProto.FBProvince.newBuilder();
              input.readMessage(subBuilder, extensionRegistry);
              addProvinces(subBuilder.buildPartial());
              break;
            }
          }
        }
      }
      
      
      // repeated .net.freeback.FBProvince provinces = 2;
      public java.util.List<net.freeback.entries.FBRegionProto.FBProvince> getProvincesList() {
        return java.util.Collections.unmodifiableList(result.provinces_);
      }
      public int getProvincesCount() {
        return result.getProvincesCount();
      }
      public net.freeback.entries.FBRegionProto.FBProvince getProvinces(int index) {
        return result.getProvinces(index);
      }
      public Builder setProvinces(int index, net.freeback.entries.FBRegionProto.FBProvince value) {
        if (value == null) {
          throw new NullPointerException();
        }
        result.provinces_.set(index, value);
        return this;
      }
      public Builder setProvinces(int index, net.freeback.entries.FBRegionProto.FBProvince.Builder builderForValue) {
        result.provinces_.set(index, builderForValue.build());
        return this;
      }
      public Builder addProvinces(net.freeback.entries.FBRegionProto.FBProvince value) {
        if (value == null) {
          throw new NullPointerException();
        }
        if (result.provinces_.isEmpty()) {
          result.provinces_ = new java.util.ArrayList<net.freeback.entries.FBRegionProto.FBProvince>();
        }
        result.provinces_.add(value);
        return this;
      }
      public Builder addProvinces(net.freeback.entries.FBRegionProto.FBProvince.Builder builderForValue) {
        if (result.provinces_.isEmpty()) {
          result.provinces_ = new java.util.ArrayList<net.freeback.entries.FBRegionProto.FBProvince>();
        }
        result.provinces_.add(builderForValue.build());
        return this;
      }
      public Builder addAllProvinces(
          java.lang.Iterable<? extends net.freeback.entries.FBRegionProto.FBProvince> values) {
        if (result.provinces_.isEmpty()) {
          result.provinces_ = new java.util.ArrayList<net.freeback.entries.FBRegionProto.FBProvince>();
        }
        super.addAll(values, result.provinces_);
        return this;
      }
      public Builder clearProvinces() {
        result.provinces_ = java.util.Collections.emptyList();
        return this;
      }
    }
    
    static {
      net.freeback.entries.FBRegionProto.getDescriptor();
    }
    
    static {
      net.freeback.entries.FBRegionProto.internalForceInit();
    }
  }
  
  public static final class FBProvince extends
      com.google.protobuf.GeneratedMessage {
    // Use FBProvince.newBuilder() to construct.
    private FBProvince() {}
    
    private static final FBProvince defaultInstance = new FBProvince();
    public static FBProvince getDefaultInstance() {
      return defaultInstance;
    }
    
    public FBProvince getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return net.freeback.entries.FBRegionProto.internal_static_net_freeback_FBProvince_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return net.freeback.entries.FBRegionProto.internal_static_net_freeback_FBProvince_fieldAccessorTable;
    }
    
    // optional int32 Code = 2;
    public static final int CODE_FIELD_NUMBER = 2;
    private boolean hasCode;
    private int code_ = 0;
    public boolean hasCode() { return hasCode; }
    public int getCode() { return code_; }
    
    // optional string Name = 3;
    public static final int NAME_FIELD_NUMBER = 3;
    private boolean hasName;
    private java.lang.String name_ = "";
    public boolean hasName() { return hasName; }
    public java.lang.String getName() { return name_; }
    
    // optional int32 DirectCity = 4;
    public static final int DIRECTCITY_FIELD_NUMBER = 4;
    private boolean hasDirectCity;
    private int directCity_ = 0;
    public boolean hasDirectCity() { return hasDirectCity; }
    public int getDirectCity() { return directCity_; }
    
    // repeated .net.freeback.FBCity Cities = 5;
    public static final int CITIES_FIELD_NUMBER = 5;
    private java.util.List<net.freeback.entries.FBRegionProto.FBCity> cities_ =
      java.util.Collections.emptyList();
    public java.util.List<net.freeback.entries.FBRegionProto.FBCity> getCitiesList() {
      return cities_;
    }
    public int getCitiesCount() { return cities_.size(); }
    public net.freeback.entries.FBRegionProto.FBCity getCities(int index) {
      return cities_.get(index);
    }
    
    public final boolean isInitialized() {
      for (net.freeback.entries.FBRegionProto.FBCity element : getCitiesList()) {
        if (!element.isInitialized()) return false;
      }
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (hasCode()) {
        output.writeInt32(2, getCode());
      }
      if (hasName()) {
        output.writeString(3, getName());
      }
      if (hasDirectCity()) {
        output.writeInt32(4, getDirectCity());
      }
      for (net.freeback.entries.FBRegionProto.FBCity element : getCitiesList()) {
        output.writeMessage(5, element);
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      if (hasCode()) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, getCode());
      }
      if (hasName()) {
        size += com.google.protobuf.CodedOutputStream
          .computeStringSize(3, getName());
      }
      if (hasDirectCity()) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(4, getDirectCity());
      }
      for (net.freeback.entries.FBRegionProto.FBCity element : getCitiesList()) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(5, element);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    public static net.freeback.entries.FBRegionProto.FBProvince parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static net.freeback.entries.FBRegionProto.FBProvince parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static net.freeback.entries.FBRegionProto.FBProvince parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static net.freeback.entries.FBRegionProto.FBProvince parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static net.freeback.entries.FBRegionProto.FBProvince parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static net.freeback.entries.FBRegionProto.FBProvince parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static net.freeback.entries.FBRegionProto.FBProvince parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeDelimitedFrom(input).buildParsed();
    }
    public static net.freeback.entries.FBRegionProto.FBProvince parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeDelimitedFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static net.freeback.entries.FBRegionProto.FBProvince parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static net.freeback.entries.FBRegionProto.FBProvince parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(net.freeback.entries.FBRegionProto.FBProvince prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> {
      private net.freeback.entries.FBRegionProto.FBProvince result;
      
      // Construct using net.freeback.entries.FBRegionProto.FBProvince.newBuilder()
      private Builder() {}
      
      private static Builder create() {
        Builder builder = new Builder();
        builder.result = new net.freeback.entries.FBRegionProto.FBProvince();
        return builder;
      }
      
      protected net.freeback.entries.FBRegionProto.FBProvince internalGetResult() {
        return result;
      }
      
      public Builder clear() {
        if (result == null) {
          throw new IllegalStateException(
            "Cannot call clear() after build().");
        }
        result = new net.freeback.entries.FBRegionProto.FBProvince();
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(result);
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return net.freeback.entries.FBRegionProto.FBProvince.getDescriptor();
      }
      
      public net.freeback.entries.FBRegionProto.FBProvince getDefaultInstanceForType() {
        return net.freeback.entries.FBRegionProto.FBProvince.getDefaultInstance();
      }
      
      public boolean isInitialized() {
        return result.isInitialized();
      }
      public net.freeback.entries.FBRegionProto.FBProvince build() {
        if (result != null && !isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return buildPartial();
      }
      
      private net.freeback.entries.FBRegionProto.FBProvince buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        if (!isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return buildPartial();
      }
      
      public net.freeback.entries.FBRegionProto.FBProvince buildPartial() {
        if (result == null) {
          throw new IllegalStateException(
            "build() has already been called on this Builder.");
        }
        if (result.cities_ != java.util.Collections.EMPTY_LIST) {
          result.cities_ =
            java.util.Collections.unmodifiableList(result.cities_);
        }
        net.freeback.entries.FBRegionProto.FBProvince returnMe = result;
        result = null;
        return returnMe;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof net.freeback.entries.FBRegionProto.FBProvince) {
          return mergeFrom((net.freeback.entries.FBRegionProto.FBProvince)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(net.freeback.entries.FBRegionProto.FBProvince other) {
        if (other == net.freeback.entries.FBRegionProto.FBProvince.getDefaultInstance()) return this;
        if (other.hasCode()) {
          setCode(other.getCode());
        }
        if (other.hasName()) {
          setName(other.getName());
        }
        if (other.hasDirectCity()) {
          setDirectCity(other.getDirectCity());
        }
        if (!other.cities_.isEmpty()) {
          if (result.cities_.isEmpty()) {
            result.cities_ = new java.util.ArrayList<net.freeback.entries.FBRegionProto.FBCity>();
          }
          result.cities_.addAll(other.cities_);
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                return this;
              }
              break;
            }
            case 16: {
              setCode(input.readInt32());
              break;
            }
            case 26: {
              setName(input.readString());
              break;
            }
            case 32: {
              setDirectCity(input.readInt32());
              break;
            }
            case 42: {
              net.freeback.entries.FBRegionProto.FBCity.Builder subBuilder = net.freeback.entries.FBRegionProto.FBCity.newBuilder();
              input.readMessage(subBuilder, extensionRegistry);
              addCities(subBuilder.buildPartial());
              break;
            }
          }
        }
      }
      
      
      // optional int32 Code = 2;
      public boolean hasCode() {
        return result.hasCode();
      }
      public int getCode() {
        return result.getCode();
      }
      public Builder setCode(int value) {
        result.hasCode = true;
        result.code_ = value;
        return this;
      }
      public Builder clearCode() {
        result.hasCode = false;
        result.code_ = 0;
        return this;
      }
      
      // optional string Name = 3;
      public boolean hasName() {
        return result.hasName();
      }
      public java.lang.String getName() {
        return result.getName();
      }
      public Builder setName(java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  result.hasName = true;
        result.name_ = value;
        return this;
      }
      public Builder clearName() {
        result.hasName = false;
        result.name_ = getDefaultInstance().getName();
        return this;
      }
      
      // optional int32 DirectCity = 4;
      public boolean hasDirectCity() {
        return result.hasDirectCity();
      }
      public int getDirectCity() {
        return result.getDirectCity();
      }
      public Builder setDirectCity(int value) {
        result.hasDirectCity = true;
        result.directCity_ = value;
        return this;
      }
      public Builder clearDirectCity() {
        result.hasDirectCity = false;
        result.directCity_ = 0;
        return this;
      }
      
      // repeated .net.freeback.FBCity Cities = 5;
      public java.util.List<net.freeback.entries.FBRegionProto.FBCity> getCitiesList() {
        return java.util.Collections.unmodifiableList(result.cities_);
      }
      public int getCitiesCount() {
        return result.getCitiesCount();
      }
      public net.freeback.entries.FBRegionProto.FBCity getCities(int index) {
        return result.getCities(index);
      }
      public Builder setCities(int index, net.freeback.entries.FBRegionProto.FBCity value) {
        if (value == null) {
          throw new NullPointerException();
        }
        result.cities_.set(index, value);
        return this;
      }
      public Builder setCities(int index, net.freeback.entries.FBRegionProto.FBCity.Builder builderForValue) {
        result.cities_.set(index, builderForValue.build());
        return this;
      }
      public Builder addCities(net.freeback.entries.FBRegionProto.FBCity value) {
        if (value == null) {
          throw new NullPointerException();
        }
        if (result.cities_.isEmpty()) {
          result.cities_ = new java.util.ArrayList<net.freeback.entries.FBRegionProto.FBCity>();
        }
        result.cities_.add(value);
        return this;
      }
      public Builder addCities(net.freeback.entries.FBRegionProto.FBCity.Builder builderForValue) {
        if (result.cities_.isEmpty()) {
          result.cities_ = new java.util.ArrayList<net.freeback.entries.FBRegionProto.FBCity>();
        }
        result.cities_.add(builderForValue.build());
        return this;
      }
      public Builder addAllCities(
          java.lang.Iterable<? extends net.freeback.entries.FBRegionProto.FBCity> values) {
        if (result.cities_.isEmpty()) {
          result.cities_ = new java.util.ArrayList<net.freeback.entries.FBRegionProto.FBCity>();
        }
        super.addAll(values, result.cities_);
        return this;
      }
      public Builder clearCities() {
        result.cities_ = java.util.Collections.emptyList();
        return this;
      }
    }
    
    static {
      net.freeback.entries.FBRegionProto.getDescriptor();
    }
    
    static {
      net.freeback.entries.FBRegionProto.internalForceInit();
    }
  }
  
  public static final class FBCity extends
      com.google.protobuf.GeneratedMessage {
    // Use FBCity.newBuilder() to construct.
    private FBCity() {}
    
    private static final FBCity defaultInstance = new FBCity();
    public static FBCity getDefaultInstance() {
      return defaultInstance;
    }
    
    public FBCity getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return net.freeback.entries.FBRegionProto.internal_static_net_freeback_FBCity_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return net.freeback.entries.FBRegionProto.internal_static_net_freeback_FBCity_fieldAccessorTable;
    }
    
    // required int32 Code = 1;
    public static final int CODE_FIELD_NUMBER = 1;
    private boolean hasCode;
    private int code_ = 0;
    public boolean hasCode() { return hasCode; }
    public int getCode() { return code_; }
    
    // required string Name = 2;
    public static final int NAME_FIELD_NUMBER = 2;
    private boolean hasName;
    private java.lang.String name_ = "";
    public boolean hasName() { return hasName; }
    public java.lang.String getName() { return name_; }
    
    // repeated .net.freeback.FBArea Areas = 4;
    public static final int AREAS_FIELD_NUMBER = 4;
    private java.util.List<net.freeback.entries.FBRegionProto.FBArea> areas_ =
      java.util.Collections.emptyList();
    public java.util.List<net.freeback.entries.FBRegionProto.FBArea> getAreasList() {
      return areas_;
    }
    public int getAreasCount() { return areas_.size(); }
    public net.freeback.entries.FBRegionProto.FBArea getAreas(int index) {
      return areas_.get(index);
    }
    
    public final boolean isInitialized() {
      if (!hasCode) return false;
      if (!hasName) return false;
      for (net.freeback.entries.FBRegionProto.FBArea element : getAreasList()) {
        if (!element.isInitialized()) return false;
      }
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (hasCode()) {
        output.writeInt32(1, getCode());
      }
      if (hasName()) {
        output.writeString(2, getName());
      }
      for (net.freeback.entries.FBRegionProto.FBArea element : getAreasList()) {
        output.writeMessage(4, element);
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      if (hasCode()) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, getCode());
      }
      if (hasName()) {
        size += com.google.protobuf.CodedOutputStream
          .computeStringSize(2, getName());
      }
      for (net.freeback.entries.FBRegionProto.FBArea element : getAreasList()) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(4, element);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    public static net.freeback.entries.FBRegionProto.FBCity parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static net.freeback.entries.FBRegionProto.FBCity parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static net.freeback.entries.FBRegionProto.FBCity parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static net.freeback.entries.FBRegionProto.FBCity parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static net.freeback.entries.FBRegionProto.FBCity parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static net.freeback.entries.FBRegionProto.FBCity parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static net.freeback.entries.FBRegionProto.FBCity parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeDelimitedFrom(input).buildParsed();
    }
    public static net.freeback.entries.FBRegionProto.FBCity parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeDelimitedFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static net.freeback.entries.FBRegionProto.FBCity parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static net.freeback.entries.FBRegionProto.FBCity parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(net.freeback.entries.FBRegionProto.FBCity prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> {
      private net.freeback.entries.FBRegionProto.FBCity result;
      
      // Construct using net.freeback.entries.FBRegionProto.FBCity.newBuilder()
      private Builder() {}
      
      private static Builder create() {
        Builder builder = new Builder();
        builder.result = new net.freeback.entries.FBRegionProto.FBCity();
        return builder;
      }
      
      protected net.freeback.entries.FBRegionProto.FBCity internalGetResult() {
        return result;
      }
      
      public Builder clear() {
        if (result == null) {
          throw new IllegalStateException(
            "Cannot call clear() after build().");
        }
        result = new net.freeback.entries.FBRegionProto.FBCity();
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(result);
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return net.freeback.entries.FBRegionProto.FBCity.getDescriptor();
      }
      
      public net.freeback.entries.FBRegionProto.FBCity getDefaultInstanceForType() {
        return net.freeback.entries.FBRegionProto.FBCity.getDefaultInstance();
      }
      
      public boolean isInitialized() {
        return result.isInitialized();
      }
      public net.freeback.entries.FBRegionProto.FBCity build() {
        if (result != null && !isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return buildPartial();
      }
      
      private net.freeback.entries.FBRegionProto.FBCity buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        if (!isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return buildPartial();
      }
      
      public net.freeback.entries.FBRegionProto.FBCity buildPartial() {
        if (result == null) {
          throw new IllegalStateException(
            "build() has already been called on this Builder.");
        }
        if (result.areas_ != java.util.Collections.EMPTY_LIST) {
          result.areas_ =
            java.util.Collections.unmodifiableList(result.areas_);
        }
        net.freeback.entries.FBRegionProto.FBCity returnMe = result;
        result = null;
        return returnMe;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof net.freeback.entries.FBRegionProto.FBCity) {
          return mergeFrom((net.freeback.entries.FBRegionProto.FBCity)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(net.freeback.entries.FBRegionProto.FBCity other) {
        if (other == net.freeback.entries.FBRegionProto.FBCity.getDefaultInstance()) return this;
        if (other.hasCode()) {
          setCode(other.getCode());
        }
        if (other.hasName()) {
          setName(other.getName());
        }
        if (!other.areas_.isEmpty()) {
          if (result.areas_.isEmpty()) {
            result.areas_ = new java.util.ArrayList<net.freeback.entries.FBRegionProto.FBArea>();
          }
          result.areas_.addAll(other.areas_);
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                return this;
              }
              break;
            }
            case 8: {
              setCode(input.readInt32());
              break;
            }
            case 18: {
              setName(input.readString());
              break;
            }
            case 34: {
              net.freeback.entries.FBRegionProto.FBArea.Builder subBuilder = net.freeback.entries.FBRegionProto.FBArea.newBuilder();
              input.readMessage(subBuilder, extensionRegistry);
              addAreas(subBuilder.buildPartial());
              break;
            }
          }
        }
      }
      
      
      // required int32 Code = 1;
      public boolean hasCode() {
        return result.hasCode();
      }
      public int getCode() {
        return result.getCode();
      }
      public Builder setCode(int value) {
        result.hasCode = true;
        result.code_ = value;
        return this;
      }
      public Builder clearCode() {
        result.hasCode = false;
        result.code_ = 0;
        return this;
      }
      
      // required string Name = 2;
      public boolean hasName() {
        return result.hasName();
      }
      public java.lang.String getName() {
        return result.getName();
      }
      public Builder setName(java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  result.hasName = true;
        result.name_ = value;
        return this;
      }
      public Builder clearName() {
        result.hasName = false;
        result.name_ = getDefaultInstance().getName();
        return this;
      }
      
      // repeated .net.freeback.FBArea Areas = 4;
      public java.util.List<net.freeback.entries.FBRegionProto.FBArea> getAreasList() {
        return java.util.Collections.unmodifiableList(result.areas_);
      }
      public int getAreasCount() {
        return result.getAreasCount();
      }
      public net.freeback.entries.FBRegionProto.FBArea getAreas(int index) {
        return result.getAreas(index);
      }
      public Builder setAreas(int index, net.freeback.entries.FBRegionProto.FBArea value) {
        if (value == null) {
          throw new NullPointerException();
        }
        result.areas_.set(index, value);
        return this;
      }
      public Builder setAreas(int index, net.freeback.entries.FBRegionProto.FBArea.Builder builderForValue) {
        result.areas_.set(index, builderForValue.build());
        return this;
      }
      public Builder addAreas(net.freeback.entries.FBRegionProto.FBArea value) {
        if (value == null) {
          throw new NullPointerException();
        }
        if (result.areas_.isEmpty()) {
          result.areas_ = new java.util.ArrayList<net.freeback.entries.FBRegionProto.FBArea>();
        }
        result.areas_.add(value);
        return this;
      }
      public Builder addAreas(net.freeback.entries.FBRegionProto.FBArea.Builder builderForValue) {
        if (result.areas_.isEmpty()) {
          result.areas_ = new java.util.ArrayList<net.freeback.entries.FBRegionProto.FBArea>();
        }
        result.areas_.add(builderForValue.build());
        return this;
      }
      public Builder addAllAreas(
          java.lang.Iterable<? extends net.freeback.entries.FBRegionProto.FBArea> values) {
        if (result.areas_.isEmpty()) {
          result.areas_ = new java.util.ArrayList<net.freeback.entries.FBRegionProto.FBArea>();
        }
        super.addAll(values, result.areas_);
        return this;
      }
      public Builder clearAreas() {
        result.areas_ = java.util.Collections.emptyList();
        return this;
      }
    }
    
    static {
      net.freeback.entries.FBRegionProto.getDescriptor();
    }
    
    static {
      net.freeback.entries.FBRegionProto.internalForceInit();
    }
  }
  
  public static final class FBArea extends
      com.google.protobuf.GeneratedMessage {
    // Use FBArea.newBuilder() to construct.
    private FBArea() {}
    
    private static final FBArea defaultInstance = new FBArea();
    public static FBArea getDefaultInstance() {
      return defaultInstance;
    }
    
    public FBArea getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return net.freeback.entries.FBRegionProto.internal_static_net_freeback_FBArea_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return net.freeback.entries.FBRegionProto.internal_static_net_freeback_FBArea_fieldAccessorTable;
    }
    
    // required int32 Code = 1;
    public static final int CODE_FIELD_NUMBER = 1;
    private boolean hasCode;
    private int code_ = 0;
    public boolean hasCode() { return hasCode; }
    public int getCode() { return code_; }
    
    // required string Name = 2;
    public static final int NAME_FIELD_NUMBER = 2;
    private boolean hasName;
    private java.lang.String name_ = "";
    public boolean hasName() { return hasName; }
    public java.lang.String getName() { return name_; }
    
    public final boolean isInitialized() {
      if (!hasCode) return false;
      if (!hasName) return false;
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (hasCode()) {
        output.writeInt32(1, getCode());
      }
      if (hasName()) {
        output.writeString(2, getName());
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      if (hasCode()) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, getCode());
      }
      if (hasName()) {
        size += com.google.protobuf.CodedOutputStream
          .computeStringSize(2, getName());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    public static net.freeback.entries.FBRegionProto.FBArea parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static net.freeback.entries.FBRegionProto.FBArea parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static net.freeback.entries.FBRegionProto.FBArea parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static net.freeback.entries.FBRegionProto.FBArea parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static net.freeback.entries.FBRegionProto.FBArea parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static net.freeback.entries.FBRegionProto.FBArea parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static net.freeback.entries.FBRegionProto.FBArea parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeDelimitedFrom(input).buildParsed();
    }
    public static net.freeback.entries.FBRegionProto.FBArea parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeDelimitedFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static net.freeback.entries.FBRegionProto.FBArea parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static net.freeback.entries.FBRegionProto.FBArea parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(net.freeback.entries.FBRegionProto.FBArea prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> {
      private net.freeback.entries.FBRegionProto.FBArea result;
      
      // Construct using net.freeback.entries.FBRegionProto.FBArea.newBuilder()
      private Builder() {}
      
      private static Builder create() {
        Builder builder = new Builder();
        builder.result = new net.freeback.entries.FBRegionProto.FBArea();
        return builder;
      }
      
      protected net.freeback.entries.FBRegionProto.FBArea internalGetResult() {
        return result;
      }
      
      public Builder clear() {
        if (result == null) {
          throw new IllegalStateException(
            "Cannot call clear() after build().");
        }
        result = new net.freeback.entries.FBRegionProto.FBArea();
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(result);
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return net.freeback.entries.FBRegionProto.FBArea.getDescriptor();
      }
      
      public net.freeback.entries.FBRegionProto.FBArea getDefaultInstanceForType() {
        return net.freeback.entries.FBRegionProto.FBArea.getDefaultInstance();
      }
      
      public boolean isInitialized() {
        return result.isInitialized();
      }
      public net.freeback.entries.FBRegionProto.FBArea build() {
        if (result != null && !isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return buildPartial();
      }
      
      private net.freeback.entries.FBRegionProto.FBArea buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        if (!isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return buildPartial();
      }
      
      public net.freeback.entries.FBRegionProto.FBArea buildPartial() {
        if (result == null) {
          throw new IllegalStateException(
            "build() has already been called on this Builder.");
        }
        net.freeback.entries.FBRegionProto.FBArea returnMe = result;
        result = null;
        return returnMe;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof net.freeback.entries.FBRegionProto.FBArea) {
          return mergeFrom((net.freeback.entries.FBRegionProto.FBArea)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(net.freeback.entries.FBRegionProto.FBArea other) {
        if (other == net.freeback.entries.FBRegionProto.FBArea.getDefaultInstance()) return this;
        if (other.hasCode()) {
          setCode(other.getCode());
        }
        if (other.hasName()) {
          setName(other.getName());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                return this;
              }
              break;
            }
            case 8: {
              setCode(input.readInt32());
              break;
            }
            case 18: {
              setName(input.readString());
              break;
            }
          }
        }
      }
      
      
      // required int32 Code = 1;
      public boolean hasCode() {
        return result.hasCode();
      }
      public int getCode() {
        return result.getCode();
      }
      public Builder setCode(int value) {
        result.hasCode = true;
        result.code_ = value;
        return this;
      }
      public Builder clearCode() {
        result.hasCode = false;
        result.code_ = 0;
        return this;
      }
      
      // required string Name = 2;
      public boolean hasName() {
        return result.hasName();
      }
      public java.lang.String getName() {
        return result.getName();
      }
      public Builder setName(java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  result.hasName = true;
        result.name_ = value;
        return this;
      }
      public Builder clearName() {
        result.hasName = false;
        result.name_ = getDefaultInstance().getName();
        return this;
      }
    }
    
    static {
      net.freeback.entries.FBRegionProto.getDescriptor();
    }
    
    static {
      net.freeback.entries.FBRegionProto.internalForceInit();
    }
  }
  
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_net_freeback_FBRegion_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_net_freeback_FBRegion_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_net_freeback_FBProvince_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_net_freeback_FBProvince_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_net_freeback_FBCity_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_net_freeback_FBCity_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_net_freeback_FBArea_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_net_freeback_FBArea_fieldAccessorTable;
  
  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\016FBRegion.proto\022\014net.freeback\"7\n\010FBRegi" +
      "on\022+\n\tprovinces\030\002 \003(\0132\030.net.freeback.FBP" +
      "rovince\"b\n\nFBProvince\022\014\n\004Code\030\002 \001(\005\022\014\n\004N" +
      "ame\030\003 \001(\t\022\022\n\nDirectCity\030\004 \001(\005\022$\n\006Cities\030" +
      "\005 \003(\0132\024.net.freeback.FBCity\"I\n\006FBCity\022\014\n" +
      "\004Code\030\001 \002(\005\022\014\n\004Name\030\002 \002(\t\022#\n\005Areas\030\004 \003(\013" +
      "2\024.net.freeback.FBArea\"$\n\006FBArea\022\014\n\004Code" +
      "\030\001 \002(\005\022\014\n\004Name\030\002 \002(\tB%\n\024net.freeback.ent" +
      "riesB\rFBRegionProto"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_net_freeback_FBRegion_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_net_freeback_FBRegion_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_net_freeback_FBRegion_descriptor,
              new java.lang.String[] { "Provinces", },
              net.freeback.entries.FBRegionProto.FBRegion.class,
              net.freeback.entries.FBRegionProto.FBRegion.Builder.class);
          internal_static_net_freeback_FBProvince_descriptor =
            getDescriptor().getMessageTypes().get(1);
          internal_static_net_freeback_FBProvince_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_net_freeback_FBProvince_descriptor,
              new java.lang.String[] { "Code", "Name", "DirectCity", "Cities", },
              net.freeback.entries.FBRegionProto.FBProvince.class,
              net.freeback.entries.FBRegionProto.FBProvince.Builder.class);
          internal_static_net_freeback_FBCity_descriptor =
            getDescriptor().getMessageTypes().get(2);
          internal_static_net_freeback_FBCity_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_net_freeback_FBCity_descriptor,
              new java.lang.String[] { "Code", "Name", "Areas", },
              net.freeback.entries.FBRegionProto.FBCity.class,
              net.freeback.entries.FBRegionProto.FBCity.Builder.class);
          internal_static_net_freeback_FBArea_descriptor =
            getDescriptor().getMessageTypes().get(3);
          internal_static_net_freeback_FBArea_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_net_freeback_FBArea_descriptor,
              new java.lang.String[] { "Code", "Name", },
              net.freeback.entries.FBRegionProto.FBArea.class,
              net.freeback.entries.FBRegionProto.FBArea.Builder.class);
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }
  
  public static void internalForceInit() {}
}
