// Generated by the protocol buffer compiler.  DO NOT EDIT!

package net.freeback.entries;

public final class FBSystemProto {
  private FBSystemProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public static final class FBSystem extends
      com.google.protobuf.GeneratedMessage {
    // Use FBSystem.newBuilder() to construct.
    private FBSystem() {}
    
    private static final FBSystem defaultInstance = new FBSystem();
    public static FBSystem getDefaultInstance() {
      return defaultInstance;
    }
    
    public FBSystem getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return net.freeback.entries.FBSystemProto.internal_static_net_freeback_FBSystem_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return net.freeback.entries.FBSystemProto.internal_static_net_freeback_FBSystem_fieldAccessorTable;
    }
    
    // required int32 VersionValue = 1;
    public static final int VERSIONVALUE_FIELD_NUMBER = 1;
    private boolean hasVersionValue;
    private int versionValue_ = 0;
    public boolean hasVersionValue() { return hasVersionValue; }
    public int getVersionValue() { return versionValue_; }
    
    // required .net.freeback.FBRegion Region = 2;
    public static final int REGION_FIELD_NUMBER = 2;
    private boolean hasRegion;
    private net.freeback.entries.FBRegionProto.FBRegion region_ = net.freeback.entries.FBRegionProto.FBRegion.getDefaultInstance();
    public boolean hasRegion() { return hasRegion; }
    public net.freeback.entries.FBRegionProto.FBRegion getRegion() { return region_; }
    
    // repeated .net.freeback.FBIndustry Industires = 4;
    public static final int INDUSTIRES_FIELD_NUMBER = 4;
    private java.util.List<net.freeback.entries.FBSystemProto.FBIndustry> industires_ =
      java.util.Collections.emptyList();
    public java.util.List<net.freeback.entries.FBSystemProto.FBIndustry> getIndustiresList() {
      return industires_;
    }
    public int getIndustiresCount() { return industires_.size(); }
    public net.freeback.entries.FBSystemProto.FBIndustry getIndustires(int index) {
      return industires_.get(index);
    }
    
    // repeated .net.freeback.FBCategory Categories = 5;
    public static final int CATEGORIES_FIELD_NUMBER = 5;
    private java.util.List<net.freeback.entries.FBSystemProto.FBCategory> categories_ =
      java.util.Collections.emptyList();
    public java.util.List<net.freeback.entries.FBSystemProto.FBCategory> getCategoriesList() {
      return categories_;
    }
    public int getCategoriesCount() { return categories_.size(); }
    public net.freeback.entries.FBSystemProto.FBCategory getCategories(int index) {
      return categories_.get(index);
    }
    
    // repeated .net.freeback.FBDimension Dimensions = 6;
    public static final int DIMENSIONS_FIELD_NUMBER = 6;
    private java.util.List<net.freeback.entries.FBSystemProto.FBDimension> dimensions_ =
      java.util.Collections.emptyList();
    public java.util.List<net.freeback.entries.FBSystemProto.FBDimension> getDimensionsList() {
      return dimensions_;
    }
    public int getDimensionsCount() { return dimensions_.size(); }
    public net.freeback.entries.FBSystemProto.FBDimension getDimensions(int index) {
      return dimensions_.get(index);
    }
    
    public final boolean isInitialized() {
      if (!hasVersionValue) return false;
      if (!hasRegion) return false;
      if (!getRegion().isInitialized()) return false;
      for (net.freeback.entries.FBSystemProto.FBIndustry element : getIndustiresList()) {
        if (!element.isInitialized()) return false;
      }
      for (net.freeback.entries.FBSystemProto.FBCategory element : getCategoriesList()) {
        if (!element.isInitialized()) return false;
      }
      for (net.freeback.entries.FBSystemProto.FBDimension element : getDimensionsList()) {
        if (!element.isInitialized()) return false;
      }
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (hasVersionValue()) {
        output.writeInt32(1, getVersionValue());
      }
      if (hasRegion()) {
        output.writeMessage(2, getRegion());
      }
      for (net.freeback.entries.FBSystemProto.FBIndustry element : getIndustiresList()) {
        output.writeMessage(4, element);
      }
      for (net.freeback.entries.FBSystemProto.FBCategory element : getCategoriesList()) {
        output.writeMessage(5, element);
      }
      for (net.freeback.entries.FBSystemProto.FBDimension element : getDimensionsList()) {
        output.writeMessage(6, element);
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      if (hasVersionValue()) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, getVersionValue());
      }
      if (hasRegion()) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(2, getRegion());
      }
      for (net.freeback.entries.FBSystemProto.FBIndustry element : getIndustiresList()) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(4, element);
      }
      for (net.freeback.entries.FBSystemProto.FBCategory element : getCategoriesList()) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(5, element);
      }
      for (net.freeback.entries.FBSystemProto.FBDimension element : getDimensionsList()) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(6, element);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    public static net.freeback.entries.FBSystemProto.FBSystem parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static net.freeback.entries.FBSystemProto.FBSystem parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static net.freeback.entries.FBSystemProto.FBSystem parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static net.freeback.entries.FBSystemProto.FBSystem parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static net.freeback.entries.FBSystemProto.FBSystem parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static net.freeback.entries.FBSystemProto.FBSystem parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static net.freeback.entries.FBSystemProto.FBSystem parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeDelimitedFrom(input).buildParsed();
    }
    public static net.freeback.entries.FBSystemProto.FBSystem parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeDelimitedFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static net.freeback.entries.FBSystemProto.FBSystem parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static net.freeback.entries.FBSystemProto.FBSystem parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(net.freeback.entries.FBSystemProto.FBSystem prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> {
      private net.freeback.entries.FBSystemProto.FBSystem result;
      
      // Construct using net.freeback.entries.FBSystemProto.FBSystem.newBuilder()
      private Builder() {}
      
      private static Builder create() {
        Builder builder = new Builder();
        builder.result = new net.freeback.entries.FBSystemProto.FBSystem();
        return builder;
      }
      
      protected net.freeback.entries.FBSystemProto.FBSystem internalGetResult() {
        return result;
      }
      
      public Builder clear() {
        if (result == null) {
          throw new IllegalStateException(
            "Cannot call clear() after build().");
        }
        result = new net.freeback.entries.FBSystemProto.FBSystem();
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(result);
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return net.freeback.entries.FBSystemProto.FBSystem.getDescriptor();
      }
      
      public net.freeback.entries.FBSystemProto.FBSystem getDefaultInstanceForType() {
        return net.freeback.entries.FBSystemProto.FBSystem.getDefaultInstance();
      }
      
      public boolean isInitialized() {
        return result.isInitialized();
      }
      public net.freeback.entries.FBSystemProto.FBSystem build() {
        if (result != null && !isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return buildPartial();
      }
      
      private net.freeback.entries.FBSystemProto.FBSystem buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        if (!isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return buildPartial();
      }
      
      public net.freeback.entries.FBSystemProto.FBSystem buildPartial() {
        if (result == null) {
          throw new IllegalStateException(
            "build() has already been called on this Builder.");
        }
        if (result.industires_ != java.util.Collections.EMPTY_LIST) {
          result.industires_ =
            java.util.Collections.unmodifiableList(result.industires_);
        }
        if (result.categories_ != java.util.Collections.EMPTY_LIST) {
          result.categories_ =
            java.util.Collections.unmodifiableList(result.categories_);
        }
        if (result.dimensions_ != java.util.Collections.EMPTY_LIST) {
          result.dimensions_ =
            java.util.Collections.unmodifiableList(result.dimensions_);
        }
        net.freeback.entries.FBSystemProto.FBSystem returnMe = result;
        result = null;
        return returnMe;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof net.freeback.entries.FBSystemProto.FBSystem) {
          return mergeFrom((net.freeback.entries.FBSystemProto.FBSystem)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(net.freeback.entries.FBSystemProto.FBSystem other) {
        if (other == net.freeback.entries.FBSystemProto.FBSystem.getDefaultInstance()) return this;
        if (other.hasVersionValue()) {
          setVersionValue(other.getVersionValue());
        }
        if (other.hasRegion()) {
          mergeRegion(other.getRegion());
        }
        if (!other.industires_.isEmpty()) {
          if (result.industires_.isEmpty()) {
            result.industires_ = new java.util.ArrayList<net.freeback.entries.FBSystemProto.FBIndustry>();
          }
          result.industires_.addAll(other.industires_);
        }
        if (!other.categories_.isEmpty()) {
          if (result.categories_.isEmpty()) {
            result.categories_ = new java.util.ArrayList<net.freeback.entries.FBSystemProto.FBCategory>();
          }
          result.categories_.addAll(other.categories_);
        }
        if (!other.dimensions_.isEmpty()) {
          if (result.dimensions_.isEmpty()) {
            result.dimensions_ = new java.util.ArrayList<net.freeback.entries.FBSystemProto.FBDimension>();
          }
          result.dimensions_.addAll(other.dimensions_);
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                return this;
              }
              break;
            }
            case 8: {
              setVersionValue(input.readInt32());
              break;
            }
            case 18: {
              net.freeback.entries.FBRegionProto.FBRegion.Builder subBuilder = net.freeback.entries.FBRegionProto.FBRegion.newBuilder();
              if (hasRegion()) {
                subBuilder.mergeFrom(getRegion());
              }
              input.readMessage(subBuilder, extensionRegistry);
              setRegion(subBuilder.buildPartial());
              break;
            }
            case 34: {
              net.freeback.entries.FBSystemProto.FBIndustry.Builder subBuilder = net.freeback.entries.FBSystemProto.FBIndustry.newBuilder();
              input.readMessage(subBuilder, extensionRegistry);
              addIndustires(subBuilder.buildPartial());
              break;
            }
            case 42: {
              net.freeback.entries.FBSystemProto.FBCategory.Builder subBuilder = net.freeback.entries.FBSystemProto.FBCategory.newBuilder();
              input.readMessage(subBuilder, extensionRegistry);
              addCategories(subBuilder.buildPartial());
              break;
            }
            case 50: {
              net.freeback.entries.FBSystemProto.FBDimension.Builder subBuilder = net.freeback.entries.FBSystemProto.FBDimension.newBuilder();
              input.readMessage(subBuilder, extensionRegistry);
              addDimensions(subBuilder.buildPartial());
              break;
            }
          }
        }
      }
      
      
      // required int32 VersionValue = 1;
      public boolean hasVersionValue() {
        return result.hasVersionValue();
      }
      public int getVersionValue() {
        return result.getVersionValue();
      }
      public Builder setVersionValue(int value) {
        result.hasVersionValue = true;
        result.versionValue_ = value;
        return this;
      }
      public Builder clearVersionValue() {
        result.hasVersionValue = false;
        result.versionValue_ = 0;
        return this;
      }
      
      // required .net.freeback.FBRegion Region = 2;
      public boolean hasRegion() {
        return result.hasRegion();
      }
      public net.freeback.entries.FBRegionProto.FBRegion getRegion() {
        return result.getRegion();
      }
      public Builder setRegion(net.freeback.entries.FBRegionProto.FBRegion value) {
        if (value == null) {
          throw new NullPointerException();
        }
        result.hasRegion = true;
        result.region_ = value;
        return this;
      }
      public Builder setRegion(net.freeback.entries.FBRegionProto.FBRegion.Builder builderForValue) {
        result.hasRegion = true;
        result.region_ = builderForValue.build();
        return this;
      }
      public Builder mergeRegion(net.freeback.entries.FBRegionProto.FBRegion value) {
        if (result.hasRegion() &&
            result.region_ != net.freeback.entries.FBRegionProto.FBRegion.getDefaultInstance()) {
          result.region_ =
            net.freeback.entries.FBRegionProto.FBRegion.newBuilder(result.region_).mergeFrom(value).buildPartial();
        } else {
          result.region_ = value;
        }
        result.hasRegion = true;
        return this;
      }
      public Builder clearRegion() {
        result.hasRegion = false;
        result.region_ = net.freeback.entries.FBRegionProto.FBRegion.getDefaultInstance();
        return this;
      }
      
      // repeated .net.freeback.FBIndustry Industires = 4;
      public java.util.List<net.freeback.entries.FBSystemProto.FBIndustry> getIndustiresList() {
        return java.util.Collections.unmodifiableList(result.industires_);
      }
      public int getIndustiresCount() {
        return result.getIndustiresCount();
      }
      public net.freeback.entries.FBSystemProto.FBIndustry getIndustires(int index) {
        return result.getIndustires(index);
      }
      public Builder setIndustires(int index, net.freeback.entries.FBSystemProto.FBIndustry value) {
        if (value == null) {
          throw new NullPointerException();
        }
        result.industires_.set(index, value);
        return this;
      }
      public Builder setIndustires(int index, net.freeback.entries.FBSystemProto.FBIndustry.Builder builderForValue) {
        result.industires_.set(index, builderForValue.build());
        return this;
      }
      public Builder addIndustires(net.freeback.entries.FBSystemProto.FBIndustry value) {
        if (value == null) {
          throw new NullPointerException();
        }
        if (result.industires_.isEmpty()) {
          result.industires_ = new java.util.ArrayList<net.freeback.entries.FBSystemProto.FBIndustry>();
        }
        result.industires_.add(value);
        return this;
      }
      public Builder addIndustires(net.freeback.entries.FBSystemProto.FBIndustry.Builder builderForValue) {
        if (result.industires_.isEmpty()) {
          result.industires_ = new java.util.ArrayList<net.freeback.entries.FBSystemProto.FBIndustry>();
        }
        result.industires_.add(builderForValue.build());
        return this;
      }
      public Builder addAllIndustires(
          java.lang.Iterable<? extends net.freeback.entries.FBSystemProto.FBIndustry> values) {
        if (result.industires_.isEmpty()) {
          result.industires_ = new java.util.ArrayList<net.freeback.entries.FBSystemProto.FBIndustry>();
        }
        super.addAll(values, result.industires_);
        return this;
      }
      public Builder clearIndustires() {
        result.industires_ = java.util.Collections.emptyList();
        return this;
      }
      
      // repeated .net.freeback.FBCategory Categories = 5;
      public java.util.List<net.freeback.entries.FBSystemProto.FBCategory> getCategoriesList() {
        return java.util.Collections.unmodifiableList(result.categories_);
      }
      public int getCategoriesCount() {
        return result.getCategoriesCount();
      }
      public net.freeback.entries.FBSystemProto.FBCategory getCategories(int index) {
        return result.getCategories(index);
      }
      public Builder setCategories(int index, net.freeback.entries.FBSystemProto.FBCategory value) {
        if (value == null) {
          throw new NullPointerException();
        }
        result.categories_.set(index, value);
        return this;
      }
      public Builder setCategories(int index, net.freeback.entries.FBSystemProto.FBCategory.Builder builderForValue) {
        result.categories_.set(index, builderForValue.build());
        return this;
      }
      public Builder addCategories(net.freeback.entries.FBSystemProto.FBCategory value) {
        if (value == null) {
          throw new NullPointerException();
        }
        if (result.categories_.isEmpty()) {
          result.categories_ = new java.util.ArrayList<net.freeback.entries.FBSystemProto.FBCategory>();
        }
        result.categories_.add(value);
        return this;
      }
      public Builder addCategories(net.freeback.entries.FBSystemProto.FBCategory.Builder builderForValue) {
        if (result.categories_.isEmpty()) {
          result.categories_ = new java.util.ArrayList<net.freeback.entries.FBSystemProto.FBCategory>();
        }
        result.categories_.add(builderForValue.build());
        return this;
      }
      public Builder addAllCategories(
          java.lang.Iterable<? extends net.freeback.entries.FBSystemProto.FBCategory> values) {
        if (result.categories_.isEmpty()) {
          result.categories_ = new java.util.ArrayList<net.freeback.entries.FBSystemProto.FBCategory>();
        }
        super.addAll(values, result.categories_);
        return this;
      }
      public Builder clearCategories() {
        result.categories_ = java.util.Collections.emptyList();
        return this;
      }
      
      // repeated .net.freeback.FBDimension Dimensions = 6;
      public java.util.List<net.freeback.entries.FBSystemProto.FBDimension> getDimensionsList() {
        return java.util.Collections.unmodifiableList(result.dimensions_);
      }
      public int getDimensionsCount() {
        return result.getDimensionsCount();
      }
      public net.freeback.entries.FBSystemProto.FBDimension getDimensions(int index) {
        return result.getDimensions(index);
      }
      public Builder setDimensions(int index, net.freeback.entries.FBSystemProto.FBDimension value) {
        if (value == null) {
          throw new NullPointerException();
        }
        result.dimensions_.set(index, value);
        return this;
      }
      public Builder setDimensions(int index, net.freeback.entries.FBSystemProto.FBDimension.Builder builderForValue) {
        result.dimensions_.set(index, builderForValue.build());
        return this;
      }
      public Builder addDimensions(net.freeback.entries.FBSystemProto.FBDimension value) {
        if (value == null) {
          throw new NullPointerException();
        }
        if (result.dimensions_.isEmpty()) {
          result.dimensions_ = new java.util.ArrayList<net.freeback.entries.FBSystemProto.FBDimension>();
        }
        result.dimensions_.add(value);
        return this;
      }
      public Builder addDimensions(net.freeback.entries.FBSystemProto.FBDimension.Builder builderForValue) {
        if (result.dimensions_.isEmpty()) {
          result.dimensions_ = new java.util.ArrayList<net.freeback.entries.FBSystemProto.FBDimension>();
        }
        result.dimensions_.add(builderForValue.build());
        return this;
      }
      public Builder addAllDimensions(
          java.lang.Iterable<? extends net.freeback.entries.FBSystemProto.FBDimension> values) {
        if (result.dimensions_.isEmpty()) {
          result.dimensions_ = new java.util.ArrayList<net.freeback.entries.FBSystemProto.FBDimension>();
        }
        super.addAll(values, result.dimensions_);
        return this;
      }
      public Builder clearDimensions() {
        result.dimensions_ = java.util.Collections.emptyList();
        return this;
      }
    }
    
    static {
      net.freeback.entries.FBSystemProto.getDescriptor();
    }
    
    static {
      net.freeback.entries.FBSystemProto.internalForceInit();
    }
  }
  
  public static final class FBIndustry extends
      com.google.protobuf.GeneratedMessage {
    // Use FBIndustry.newBuilder() to construct.
    private FBIndustry() {}
    
    private static final FBIndustry defaultInstance = new FBIndustry();
    public static FBIndustry getDefaultInstance() {
      return defaultInstance;
    }
    
    public FBIndustry getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return net.freeback.entries.FBSystemProto.internal_static_net_freeback_FBIndustry_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return net.freeback.entries.FBSystemProto.internal_static_net_freeback_FBIndustry_fieldAccessorTable;
    }
    
    // required int32 Code = 1;
    public static final int CODE_FIELD_NUMBER = 1;
    private boolean hasCode;
    private int code_ = 0;
    public boolean hasCode() { return hasCode; }
    public int getCode() { return code_; }
    
    // required string Name = 2;
    public static final int NAME_FIELD_NUMBER = 2;
    private boolean hasName;
    private java.lang.String name_ = "";
    public boolean hasName() { return hasName; }
    public java.lang.String getName() { return name_; }
    
    public final boolean isInitialized() {
      if (!hasCode) return false;
      if (!hasName) return false;
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (hasCode()) {
        output.writeInt32(1, getCode());
      }
      if (hasName()) {
        output.writeString(2, getName());
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      if (hasCode()) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, getCode());
      }
      if (hasName()) {
        size += com.google.protobuf.CodedOutputStream
          .computeStringSize(2, getName());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    public static net.freeback.entries.FBSystemProto.FBIndustry parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static net.freeback.entries.FBSystemProto.FBIndustry parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static net.freeback.entries.FBSystemProto.FBIndustry parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static net.freeback.entries.FBSystemProto.FBIndustry parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static net.freeback.entries.FBSystemProto.FBIndustry parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static net.freeback.entries.FBSystemProto.FBIndustry parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static net.freeback.entries.FBSystemProto.FBIndustry parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeDelimitedFrom(input).buildParsed();
    }
    public static net.freeback.entries.FBSystemProto.FBIndustry parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeDelimitedFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static net.freeback.entries.FBSystemProto.FBIndustry parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static net.freeback.entries.FBSystemProto.FBIndustry parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(net.freeback.entries.FBSystemProto.FBIndustry prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> {
      private net.freeback.entries.FBSystemProto.FBIndustry result;
      
      // Construct using net.freeback.entries.FBSystemProto.FBIndustry.newBuilder()
      private Builder() {}
      
      private static Builder create() {
        Builder builder = new Builder();
        builder.result = new net.freeback.entries.FBSystemProto.FBIndustry();
        return builder;
      }
      
      protected net.freeback.entries.FBSystemProto.FBIndustry internalGetResult() {
        return result;
      }
      
      public Builder clear() {
        if (result == null) {
          throw new IllegalStateException(
            "Cannot call clear() after build().");
        }
        result = new net.freeback.entries.FBSystemProto.FBIndustry();
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(result);
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return net.freeback.entries.FBSystemProto.FBIndustry.getDescriptor();
      }
      
      public net.freeback.entries.FBSystemProto.FBIndustry getDefaultInstanceForType() {
        return net.freeback.entries.FBSystemProto.FBIndustry.getDefaultInstance();
      }
      
      public boolean isInitialized() {
        return result.isInitialized();
      }
      public net.freeback.entries.FBSystemProto.FBIndustry build() {
        if (result != null && !isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return buildPartial();
      }
      
      private net.freeback.entries.FBSystemProto.FBIndustry buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        if (!isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return buildPartial();
      }
      
      public net.freeback.entries.FBSystemProto.FBIndustry buildPartial() {
        if (result == null) {
          throw new IllegalStateException(
            "build() has already been called on this Builder.");
        }
        net.freeback.entries.FBSystemProto.FBIndustry returnMe = result;
        result = null;
        return returnMe;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof net.freeback.entries.FBSystemProto.FBIndustry) {
          return mergeFrom((net.freeback.entries.FBSystemProto.FBIndustry)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(net.freeback.entries.FBSystemProto.FBIndustry other) {
        if (other == net.freeback.entries.FBSystemProto.FBIndustry.getDefaultInstance()) return this;
        if (other.hasCode()) {
          setCode(other.getCode());
        }
        if (other.hasName()) {
          setName(other.getName());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                return this;
              }
              break;
            }
            case 8: {
              setCode(input.readInt32());
              break;
            }
            case 18: {
              setName(input.readString());
              break;
            }
          }
        }
      }
      
      
      // required int32 Code = 1;
      public boolean hasCode() {
        return result.hasCode();
      }
      public int getCode() {
        return result.getCode();
      }
      public Builder setCode(int value) {
        result.hasCode = true;
        result.code_ = value;
        return this;
      }
      public Builder clearCode() {
        result.hasCode = false;
        result.code_ = 0;
        return this;
      }
      
      // required string Name = 2;
      public boolean hasName() {
        return result.hasName();
      }
      public java.lang.String getName() {
        return result.getName();
      }
      public Builder setName(java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  result.hasName = true;
        result.name_ = value;
        return this;
      }
      public Builder clearName() {
        result.hasName = false;
        result.name_ = getDefaultInstance().getName();
        return this;
      }
    }
    
    static {
      net.freeback.entries.FBSystemProto.getDescriptor();
    }
    
    static {
      net.freeback.entries.FBSystemProto.internalForceInit();
    }
  }
  
  public static final class FBCategory extends
      com.google.protobuf.GeneratedMessage {
    // Use FBCategory.newBuilder() to construct.
    private FBCategory() {}
    
    private static final FBCategory defaultInstance = new FBCategory();
    public static FBCategory getDefaultInstance() {
      return defaultInstance;
    }
    
    public FBCategory getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return net.freeback.entries.FBSystemProto.internal_static_net_freeback_FBCategory_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return net.freeback.entries.FBSystemProto.internal_static_net_freeback_FBCategory_fieldAccessorTable;
    }
    
    // required int32 Code = 1;
    public static final int CODE_FIELD_NUMBER = 1;
    private boolean hasCode;
    private int code_ = 0;
    public boolean hasCode() { return hasCode; }
    public int getCode() { return code_; }
    
    // required int32 Order = 2;
    public static final int ORDER_FIELD_NUMBER = 2;
    private boolean hasOrder;
    private int order_ = 0;
    public boolean hasOrder() { return hasOrder; }
    public int getOrder() { return order_; }
    
    // required string Name = 3;
    public static final int NAME_FIELD_NUMBER = 3;
    private boolean hasName;
    private java.lang.String name_ = "";
    public boolean hasName() { return hasName; }
    public java.lang.String getName() { return name_; }
    
    // required int32 State = 4;
    public static final int STATE_FIELD_NUMBER = 4;
    private boolean hasState;
    private int state_ = 0;
    public boolean hasState() { return hasState; }
    public int getState() { return state_; }
    
    public final boolean isInitialized() {
      if (!hasCode) return false;
      if (!hasOrder) return false;
      if (!hasName) return false;
      if (!hasState) return false;
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (hasCode()) {
        output.writeInt32(1, getCode());
      }
      if (hasOrder()) {
        output.writeInt32(2, getOrder());
      }
      if (hasName()) {
        output.writeString(3, getName());
      }
      if (hasState()) {
        output.writeInt32(4, getState());
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      if (hasCode()) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, getCode());
      }
      if (hasOrder()) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, getOrder());
      }
      if (hasName()) {
        size += com.google.protobuf.CodedOutputStream
          .computeStringSize(3, getName());
      }
      if (hasState()) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(4, getState());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    public static net.freeback.entries.FBSystemProto.FBCategory parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static net.freeback.entries.FBSystemProto.FBCategory parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static net.freeback.entries.FBSystemProto.FBCategory parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static net.freeback.entries.FBSystemProto.FBCategory parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static net.freeback.entries.FBSystemProto.FBCategory parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static net.freeback.entries.FBSystemProto.FBCategory parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static net.freeback.entries.FBSystemProto.FBCategory parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeDelimitedFrom(input).buildParsed();
    }
    public static net.freeback.entries.FBSystemProto.FBCategory parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeDelimitedFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static net.freeback.entries.FBSystemProto.FBCategory parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static net.freeback.entries.FBSystemProto.FBCategory parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(net.freeback.entries.FBSystemProto.FBCategory prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> {
      private net.freeback.entries.FBSystemProto.FBCategory result;
      
      // Construct using net.freeback.entries.FBSystemProto.FBCategory.newBuilder()
      private Builder() {}
      
      private static Builder create() {
        Builder builder = new Builder();
        builder.result = new net.freeback.entries.FBSystemProto.FBCategory();
        return builder;
      }
      
      protected net.freeback.entries.FBSystemProto.FBCategory internalGetResult() {
        return result;
      }
      
      public Builder clear() {
        if (result == null) {
          throw new IllegalStateException(
            "Cannot call clear() after build().");
        }
        result = new net.freeback.entries.FBSystemProto.FBCategory();
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(result);
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return net.freeback.entries.FBSystemProto.FBCategory.getDescriptor();
      }
      
      public net.freeback.entries.FBSystemProto.FBCategory getDefaultInstanceForType() {
        return net.freeback.entries.FBSystemProto.FBCategory.getDefaultInstance();
      }
      
      public boolean isInitialized() {
        return result.isInitialized();
      }
      public net.freeback.entries.FBSystemProto.FBCategory build() {
        if (result != null && !isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return buildPartial();
      }
      
      private net.freeback.entries.FBSystemProto.FBCategory buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        if (!isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return buildPartial();
      }
      
      public net.freeback.entries.FBSystemProto.FBCategory buildPartial() {
        if (result == null) {
          throw new IllegalStateException(
            "build() has already been called on this Builder.");
        }
        net.freeback.entries.FBSystemProto.FBCategory returnMe = result;
        result = null;
        return returnMe;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof net.freeback.entries.FBSystemProto.FBCategory) {
          return mergeFrom((net.freeback.entries.FBSystemProto.FBCategory)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(net.freeback.entries.FBSystemProto.FBCategory other) {
        if (other == net.freeback.entries.FBSystemProto.FBCategory.getDefaultInstance()) return this;
        if (other.hasCode()) {
          setCode(other.getCode());
        }
        if (other.hasOrder()) {
          setOrder(other.getOrder());
        }
        if (other.hasName()) {
          setName(other.getName());
        }
        if (other.hasState()) {
          setState(other.getState());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                return this;
              }
              break;
            }
            case 8: {
              setCode(input.readInt32());
              break;
            }
            case 16: {
              setOrder(input.readInt32());
              break;
            }
            case 26: {
              setName(input.readString());
              break;
            }
            case 32: {
              setState(input.readInt32());
              break;
            }
          }
        }
      }
      
      
      // required int32 Code = 1;
      public boolean hasCode() {
        return result.hasCode();
      }
      public int getCode() {
        return result.getCode();
      }
      public Builder setCode(int value) {
        result.hasCode = true;
        result.code_ = value;
        return this;
      }
      public Builder clearCode() {
        result.hasCode = false;
        result.code_ = 0;
        return this;
      }
      
      // required int32 Order = 2;
      public boolean hasOrder() {
        return result.hasOrder();
      }
      public int getOrder() {
        return result.getOrder();
      }
      public Builder setOrder(int value) {
        result.hasOrder = true;
        result.order_ = value;
        return this;
      }
      public Builder clearOrder() {
        result.hasOrder = false;
        result.order_ = 0;
        return this;
      }
      
      // required string Name = 3;
      public boolean hasName() {
        return result.hasName();
      }
      public java.lang.String getName() {
        return result.getName();
      }
      public Builder setName(java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  result.hasName = true;
        result.name_ = value;
        return this;
      }
      public Builder clearName() {
        result.hasName = false;
        result.name_ = getDefaultInstance().getName();
        return this;
      }
      
      // required int32 State = 4;
      public boolean hasState() {
        return result.hasState();
      }
      public int getState() {
        return result.getState();
      }
      public Builder setState(int value) {
        result.hasState = true;
        result.state_ = value;
        return this;
      }
      public Builder clearState() {
        result.hasState = false;
        result.state_ = 0;
        return this;
      }
    }
    
    static {
      net.freeback.entries.FBSystemProto.getDescriptor();
    }
    
    static {
      net.freeback.entries.FBSystemProto.internalForceInit();
    }
  }
  
  public static final class FBDimension extends
      com.google.protobuf.GeneratedMessage {
    // Use FBDimension.newBuilder() to construct.
    private FBDimension() {}
    
    private static final FBDimension defaultInstance = new FBDimension();
    public static FBDimension getDefaultInstance() {
      return defaultInstance;
    }
    
    public FBDimension getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return net.freeback.entries.FBSystemProto.internal_static_net_freeback_FBDimension_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return net.freeback.entries.FBSystemProto.internal_static_net_freeback_FBDimension_fieldAccessorTable;
    }
    
    // required string Group = 1;
    public static final int GROUP_FIELD_NUMBER = 1;
    private boolean hasGroup;
    private java.lang.String group_ = "";
    public boolean hasGroup() { return hasGroup; }
    public java.lang.String getGroup() { return group_; }
    
    // repeated string Dimension = 2;
    public static final int DIMENSION_FIELD_NUMBER = 2;
    private java.util.List<java.lang.String> dimension_ =
      java.util.Collections.emptyList();
    public java.util.List<java.lang.String> getDimensionList() {
      return dimension_;
    }
    public int getDimensionCount() { return dimension_.size(); }
    public java.lang.String getDimension(int index) {
      return dimension_.get(index);
    }
    
    public final boolean isInitialized() {
      if (!hasGroup) return false;
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (hasGroup()) {
        output.writeString(1, getGroup());
      }
      for (java.lang.String element : getDimensionList()) {
        output.writeString(2, element);
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      if (hasGroup()) {
        size += com.google.protobuf.CodedOutputStream
          .computeStringSize(1, getGroup());
      }
      {
        int dataSize = 0;
        for (java.lang.String element : getDimensionList()) {
          dataSize += com.google.protobuf.CodedOutputStream
            .computeStringSizeNoTag(element);
        }
        size += dataSize;
        size += 1 * getDimensionList().size();
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    public static net.freeback.entries.FBSystemProto.FBDimension parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static net.freeback.entries.FBSystemProto.FBDimension parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static net.freeback.entries.FBSystemProto.FBDimension parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static net.freeback.entries.FBSystemProto.FBDimension parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static net.freeback.entries.FBSystemProto.FBDimension parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static net.freeback.entries.FBSystemProto.FBDimension parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static net.freeback.entries.FBSystemProto.FBDimension parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeDelimitedFrom(input).buildParsed();
    }
    public static net.freeback.entries.FBSystemProto.FBDimension parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeDelimitedFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static net.freeback.entries.FBSystemProto.FBDimension parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static net.freeback.entries.FBSystemProto.FBDimension parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(net.freeback.entries.FBSystemProto.FBDimension prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> {
      private net.freeback.entries.FBSystemProto.FBDimension result;
      
      // Construct using net.freeback.entries.FBSystemProto.FBDimension.newBuilder()
      private Builder() {}
      
      private static Builder create() {
        Builder builder = new Builder();
        builder.result = new net.freeback.entries.FBSystemProto.FBDimension();
        return builder;
      }
      
      protected net.freeback.entries.FBSystemProto.FBDimension internalGetResult() {
        return result;
      }
      
      public Builder clear() {
        if (result == null) {
          throw new IllegalStateException(
            "Cannot call clear() after build().");
        }
        result = new net.freeback.entries.FBSystemProto.FBDimension();
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(result);
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return net.freeback.entries.FBSystemProto.FBDimension.getDescriptor();
      }
      
      public net.freeback.entries.FBSystemProto.FBDimension getDefaultInstanceForType() {
        return net.freeback.entries.FBSystemProto.FBDimension.getDefaultInstance();
      }
      
      public boolean isInitialized() {
        return result.isInitialized();
      }
      public net.freeback.entries.FBSystemProto.FBDimension build() {
        if (result != null && !isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return buildPartial();
      }
      
      private net.freeback.entries.FBSystemProto.FBDimension buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        if (!isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return buildPartial();
      }
      
      public net.freeback.entries.FBSystemProto.FBDimension buildPartial() {
        if (result == null) {
          throw new IllegalStateException(
            "build() has already been called on this Builder.");
        }
        if (result.dimension_ != java.util.Collections.EMPTY_LIST) {
          result.dimension_ =
            java.util.Collections.unmodifiableList(result.dimension_);
        }
        net.freeback.entries.FBSystemProto.FBDimension returnMe = result;
        result = null;
        return returnMe;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof net.freeback.entries.FBSystemProto.FBDimension) {
          return mergeFrom((net.freeback.entries.FBSystemProto.FBDimension)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(net.freeback.entries.FBSystemProto.FBDimension other) {
        if (other == net.freeback.entries.FBSystemProto.FBDimension.getDefaultInstance()) return this;
        if (other.hasGroup()) {
          setGroup(other.getGroup());
        }
        if (!other.dimension_.isEmpty()) {
          if (result.dimension_.isEmpty()) {
            result.dimension_ = new java.util.ArrayList<java.lang.String>();
          }
          result.dimension_.addAll(other.dimension_);
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                return this;
              }
              break;
            }
            case 10: {
              setGroup(input.readString());
              break;
            }
            case 18: {
              addDimension(input.readString());
              break;
            }
          }
        }
      }
      
      
      // required string Group = 1;
      public boolean hasGroup() {
        return result.hasGroup();
      }
      public java.lang.String getGroup() {
        return result.getGroup();
      }
      public Builder setGroup(java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  result.hasGroup = true;
        result.group_ = value;
        return this;
      }
      public Builder clearGroup() {
        result.hasGroup = false;
        result.group_ = getDefaultInstance().getGroup();
        return this;
      }
      
      // repeated string Dimension = 2;
      public java.util.List<java.lang.String> getDimensionList() {
        return java.util.Collections.unmodifiableList(result.dimension_);
      }
      public int getDimensionCount() {
        return result.getDimensionCount();
      }
      public java.lang.String getDimension(int index) {
        return result.getDimension(index);
      }
      public Builder setDimension(int index, java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  result.dimension_.set(index, value);
        return this;
      }
      public Builder addDimension(java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  if (result.dimension_.isEmpty()) {
          result.dimension_ = new java.util.ArrayList<java.lang.String>();
        }
        result.dimension_.add(value);
        return this;
      }
      public Builder addAllDimension(
          java.lang.Iterable<? extends java.lang.String> values) {
        if (result.dimension_.isEmpty()) {
          result.dimension_ = new java.util.ArrayList<java.lang.String>();
        }
        super.addAll(values, result.dimension_);
        return this;
      }
      public Builder clearDimension() {
        result.dimension_ = java.util.Collections.emptyList();
        return this;
      }
    }
    
    static {
      net.freeback.entries.FBSystemProto.getDescriptor();
    }
    
    static {
      net.freeback.entries.FBSystemProto.internalForceInit();
    }
  }
  
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_net_freeback_FBSystem_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_net_freeback_FBSystem_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_net_freeback_FBIndustry_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_net_freeback_FBIndustry_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_net_freeback_FBCategory_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_net_freeback_FBCategory_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_net_freeback_FBDimension_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_net_freeback_FBDimension_fieldAccessorTable;
  
  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\016FBSystem.proto\022\014net.freeback\032\016FBRegion" +
      ".proto\"\323\001\n\010FBSystem\022\024\n\014VersionValue\030\001 \002(" +
      "\005\022&\n\006Region\030\002 \002(\0132\026.net.freeback.FBRegio" +
      "n\022,\n\nIndustires\030\004 \003(\0132\030.net.freeback.FBI" +
      "ndustry\022,\n\nCategories\030\005 \003(\0132\030.net.freeba" +
      "ck.FBCategory\022-\n\nDimensions\030\006 \003(\0132\031.net." +
      "freeback.FBDimension\"(\n\nFBIndustry\022\014\n\004Co" +
      "de\030\001 \002(\005\022\014\n\004Name\030\002 \002(\t\"F\n\nFBCategory\022\014\n\004" +
      "Code\030\001 \002(\005\022\r\n\005Order\030\002 \002(\005\022\014\n\004Name\030\003 \002(\t\022" +
      "\r\n\005State\030\004 \002(\005\"/\n\013FBDimension\022\r\n\005Group\030\001",
      " \002(\t\022\021\n\tDimension\030\002 \003(\tB%\n\024net.freeback." +
      "entriesB\rFBSystemProto"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_net_freeback_FBSystem_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_net_freeback_FBSystem_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_net_freeback_FBSystem_descriptor,
              new java.lang.String[] { "VersionValue", "Region", "Industires", "Categories", "Dimensions", },
              net.freeback.entries.FBSystemProto.FBSystem.class,
              net.freeback.entries.FBSystemProto.FBSystem.Builder.class);
          internal_static_net_freeback_FBIndustry_descriptor =
            getDescriptor().getMessageTypes().get(1);
          internal_static_net_freeback_FBIndustry_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_net_freeback_FBIndustry_descriptor,
              new java.lang.String[] { "Code", "Name", },
              net.freeback.entries.FBSystemProto.FBIndustry.class,
              net.freeback.entries.FBSystemProto.FBIndustry.Builder.class);
          internal_static_net_freeback_FBCategory_descriptor =
            getDescriptor().getMessageTypes().get(2);
          internal_static_net_freeback_FBCategory_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_net_freeback_FBCategory_descriptor,
              new java.lang.String[] { "Code", "Order", "Name", "State", },
              net.freeback.entries.FBSystemProto.FBCategory.class,
              net.freeback.entries.FBSystemProto.FBCategory.Builder.class);
          internal_static_net_freeback_FBDimension_descriptor =
            getDescriptor().getMessageTypes().get(3);
          internal_static_net_freeback_FBDimension_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_net_freeback_FBDimension_descriptor,
              new java.lang.String[] { "Group", "Dimension", },
              net.freeback.entries.FBSystemProto.FBDimension.class,
              net.freeback.entries.FBSystemProto.FBDimension.Builder.class);
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          net.freeback.entries.FBRegionProto.getDescriptor(),
        }, assigner);
  }
  
  public static void internalForceInit() {}
}
