// Generated by the protocol buffer compiler.  DO NOT EDIT!

package net.freeback.entries.store;

public final class FBOrderProto {
  private FBOrderProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public enum OrderState
      implements com.google.protobuf.ProtocolMessageEnum {
    Making(0, 1),
    OnRoute(1, 2),
    Finished(2, 3),
    ;
    
    
    public final int getNumber() { return value; }
    
    public static OrderState valueOf(int value) {
      switch (value) {
        case 1: return Making;
        case 2: return OnRoute;
        case 3: return Finished;
        default: return null;
      }
    }
    
    public static com.google.protobuf.Internal.EnumLiteMap<OrderState>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static com.google.protobuf.Internal.EnumLiteMap<OrderState>
        internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<OrderState>() {
            public OrderState findValueByNumber(int number) {
              return OrderState.valueOf(number)
    ;        }
          };
    
    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      return getDescriptor().getValues().get(index);
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return net.freeback.entries.store.FBOrderProto.getDescriptor().getEnumTypes().get(0);
    }
    
    private static final OrderState[] VALUES = {
      Making, OnRoute, Finished, 
    };
    public static OrderState valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      return VALUES[desc.getIndex()];
    }
    private final int index;
    private final int value;
    private OrderState(int index, int value) {
      this.index = index;
      this.value = value;
    }
    
    static {
      net.freeback.entries.store.FBOrderProto.getDescriptor();
    }
  }
  
  public enum Delivery
      implements com.google.protobuf.ProtocolMessageEnum {
    Self(0, 1),
    Home(1, 2),
    ;
    
    
    public final int getNumber() { return value; }
    
    public static Delivery valueOf(int value) {
      switch (value) {
        case 1: return Self;
        case 2: return Home;
        default: return null;
      }
    }
    
    public static com.google.protobuf.Internal.EnumLiteMap<Delivery>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static com.google.protobuf.Internal.EnumLiteMap<Delivery>
        internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<Delivery>() {
            public Delivery findValueByNumber(int number) {
              return Delivery.valueOf(number)
    ;        }
          };
    
    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      return getDescriptor().getValues().get(index);
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return net.freeback.entries.store.FBOrderProto.getDescriptor().getEnumTypes().get(1);
    }
    
    private static final Delivery[] VALUES = {
      Self, Home, 
    };
    public static Delivery valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      return VALUES[desc.getIndex()];
    }
    private final int index;
    private final int value;
    private Delivery(int index, int value) {
      this.index = index;
      this.value = value;
    }
    
    static {
      net.freeback.entries.store.FBOrderProto.getDescriptor();
    }
  }
  
  public static final class FBOrder extends
      com.google.protobuf.GeneratedMessage {
    // Use FBOrder.newBuilder() to construct.
    private FBOrder() {}
    
    private static final FBOrder defaultInstance = new FBOrder();
    public static FBOrder getDefaultInstance() {
      return defaultInstance;
    }
    
    public FBOrder getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return net.freeback.entries.store.FBOrderProto.internal_static_net_freeback_FBOrder_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return net.freeback.entries.store.FBOrderProto.internal_static_net_freeback_FBOrder_fieldAccessorTable;
    }
    
    // required string Code = 1;
    public static final int CODE_FIELD_NUMBER = 1;
    private boolean hasCode;
    private java.lang.String code_ = "";
    public boolean hasCode() { return hasCode; }
    public java.lang.String getCode() { return code_; }
    
    // required string Store = 2;
    public static final int STORE_FIELD_NUMBER = 2;
    private boolean hasStore;
    private java.lang.String store_ = "";
    public boolean hasStore() { return hasStore; }
    public java.lang.String getStore() { return store_; }
    
    // required string User = 3;
    public static final int USER_FIELD_NUMBER = 3;
    private boolean hasUser;
    private java.lang.String user_ = "";
    public boolean hasUser() { return hasUser; }
    public java.lang.String getUser() { return user_; }
    
    // required float Adjust = 5;
    public static final int ADJUST_FIELD_NUMBER = 5;
    private boolean hasAdjust;
    private float adjust_ = 0F;
    public boolean hasAdjust() { return hasAdjust; }
    public float getAdjust() { return adjust_; }
    
    // required .net.freeback.OrderState State = 8;
    public static final int STATE_FIELD_NUMBER = 8;
    private boolean hasState;
    private net.freeback.entries.store.FBOrderProto.OrderState state_ = net.freeback.entries.store.FBOrderProto.OrderState.Making;
    public boolean hasState() { return hasState; }
    public net.freeback.entries.store.FBOrderProto.OrderState getState() { return state_; }
    
    // repeated .net.freeback.FBOrderItem Items = 11;
    public static final int ITEMS_FIELD_NUMBER = 11;
    private java.util.List<net.freeback.entries.store.FBOrderProto.FBOrderItem> items_ =
      java.util.Collections.emptyList();
    public java.util.List<net.freeback.entries.store.FBOrderProto.FBOrderItem> getItemsList() {
      return items_;
    }
    public int getItemsCount() { return items_.size(); }
    public net.freeback.entries.store.FBOrderProto.FBOrderItem getItems(int index) {
      return items_.get(index);
    }
    
    // required string Address = 12;
    public static final int ADDRESS_FIELD_NUMBER = 12;
    private boolean hasAddress;
    private java.lang.String address_ = "";
    public boolean hasAddress() { return hasAddress; }
    public java.lang.String getAddress() { return address_; }
    
    // optional string Remark = 14;
    public static final int REMARK_FIELD_NUMBER = 14;
    private boolean hasRemark;
    private java.lang.String remark_ = "";
    public boolean hasRemark() { return hasRemark; }
    public java.lang.String getRemark() { return remark_; }
    
    // required string LastModified = 13;
    public static final int LASTMODIFIED_FIELD_NUMBER = 13;
    private boolean hasLastModified;
    private java.lang.String lastModified_ = "";
    public boolean hasLastModified() { return hasLastModified; }
    public java.lang.String getLastModified() { return lastModified_; }
    
    // required .net.freeback.Delivery Dispatch = 15;
    public static final int DISPATCH_FIELD_NUMBER = 15;
    private boolean hasDispatch;
    private net.freeback.entries.store.FBOrderProto.Delivery dispatch_ = net.freeback.entries.store.FBOrderProto.Delivery.Self;
    public boolean hasDispatch() { return hasDispatch; }
    public net.freeback.entries.store.FBOrderProto.Delivery getDispatch() { return dispatch_; }
    
    public final boolean isInitialized() {
      if (!hasCode) return false;
      if (!hasStore) return false;
      if (!hasUser) return false;
      if (!hasAdjust) return false;
      if (!hasState) return false;
      if (!hasAddress) return false;
      if (!hasLastModified) return false;
      if (!hasDispatch) return false;
      for (net.freeback.entries.store.FBOrderProto.FBOrderItem element : getItemsList()) {
        if (!element.isInitialized()) return false;
      }
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (hasCode()) {
        output.writeString(1, getCode());
      }
      if (hasStore()) {
        output.writeString(2, getStore());
      }
      if (hasUser()) {
        output.writeString(3, getUser());
      }
      if (hasAdjust()) {
        output.writeFloat(5, getAdjust());
      }
      if (hasState()) {
        output.writeEnum(8, getState().getNumber());
      }
      for (net.freeback.entries.store.FBOrderProto.FBOrderItem element : getItemsList()) {
        output.writeMessage(11, element);
      }
      if (hasAddress()) {
        output.writeString(12, getAddress());
      }
      if (hasLastModified()) {
        output.writeString(13, getLastModified());
      }
      if (hasRemark()) {
        output.writeString(14, getRemark());
      }
      if (hasDispatch()) {
        output.writeEnum(15, getDispatch().getNumber());
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      if (hasCode()) {
        size += com.google.protobuf.CodedOutputStream
          .computeStringSize(1, getCode());
      }
      if (hasStore()) {
        size += com.google.protobuf.CodedOutputStream
          .computeStringSize(2, getStore());
      }
      if (hasUser()) {
        size += com.google.protobuf.CodedOutputStream
          .computeStringSize(3, getUser());
      }
      if (hasAdjust()) {
        size += com.google.protobuf.CodedOutputStream
          .computeFloatSize(5, getAdjust());
      }
      if (hasState()) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(8, getState().getNumber());
      }
      for (net.freeback.entries.store.FBOrderProto.FBOrderItem element : getItemsList()) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(11, element);
      }
      if (hasAddress()) {
        size += com.google.protobuf.CodedOutputStream
          .computeStringSize(12, getAddress());
      }
      if (hasLastModified()) {
        size += com.google.protobuf.CodedOutputStream
          .computeStringSize(13, getLastModified());
      }
      if (hasRemark()) {
        size += com.google.protobuf.CodedOutputStream
          .computeStringSize(14, getRemark());
      }
      if (hasDispatch()) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(15, getDispatch().getNumber());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    public static net.freeback.entries.store.FBOrderProto.FBOrder parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static net.freeback.entries.store.FBOrderProto.FBOrder parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static net.freeback.entries.store.FBOrderProto.FBOrder parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static net.freeback.entries.store.FBOrderProto.FBOrder parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static net.freeback.entries.store.FBOrderProto.FBOrder parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static net.freeback.entries.store.FBOrderProto.FBOrder parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static net.freeback.entries.store.FBOrderProto.FBOrder parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeDelimitedFrom(input).buildParsed();
    }
    public static net.freeback.entries.store.FBOrderProto.FBOrder parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeDelimitedFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static net.freeback.entries.store.FBOrderProto.FBOrder parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static net.freeback.entries.store.FBOrderProto.FBOrder parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(net.freeback.entries.store.FBOrderProto.FBOrder prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> {
      private net.freeback.entries.store.FBOrderProto.FBOrder result;
      
      // Construct using net.freeback.entries.store.FBOrderProto.FBOrder.newBuilder()
      private Builder() {}
      
      private static Builder create() {
        Builder builder = new Builder();
        builder.result = new net.freeback.entries.store.FBOrderProto.FBOrder();
        return builder;
      }
      
      protected net.freeback.entries.store.FBOrderProto.FBOrder internalGetResult() {
        return result;
      }
      
      public Builder clear() {
        if (result == null) {
          throw new IllegalStateException(
            "Cannot call clear() after build().");
        }
        result = new net.freeback.entries.store.FBOrderProto.FBOrder();
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(result);
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return net.freeback.entries.store.FBOrderProto.FBOrder.getDescriptor();
      }
      
      public net.freeback.entries.store.FBOrderProto.FBOrder getDefaultInstanceForType() {
        return net.freeback.entries.store.FBOrderProto.FBOrder.getDefaultInstance();
      }
      
      public boolean isInitialized() {
        return result.isInitialized();
      }
      public net.freeback.entries.store.FBOrderProto.FBOrder build() {
        if (result != null && !isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return buildPartial();
      }
      
      private net.freeback.entries.store.FBOrderProto.FBOrder buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        if (!isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return buildPartial();
      }
      
      public net.freeback.entries.store.FBOrderProto.FBOrder buildPartial() {
        if (result == null) {
          throw new IllegalStateException(
            "build() has already been called on this Builder.");
        }
        if (result.items_ != java.util.Collections.EMPTY_LIST) {
          result.items_ =
            java.util.Collections.unmodifiableList(result.items_);
        }
        net.freeback.entries.store.FBOrderProto.FBOrder returnMe = result;
        result = null;
        return returnMe;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof net.freeback.entries.store.FBOrderProto.FBOrder) {
          return mergeFrom((net.freeback.entries.store.FBOrderProto.FBOrder)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(net.freeback.entries.store.FBOrderProto.FBOrder other) {
        if (other == net.freeback.entries.store.FBOrderProto.FBOrder.getDefaultInstance()) return this;
        if (other.hasCode()) {
          setCode(other.getCode());
        }
        if (other.hasStore()) {
          setStore(other.getStore());
        }
        if (other.hasUser()) {
          setUser(other.getUser());
        }
        if (other.hasAdjust()) {
          setAdjust(other.getAdjust());
        }
        if (other.hasState()) {
          setState(other.getState());
        }
        if (!other.items_.isEmpty()) {
          if (result.items_.isEmpty()) {
            result.items_ = new java.util.ArrayList<net.freeback.entries.store.FBOrderProto.FBOrderItem>();
          }
          result.items_.addAll(other.items_);
        }
        if (other.hasAddress()) {
          setAddress(other.getAddress());
        }
        if (other.hasRemark()) {
          setRemark(other.getRemark());
        }
        if (other.hasLastModified()) {
          setLastModified(other.getLastModified());
        }
        if (other.hasDispatch()) {
          setDispatch(other.getDispatch());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                return this;
              }
              break;
            }
            case 10: {
              setCode(input.readString());
              break;
            }
            case 18: {
              setStore(input.readString());
              break;
            }
            case 26: {
              setUser(input.readString());
              break;
            }
            case 45: {
              setAdjust(input.readFloat());
              break;
            }
            case 64: {
              int rawValue = input.readEnum();
              net.freeback.entries.store.FBOrderProto.OrderState value = net.freeback.entries.store.FBOrderProto.OrderState.valueOf(rawValue);
              if (value == null) {
                unknownFields.mergeVarintField(8, rawValue);
              } else {
                setState(value);
              }
              break;
            }
            case 90: {
              net.freeback.entries.store.FBOrderProto.FBOrderItem.Builder subBuilder = net.freeback.entries.store.FBOrderProto.FBOrderItem.newBuilder();
              input.readMessage(subBuilder, extensionRegistry);
              addItems(subBuilder.buildPartial());
              break;
            }
            case 98: {
              setAddress(input.readString());
              break;
            }
            case 106: {
              setLastModified(input.readString());
              break;
            }
            case 114: {
              setRemark(input.readString());
              break;
            }
            case 120: {
              int rawValue = input.readEnum();
              net.freeback.entries.store.FBOrderProto.Delivery value = net.freeback.entries.store.FBOrderProto.Delivery.valueOf(rawValue);
              if (value == null) {
                unknownFields.mergeVarintField(15, rawValue);
              } else {
                setDispatch(value);
              }
              break;
            }
          }
        }
      }
      
      
      // required string Code = 1;
      public boolean hasCode() {
        return result.hasCode();
      }
      public java.lang.String getCode() {
        return result.getCode();
      }
      public Builder setCode(java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  result.hasCode = true;
        result.code_ = value;
        return this;
      }
      public Builder clearCode() {
        result.hasCode = false;
        result.code_ = getDefaultInstance().getCode();
        return this;
      }
      
      // required string Store = 2;
      public boolean hasStore() {
        return result.hasStore();
      }
      public java.lang.String getStore() {
        return result.getStore();
      }
      public Builder setStore(java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  result.hasStore = true;
        result.store_ = value;
        return this;
      }
      public Builder clearStore() {
        result.hasStore = false;
        result.store_ = getDefaultInstance().getStore();
        return this;
      }
      
      // required string User = 3;
      public boolean hasUser() {
        return result.hasUser();
      }
      public java.lang.String getUser() {
        return result.getUser();
      }
      public Builder setUser(java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  result.hasUser = true;
        result.user_ = value;
        return this;
      }
      public Builder clearUser() {
        result.hasUser = false;
        result.user_ = getDefaultInstance().getUser();
        return this;
      }
      
      // required float Adjust = 5;
      public boolean hasAdjust() {
        return result.hasAdjust();
      }
      public float getAdjust() {
        return result.getAdjust();
      }
      public Builder setAdjust(float value) {
        result.hasAdjust = true;
        result.adjust_ = value;
        return this;
      }
      public Builder clearAdjust() {
        result.hasAdjust = false;
        result.adjust_ = 0F;
        return this;
      }
      
      // required .net.freeback.OrderState State = 8;
      public boolean hasState() {
        return result.hasState();
      }
      public net.freeback.entries.store.FBOrderProto.OrderState getState() {
        return result.getState();
      }
      public Builder setState(net.freeback.entries.store.FBOrderProto.OrderState value) {
        if (value == null) {
          throw new NullPointerException();
        }
        result.hasState = true;
        result.state_ = value;
        return this;
      }
      public Builder clearState() {
        result.hasState = false;
        result.state_ = net.freeback.entries.store.FBOrderProto.OrderState.Making;
        return this;
      }
      
      // repeated .net.freeback.FBOrderItem Items = 11;
      public java.util.List<net.freeback.entries.store.FBOrderProto.FBOrderItem> getItemsList() {
        return java.util.Collections.unmodifiableList(result.items_);
      }
      public int getItemsCount() {
        return result.getItemsCount();
      }
      public net.freeback.entries.store.FBOrderProto.FBOrderItem getItems(int index) {
        return result.getItems(index);
      }
      public Builder setItems(int index, net.freeback.entries.store.FBOrderProto.FBOrderItem value) {
        if (value == null) {
          throw new NullPointerException();
        }
        result.items_.set(index, value);
        return this;
      }
      public Builder setItems(int index, net.freeback.entries.store.FBOrderProto.FBOrderItem.Builder builderForValue) {
        result.items_.set(index, builderForValue.build());
        return this;
      }
      public Builder addItems(net.freeback.entries.store.FBOrderProto.FBOrderItem value) {
        if (value == null) {
          throw new NullPointerException();
        }
        if (result.items_.isEmpty()) {
          result.items_ = new java.util.ArrayList<net.freeback.entries.store.FBOrderProto.FBOrderItem>();
        }
        result.items_.add(value);
        return this;
      }
      public Builder addItems(net.freeback.entries.store.FBOrderProto.FBOrderItem.Builder builderForValue) {
        if (result.items_.isEmpty()) {
          result.items_ = new java.util.ArrayList<net.freeback.entries.store.FBOrderProto.FBOrderItem>();
        }
        result.items_.add(builderForValue.build());
        return this;
      }
      public Builder addAllItems(
          java.lang.Iterable<? extends net.freeback.entries.store.FBOrderProto.FBOrderItem> values) {
        if (result.items_.isEmpty()) {
          result.items_ = new java.util.ArrayList<net.freeback.entries.store.FBOrderProto.FBOrderItem>();
        }
        super.addAll(values, result.items_);
        return this;
      }
      public Builder clearItems() {
        result.items_ = java.util.Collections.emptyList();
        return this;
      }
      
      // required string Address = 12;
      public boolean hasAddress() {
        return result.hasAddress();
      }
      public java.lang.String getAddress() {
        return result.getAddress();
      }
      public Builder setAddress(java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  result.hasAddress = true;
        result.address_ = value;
        return this;
      }
      public Builder clearAddress() {
        result.hasAddress = false;
        result.address_ = getDefaultInstance().getAddress();
        return this;
      }
      
      // optional string Remark = 14;
      public boolean hasRemark() {
        return result.hasRemark();
      }
      public java.lang.String getRemark() {
        return result.getRemark();
      }
      public Builder setRemark(java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  result.hasRemark = true;
        result.remark_ = value;
        return this;
      }
      public Builder clearRemark() {
        result.hasRemark = false;
        result.remark_ = getDefaultInstance().getRemark();
        return this;
      }
      
      // required string LastModified = 13;
      public boolean hasLastModified() {
        return result.hasLastModified();
      }
      public java.lang.String getLastModified() {
        return result.getLastModified();
      }
      public Builder setLastModified(java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  result.hasLastModified = true;
        result.lastModified_ = value;
        return this;
      }
      public Builder clearLastModified() {
        result.hasLastModified = false;
        result.lastModified_ = getDefaultInstance().getLastModified();
        return this;
      }
      
      // required .net.freeback.Delivery Dispatch = 15;
      public boolean hasDispatch() {
        return result.hasDispatch();
      }
      public net.freeback.entries.store.FBOrderProto.Delivery getDispatch() {
        return result.getDispatch();
      }
      public Builder setDispatch(net.freeback.entries.store.FBOrderProto.Delivery value) {
        if (value == null) {
          throw new NullPointerException();
        }
        result.hasDispatch = true;
        result.dispatch_ = value;
        return this;
      }
      public Builder clearDispatch() {
        result.hasDispatch = false;
        result.dispatch_ = net.freeback.entries.store.FBOrderProto.Delivery.Self;
        return this;
      }
    }
    
    static {
      net.freeback.entries.store.FBOrderProto.getDescriptor();
    }
    
    static {
      net.freeback.entries.store.FBOrderProto.internalForceInit();
    }
  }
  
  public static final class FBOrderItem extends
      com.google.protobuf.GeneratedMessage {
    // Use FBOrderItem.newBuilder() to construct.
    private FBOrderItem() {}
    
    private static final FBOrderItem defaultInstance = new FBOrderItem();
    public static FBOrderItem getDefaultInstance() {
      return defaultInstance;
    }
    
    public FBOrderItem getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return net.freeback.entries.store.FBOrderProto.internal_static_net_freeback_FBOrderItem_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return net.freeback.entries.store.FBOrderProto.internal_static_net_freeback_FBOrderItem_fieldAccessorTable;
    }
    
    // required string Code = 1;
    public static final int CODE_FIELD_NUMBER = 1;
    private boolean hasCode;
    private java.lang.String code_ = "";
    public boolean hasCode() { return hasCode; }
    public java.lang.String getCode() { return code_; }
    
    // required .net.freeback.FBProduct Product = 2;
    public static final int PRODUCT_FIELD_NUMBER = 2;
    private boolean hasProduct;
    private net.freeback.entries.store.FBProductProto.FBProduct product_ = net.freeback.entries.store.FBProductProto.FBProduct.getDefaultInstance();
    public boolean hasProduct() { return hasProduct; }
    public net.freeback.entries.store.FBProductProto.FBProduct getProduct() { return product_; }
    
    // required int32 Amount = 3 [default = 1];
    public static final int AMOUNT_FIELD_NUMBER = 3;
    private boolean hasAmount;
    private int amount_ = 1;
    public boolean hasAmount() { return hasAmount; }
    public int getAmount() { return amount_; }
    
    public final boolean isInitialized() {
      if (!hasCode) return false;
      if (!hasProduct) return false;
      if (!hasAmount) return false;
      if (!getProduct().isInitialized()) return false;
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (hasCode()) {
        output.writeString(1, getCode());
      }
      if (hasProduct()) {
        output.writeMessage(2, getProduct());
      }
      if (hasAmount()) {
        output.writeInt32(3, getAmount());
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      if (hasCode()) {
        size += com.google.protobuf.CodedOutputStream
          .computeStringSize(1, getCode());
      }
      if (hasProduct()) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(2, getProduct());
      }
      if (hasAmount()) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(3, getAmount());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    public static net.freeback.entries.store.FBOrderProto.FBOrderItem parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static net.freeback.entries.store.FBOrderProto.FBOrderItem parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static net.freeback.entries.store.FBOrderProto.FBOrderItem parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static net.freeback.entries.store.FBOrderProto.FBOrderItem parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static net.freeback.entries.store.FBOrderProto.FBOrderItem parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static net.freeback.entries.store.FBOrderProto.FBOrderItem parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static net.freeback.entries.store.FBOrderProto.FBOrderItem parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeDelimitedFrom(input).buildParsed();
    }
    public static net.freeback.entries.store.FBOrderProto.FBOrderItem parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeDelimitedFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static net.freeback.entries.store.FBOrderProto.FBOrderItem parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static net.freeback.entries.store.FBOrderProto.FBOrderItem parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(net.freeback.entries.store.FBOrderProto.FBOrderItem prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> {
      private net.freeback.entries.store.FBOrderProto.FBOrderItem result;
      
      // Construct using net.freeback.entries.store.FBOrderProto.FBOrderItem.newBuilder()
      private Builder() {}
      
      private static Builder create() {
        Builder builder = new Builder();
        builder.result = new net.freeback.entries.store.FBOrderProto.FBOrderItem();
        return builder;
      }
      
      protected net.freeback.entries.store.FBOrderProto.FBOrderItem internalGetResult() {
        return result;
      }
      
      public Builder clear() {
        if (result == null) {
          throw new IllegalStateException(
            "Cannot call clear() after build().");
        }
        result = new net.freeback.entries.store.FBOrderProto.FBOrderItem();
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(result);
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return net.freeback.entries.store.FBOrderProto.FBOrderItem.getDescriptor();
      }
      
      public net.freeback.entries.store.FBOrderProto.FBOrderItem getDefaultInstanceForType() {
        return net.freeback.entries.store.FBOrderProto.FBOrderItem.getDefaultInstance();
      }
      
      public boolean isInitialized() {
        return result.isInitialized();
      }
      public net.freeback.entries.store.FBOrderProto.FBOrderItem build() {
        if (result != null && !isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return buildPartial();
      }
      
      private net.freeback.entries.store.FBOrderProto.FBOrderItem buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        if (!isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return buildPartial();
      }
      
      public net.freeback.entries.store.FBOrderProto.FBOrderItem buildPartial() {
        if (result == null) {
          throw new IllegalStateException(
            "build() has already been called on this Builder.");
        }
        net.freeback.entries.store.FBOrderProto.FBOrderItem returnMe = result;
        result = null;
        return returnMe;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof net.freeback.entries.store.FBOrderProto.FBOrderItem) {
          return mergeFrom((net.freeback.entries.store.FBOrderProto.FBOrderItem)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(net.freeback.entries.store.FBOrderProto.FBOrderItem other) {
        if (other == net.freeback.entries.store.FBOrderProto.FBOrderItem.getDefaultInstance()) return this;
        if (other.hasCode()) {
          setCode(other.getCode());
        }
        if (other.hasProduct()) {
          mergeProduct(other.getProduct());
        }
        if (other.hasAmount()) {
          setAmount(other.getAmount());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                return this;
              }
              break;
            }
            case 10: {
              setCode(input.readString());
              break;
            }
            case 18: {
              net.freeback.entries.store.FBProductProto.FBProduct.Builder subBuilder = net.freeback.entries.store.FBProductProto.FBProduct.newBuilder();
              if (hasProduct()) {
                subBuilder.mergeFrom(getProduct());
              }
              input.readMessage(subBuilder, extensionRegistry);
              setProduct(subBuilder.buildPartial());
              break;
            }
            case 24: {
              setAmount(input.readInt32());
              break;
            }
          }
        }
      }
      
      
      // required string Code = 1;
      public boolean hasCode() {
        return result.hasCode();
      }
      public java.lang.String getCode() {
        return result.getCode();
      }
      public Builder setCode(java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  result.hasCode = true;
        result.code_ = value;
        return this;
      }
      public Builder clearCode() {
        result.hasCode = false;
        result.code_ = getDefaultInstance().getCode();
        return this;
      }
      
      // required .net.freeback.FBProduct Product = 2;
      public boolean hasProduct() {
        return result.hasProduct();
      }
      public net.freeback.entries.store.FBProductProto.FBProduct getProduct() {
        return result.getProduct();
      }
      public Builder setProduct(net.freeback.entries.store.FBProductProto.FBProduct value) {
        if (value == null) {
          throw new NullPointerException();
        }
        result.hasProduct = true;
        result.product_ = value;
        return this;
      }
      public Builder setProduct(net.freeback.entries.store.FBProductProto.FBProduct.Builder builderForValue) {
        result.hasProduct = true;
        result.product_ = builderForValue.build();
        return this;
      }
      public Builder mergeProduct(net.freeback.entries.store.FBProductProto.FBProduct value) {
        if (result.hasProduct() &&
            result.product_ != net.freeback.entries.store.FBProductProto.FBProduct.getDefaultInstance()) {
          result.product_ =
            net.freeback.entries.store.FBProductProto.FBProduct.newBuilder(result.product_).mergeFrom(value).buildPartial();
        } else {
          result.product_ = value;
        }
        result.hasProduct = true;
        return this;
      }
      public Builder clearProduct() {
        result.hasProduct = false;
        result.product_ = net.freeback.entries.store.FBProductProto.FBProduct.getDefaultInstance();
        return this;
      }
      
      // required int32 Amount = 3 [default = 1];
      public boolean hasAmount() {
        return result.hasAmount();
      }
      public int getAmount() {
        return result.getAmount();
      }
      public Builder setAmount(int value) {
        result.hasAmount = true;
        result.amount_ = value;
        return this;
      }
      public Builder clearAmount() {
        result.hasAmount = false;
        result.amount_ = 1;
        return this;
      }
    }
    
    static {
      net.freeback.entries.store.FBOrderProto.getDescriptor();
    }
    
    static {
      net.freeback.entries.store.FBOrderProto.internalForceInit();
    }
  }
  
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_net_freeback_FBOrder_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_net_freeback_FBOrder_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_net_freeback_FBOrderItem_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_net_freeback_FBOrderItem_fieldAccessorTable;
  
  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\rFBOrder.proto\022\014net.freeback\032\017FBProduct" +
      ".proto\"\370\001\n\007FBOrder\022\014\n\004Code\030\001 \002(\t\022\r\n\005Stor" +
      "e\030\002 \002(\t\022\014\n\004User\030\003 \002(\t\022\016\n\006Adjust\030\005 \002(\002\022\'\n" +
      "\005State\030\010 \002(\0162\030.net.freeback.OrderState\022(" +
      "\n\005Items\030\013 \003(\0132\031.net.freeback.FBOrderItem" +
      "\022\017\n\007Address\030\014 \002(\t\022\016\n\006Remark\030\016 \001(\t\022\024\n\014Las" +
      "tModified\030\r \002(\t\022(\n\010Dispatch\030\017 \002(\0162\026.net." +
      "freeback.Delivery\"X\n\013FBOrderItem\022\014\n\004Code" +
      "\030\001 \002(\t\022(\n\007Product\030\002 \002(\0132\027.net.freeback.F" +
      "BProduct\022\021\n\006Amount\030\003 \002(\005:\0011*3\n\nOrderStat",
      "e\022\n\n\006Making\020\001\022\013\n\007OnRoute\020\002\022\014\n\010Finished\020\003" +
      "*\036\n\010Delivery\022\010\n\004Self\020\001\022\010\n\004Home\020\002B*\n\032net." +
      "freeback.entries.storeB\014FBOrderProto"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_net_freeback_FBOrder_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_net_freeback_FBOrder_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_net_freeback_FBOrder_descriptor,
              new java.lang.String[] { "Code", "Store", "User", "Adjust", "State", "Items", "Address", "Remark", "LastModified", "Dispatch", },
              net.freeback.entries.store.FBOrderProto.FBOrder.class,
              net.freeback.entries.store.FBOrderProto.FBOrder.Builder.class);
          internal_static_net_freeback_FBOrderItem_descriptor =
            getDescriptor().getMessageTypes().get(1);
          internal_static_net_freeback_FBOrderItem_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_net_freeback_FBOrderItem_descriptor,
              new java.lang.String[] { "Code", "Product", "Amount", },
              net.freeback.entries.store.FBOrderProto.FBOrderItem.class,
              net.freeback.entries.store.FBOrderProto.FBOrderItem.Builder.class);
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          net.freeback.entries.store.FBProductProto.getDescriptor(),
        }, assigner);
  }
  
  public static void internalForceInit() {}
}
