// Generated by the protocol buffer compiler.  DO NOT EDIT!

package net.freeback.entries.store;

public final class FBProductProto {
  private FBProductProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public static final class FBProducts extends
      com.google.protobuf.GeneratedMessage {
    // Use FBProducts.newBuilder() to construct.
    private FBProducts() {}
    
    private static final FBProducts defaultInstance = new FBProducts();
    public static FBProducts getDefaultInstance() {
      return defaultInstance;
    }
    
    public FBProducts getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return net.freeback.entries.store.FBProductProto.internal_static_net_freeback_FBProducts_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return net.freeback.entries.store.FBProductProto.internal_static_net_freeback_FBProducts_fieldAccessorTable;
    }
    
    // required string Code = 1;
    public static final int CODE_FIELD_NUMBER = 1;
    private boolean hasCode;
    private java.lang.String code_ = "";
    public boolean hasCode() { return hasCode; }
    public java.lang.String getCode() { return code_; }
    
    // required string Store = 2;
    public static final int STORE_FIELD_NUMBER = 2;
    private boolean hasStore;
    private java.lang.String store_ = "";
    public boolean hasStore() { return hasStore; }
    public java.lang.String getStore() { return store_; }
    
    // repeated .net.freeback.FBCategoryProduct Products = 3;
    public static final int PRODUCTS_FIELD_NUMBER = 3;
    private java.util.List<net.freeback.entries.store.FBProductProto.FBCategoryProduct> products_ =
      java.util.Collections.emptyList();
    public java.util.List<net.freeback.entries.store.FBProductProto.FBCategoryProduct> getProductsList() {
      return products_;
    }
    public int getProductsCount() { return products_.size(); }
    public net.freeback.entries.store.FBProductProto.FBCategoryProduct getProducts(int index) {
      return products_.get(index);
    }
    
    public final boolean isInitialized() {
      if (!hasCode) return false;
      if (!hasStore) return false;
      for (net.freeback.entries.store.FBProductProto.FBCategoryProduct element : getProductsList()) {
        if (!element.isInitialized()) return false;
      }
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (hasCode()) {
        output.writeString(1, getCode());
      }
      if (hasStore()) {
        output.writeString(2, getStore());
      }
      for (net.freeback.entries.store.FBProductProto.FBCategoryProduct element : getProductsList()) {
        output.writeMessage(3, element);
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      if (hasCode()) {
        size += com.google.protobuf.CodedOutputStream
          .computeStringSize(1, getCode());
      }
      if (hasStore()) {
        size += com.google.protobuf.CodedOutputStream
          .computeStringSize(2, getStore());
      }
      for (net.freeback.entries.store.FBProductProto.FBCategoryProduct element : getProductsList()) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(3, element);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    public static net.freeback.entries.store.FBProductProto.FBProducts parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static net.freeback.entries.store.FBProductProto.FBProducts parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static net.freeback.entries.store.FBProductProto.FBProducts parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static net.freeback.entries.store.FBProductProto.FBProducts parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static net.freeback.entries.store.FBProductProto.FBProducts parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static net.freeback.entries.store.FBProductProto.FBProducts parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static net.freeback.entries.store.FBProductProto.FBProducts parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeDelimitedFrom(input).buildParsed();
    }
    public static net.freeback.entries.store.FBProductProto.FBProducts parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeDelimitedFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static net.freeback.entries.store.FBProductProto.FBProducts parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static net.freeback.entries.store.FBProductProto.FBProducts parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(net.freeback.entries.store.FBProductProto.FBProducts prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> {
      private net.freeback.entries.store.FBProductProto.FBProducts result;
      
      // Construct using net.freeback.entries.store.FBProductProto.FBProducts.newBuilder()
      private Builder() {}
      
      private static Builder create() {
        Builder builder = new Builder();
        builder.result = new net.freeback.entries.store.FBProductProto.FBProducts();
        return builder;
      }
      
      protected net.freeback.entries.store.FBProductProto.FBProducts internalGetResult() {
        return result;
      }
      
      public Builder clear() {
        if (result == null) {
          throw new IllegalStateException(
            "Cannot call clear() after build().");
        }
        result = new net.freeback.entries.store.FBProductProto.FBProducts();
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(result);
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return net.freeback.entries.store.FBProductProto.FBProducts.getDescriptor();
      }
      
      public net.freeback.entries.store.FBProductProto.FBProducts getDefaultInstanceForType() {
        return net.freeback.entries.store.FBProductProto.FBProducts.getDefaultInstance();
      }
      
      public boolean isInitialized() {
        return result.isInitialized();
      }
      public net.freeback.entries.store.FBProductProto.FBProducts build() {
        if (result != null && !isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return buildPartial();
      }
      
      private net.freeback.entries.store.FBProductProto.FBProducts buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        if (!isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return buildPartial();
      }
      
      public net.freeback.entries.store.FBProductProto.FBProducts buildPartial() {
        if (result == null) {
          throw new IllegalStateException(
            "build() has already been called on this Builder.");
        }
        if (result.products_ != java.util.Collections.EMPTY_LIST) {
          result.products_ =
            java.util.Collections.unmodifiableList(result.products_);
        }
        net.freeback.entries.store.FBProductProto.FBProducts returnMe = result;
        result = null;
        return returnMe;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof net.freeback.entries.store.FBProductProto.FBProducts) {
          return mergeFrom((net.freeback.entries.store.FBProductProto.FBProducts)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(net.freeback.entries.store.FBProductProto.FBProducts other) {
        if (other == net.freeback.entries.store.FBProductProto.FBProducts.getDefaultInstance()) return this;
        if (other.hasCode()) {
          setCode(other.getCode());
        }
        if (other.hasStore()) {
          setStore(other.getStore());
        }
        if (!other.products_.isEmpty()) {
          if (result.products_.isEmpty()) {
            result.products_ = new java.util.ArrayList<net.freeback.entries.store.FBProductProto.FBCategoryProduct>();
          }
          result.products_.addAll(other.products_);
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                return this;
              }
              break;
            }
            case 10: {
              setCode(input.readString());
              break;
            }
            case 18: {
              setStore(input.readString());
              break;
            }
            case 26: {
              net.freeback.entries.store.FBProductProto.FBCategoryProduct.Builder subBuilder = net.freeback.entries.store.FBProductProto.FBCategoryProduct.newBuilder();
              input.readMessage(subBuilder, extensionRegistry);
              addProducts(subBuilder.buildPartial());
              break;
            }
          }
        }
      }
      
      
      // required string Code = 1;
      public boolean hasCode() {
        return result.hasCode();
      }
      public java.lang.String getCode() {
        return result.getCode();
      }
      public Builder setCode(java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  result.hasCode = true;
        result.code_ = value;
        return this;
      }
      public Builder clearCode() {
        result.hasCode = false;
        result.code_ = getDefaultInstance().getCode();
        return this;
      }
      
      // required string Store = 2;
      public boolean hasStore() {
        return result.hasStore();
      }
      public java.lang.String getStore() {
        return result.getStore();
      }
      public Builder setStore(java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  result.hasStore = true;
        result.store_ = value;
        return this;
      }
      public Builder clearStore() {
        result.hasStore = false;
        result.store_ = getDefaultInstance().getStore();
        return this;
      }
      
      // repeated .net.freeback.FBCategoryProduct Products = 3;
      public java.util.List<net.freeback.entries.store.FBProductProto.FBCategoryProduct> getProductsList() {
        return java.util.Collections.unmodifiableList(result.products_);
      }
      public int getProductsCount() {
        return result.getProductsCount();
      }
      public net.freeback.entries.store.FBProductProto.FBCategoryProduct getProducts(int index) {
        return result.getProducts(index);
      }
      public Builder setProducts(int index, net.freeback.entries.store.FBProductProto.FBCategoryProduct value) {
        if (value == null) {
          throw new NullPointerException();
        }
        result.products_.set(index, value);
        return this;
      }
      public Builder setProducts(int index, net.freeback.entries.store.FBProductProto.FBCategoryProduct.Builder builderForValue) {
        result.products_.set(index, builderForValue.build());
        return this;
      }
      public Builder addProducts(net.freeback.entries.store.FBProductProto.FBCategoryProduct value) {
        if (value == null) {
          throw new NullPointerException();
        }
        if (result.products_.isEmpty()) {
          result.products_ = new java.util.ArrayList<net.freeback.entries.store.FBProductProto.FBCategoryProduct>();
        }
        result.products_.add(value);
        return this;
      }
      public Builder addProducts(net.freeback.entries.store.FBProductProto.FBCategoryProduct.Builder builderForValue) {
        if (result.products_.isEmpty()) {
          result.products_ = new java.util.ArrayList<net.freeback.entries.store.FBProductProto.FBCategoryProduct>();
        }
        result.products_.add(builderForValue.build());
        return this;
      }
      public Builder addAllProducts(
          java.lang.Iterable<? extends net.freeback.entries.store.FBProductProto.FBCategoryProduct> values) {
        if (result.products_.isEmpty()) {
          result.products_ = new java.util.ArrayList<net.freeback.entries.store.FBProductProto.FBCategoryProduct>();
        }
        super.addAll(values, result.products_);
        return this;
      }
      public Builder clearProducts() {
        result.products_ = java.util.Collections.emptyList();
        return this;
      }
    }
    
    static {
      net.freeback.entries.store.FBProductProto.getDescriptor();
    }
    
    static {
      net.freeback.entries.store.FBProductProto.internalForceInit();
    }
  }
  
  public static final class FBCategoryProduct extends
      com.google.protobuf.GeneratedMessage {
    // Use FBCategoryProduct.newBuilder() to construct.
    private FBCategoryProduct() {}
    
    private static final FBCategoryProduct defaultInstance = new FBCategoryProduct();
    public static FBCategoryProduct getDefaultInstance() {
      return defaultInstance;
    }
    
    public FBCategoryProduct getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return net.freeback.entries.store.FBProductProto.internal_static_net_freeback_FBCategoryProduct_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return net.freeback.entries.store.FBProductProto.internal_static_net_freeback_FBCategoryProduct_fieldAccessorTable;
    }
    
    // required int32 Category = 1;
    public static final int CATEGORY_FIELD_NUMBER = 1;
    private boolean hasCategory;
    private int category_ = 0;
    public boolean hasCategory() { return hasCategory; }
    public int getCategory() { return category_; }
    
    // repeated .net.freeback.FBProduct Products = 2;
    public static final int PRODUCTS_FIELD_NUMBER = 2;
    private java.util.List<net.freeback.entries.store.FBProductProto.FBProduct> products_ =
      java.util.Collections.emptyList();
    public java.util.List<net.freeback.entries.store.FBProductProto.FBProduct> getProductsList() {
      return products_;
    }
    public int getProductsCount() { return products_.size(); }
    public net.freeback.entries.store.FBProductProto.FBProduct getProducts(int index) {
      return products_.get(index);
    }
    
    public final boolean isInitialized() {
      if (!hasCategory) return false;
      for (net.freeback.entries.store.FBProductProto.FBProduct element : getProductsList()) {
        if (!element.isInitialized()) return false;
      }
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (hasCategory()) {
        output.writeInt32(1, getCategory());
      }
      for (net.freeback.entries.store.FBProductProto.FBProduct element : getProductsList()) {
        output.writeMessage(2, element);
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      if (hasCategory()) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, getCategory());
      }
      for (net.freeback.entries.store.FBProductProto.FBProduct element : getProductsList()) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(2, element);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    public static net.freeback.entries.store.FBProductProto.FBCategoryProduct parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static net.freeback.entries.store.FBProductProto.FBCategoryProduct parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static net.freeback.entries.store.FBProductProto.FBCategoryProduct parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static net.freeback.entries.store.FBProductProto.FBCategoryProduct parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static net.freeback.entries.store.FBProductProto.FBCategoryProduct parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static net.freeback.entries.store.FBProductProto.FBCategoryProduct parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static net.freeback.entries.store.FBProductProto.FBCategoryProduct parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeDelimitedFrom(input).buildParsed();
    }
    public static net.freeback.entries.store.FBProductProto.FBCategoryProduct parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeDelimitedFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static net.freeback.entries.store.FBProductProto.FBCategoryProduct parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static net.freeback.entries.store.FBProductProto.FBCategoryProduct parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(net.freeback.entries.store.FBProductProto.FBCategoryProduct prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> {
      private net.freeback.entries.store.FBProductProto.FBCategoryProduct result;
      
      // Construct using net.freeback.entries.store.FBProductProto.FBCategoryProduct.newBuilder()
      private Builder() {}
      
      private static Builder create() {
        Builder builder = new Builder();
        builder.result = new net.freeback.entries.store.FBProductProto.FBCategoryProduct();
        return builder;
      }
      
      protected net.freeback.entries.store.FBProductProto.FBCategoryProduct internalGetResult() {
        return result;
      }
      
      public Builder clear() {
        if (result == null) {
          throw new IllegalStateException(
            "Cannot call clear() after build().");
        }
        result = new net.freeback.entries.store.FBProductProto.FBCategoryProduct();
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(result);
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return net.freeback.entries.store.FBProductProto.FBCategoryProduct.getDescriptor();
      }
      
      public net.freeback.entries.store.FBProductProto.FBCategoryProduct getDefaultInstanceForType() {
        return net.freeback.entries.store.FBProductProto.FBCategoryProduct.getDefaultInstance();
      }
      
      public boolean isInitialized() {
        return result.isInitialized();
      }
      public net.freeback.entries.store.FBProductProto.FBCategoryProduct build() {
        if (result != null && !isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return buildPartial();
      }
      
      private net.freeback.entries.store.FBProductProto.FBCategoryProduct buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        if (!isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return buildPartial();
      }
      
      public net.freeback.entries.store.FBProductProto.FBCategoryProduct buildPartial() {
        if (result == null) {
          throw new IllegalStateException(
            "build() has already been called on this Builder.");
        }
        if (result.products_ != java.util.Collections.EMPTY_LIST) {
          result.products_ =
            java.util.Collections.unmodifiableList(result.products_);
        }
        net.freeback.entries.store.FBProductProto.FBCategoryProduct returnMe = result;
        result = null;
        return returnMe;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof net.freeback.entries.store.FBProductProto.FBCategoryProduct) {
          return mergeFrom((net.freeback.entries.store.FBProductProto.FBCategoryProduct)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(net.freeback.entries.store.FBProductProto.FBCategoryProduct other) {
        if (other == net.freeback.entries.store.FBProductProto.FBCategoryProduct.getDefaultInstance()) return this;
        if (other.hasCategory()) {
          setCategory(other.getCategory());
        }
        if (!other.products_.isEmpty()) {
          if (result.products_.isEmpty()) {
            result.products_ = new java.util.ArrayList<net.freeback.entries.store.FBProductProto.FBProduct>();
          }
          result.products_.addAll(other.products_);
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                return this;
              }
              break;
            }
            case 8: {
              setCategory(input.readInt32());
              break;
            }
            case 18: {
              net.freeback.entries.store.FBProductProto.FBProduct.Builder subBuilder = net.freeback.entries.store.FBProductProto.FBProduct.newBuilder();
              input.readMessage(subBuilder, extensionRegistry);
              addProducts(subBuilder.buildPartial());
              break;
            }
          }
        }
      }
      
      
      // required int32 Category = 1;
      public boolean hasCategory() {
        return result.hasCategory();
      }
      public int getCategory() {
        return result.getCategory();
      }
      public Builder setCategory(int value) {
        result.hasCategory = true;
        result.category_ = value;
        return this;
      }
      public Builder clearCategory() {
        result.hasCategory = false;
        result.category_ = 0;
        return this;
      }
      
      // repeated .net.freeback.FBProduct Products = 2;
      public java.util.List<net.freeback.entries.store.FBProductProto.FBProduct> getProductsList() {
        return java.util.Collections.unmodifiableList(result.products_);
      }
      public int getProductsCount() {
        return result.getProductsCount();
      }
      public net.freeback.entries.store.FBProductProto.FBProduct getProducts(int index) {
        return result.getProducts(index);
      }
      public Builder setProducts(int index, net.freeback.entries.store.FBProductProto.FBProduct value) {
        if (value == null) {
          throw new NullPointerException();
        }
        result.products_.set(index, value);
        return this;
      }
      public Builder setProducts(int index, net.freeback.entries.store.FBProductProto.FBProduct.Builder builderForValue) {
        result.products_.set(index, builderForValue.build());
        return this;
      }
      public Builder addProducts(net.freeback.entries.store.FBProductProto.FBProduct value) {
        if (value == null) {
          throw new NullPointerException();
        }
        if (result.products_.isEmpty()) {
          result.products_ = new java.util.ArrayList<net.freeback.entries.store.FBProductProto.FBProduct>();
        }
        result.products_.add(value);
        return this;
      }
      public Builder addProducts(net.freeback.entries.store.FBProductProto.FBProduct.Builder builderForValue) {
        if (result.products_.isEmpty()) {
          result.products_ = new java.util.ArrayList<net.freeback.entries.store.FBProductProto.FBProduct>();
        }
        result.products_.add(builderForValue.build());
        return this;
      }
      public Builder addAllProducts(
          java.lang.Iterable<? extends net.freeback.entries.store.FBProductProto.FBProduct> values) {
        if (result.products_.isEmpty()) {
          result.products_ = new java.util.ArrayList<net.freeback.entries.store.FBProductProto.FBProduct>();
        }
        super.addAll(values, result.products_);
        return this;
      }
      public Builder clearProducts() {
        result.products_ = java.util.Collections.emptyList();
        return this;
      }
    }
    
    static {
      net.freeback.entries.store.FBProductProto.getDescriptor();
    }
    
    static {
      net.freeback.entries.store.FBProductProto.internalForceInit();
    }
  }
  
  public static final class FBProduct extends
      com.google.protobuf.GeneratedMessage {
    // Use FBProduct.newBuilder() to construct.
    private FBProduct() {}
    
    private static final FBProduct defaultInstance = new FBProduct();
    public static FBProduct getDefaultInstance() {
      return defaultInstance;
    }
    
    public FBProduct getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return net.freeback.entries.store.FBProductProto.internal_static_net_freeback_FBProduct_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return net.freeback.entries.store.FBProductProto.internal_static_net_freeback_FBProduct_fieldAccessorTable;
    }
    
    // required string Code = 1;
    public static final int CODE_FIELD_NUMBER = 1;
    private boolean hasCode;
    private java.lang.String code_ = "";
    public boolean hasCode() { return hasCode; }
    public java.lang.String getCode() { return code_; }
    
    // repeated string Photos = 2;
    public static final int PHOTOS_FIELD_NUMBER = 2;
    private java.util.List<java.lang.String> photos_ =
      java.util.Collections.emptyList();
    public java.util.List<java.lang.String> getPhotosList() {
      return photos_;
    }
    public int getPhotosCount() { return photos_.size(); }
    public java.lang.String getPhotos(int index) {
      return photos_.get(index);
    }
    
    // required string Name = 3;
    public static final int NAME_FIELD_NUMBER = 3;
    private boolean hasName;
    private java.lang.String name_ = "";
    public boolean hasName() { return hasName; }
    public java.lang.String getName() { return name_; }
    
    // required int32 Order = 4;
    public static final int ORDER_FIELD_NUMBER = 4;
    private boolean hasOrder;
    private int order_ = 0;
    public boolean hasOrder() { return hasOrder; }
    public int getOrder() { return order_; }
    
    // repeated .net.freeback.FBStock Stocks = 5;
    public static final int STOCKS_FIELD_NUMBER = 5;
    private java.util.List<net.freeback.entries.store.FBProductProto.FBStock> stocks_ =
      java.util.Collections.emptyList();
    public java.util.List<net.freeback.entries.store.FBProductProto.FBStock> getStocksList() {
      return stocks_;
    }
    public int getStocksCount() { return stocks_.size(); }
    public net.freeback.entries.store.FBProductProto.FBStock getStocks(int index) {
      return stocks_.get(index);
    }
    
    // optional string Description = 6;
    public static final int DESCRIPTION_FIELD_NUMBER = 6;
    private boolean hasDescription;
    private java.lang.String description_ = "";
    public boolean hasDescription() { return hasDescription; }
    public java.lang.String getDescription() { return description_; }
    
    // required string Modified = 7;
    public static final int MODIFIED_FIELD_NUMBER = 7;
    private boolean hasModified;
    private java.lang.String modified_ = "";
    public boolean hasModified() { return hasModified; }
    public java.lang.String getModified() { return modified_; }
    
    public final boolean isInitialized() {
      if (!hasCode) return false;
      if (!hasName) return false;
      if (!hasOrder) return false;
      if (!hasModified) return false;
      for (net.freeback.entries.store.FBProductProto.FBStock element : getStocksList()) {
        if (!element.isInitialized()) return false;
      }
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (hasCode()) {
        output.writeString(1, getCode());
      }
      for (java.lang.String element : getPhotosList()) {
        output.writeString(2, element);
      }
      if (hasName()) {
        output.writeString(3, getName());
      }
      if (hasOrder()) {
        output.writeInt32(4, getOrder());
      }
      for (net.freeback.entries.store.FBProductProto.FBStock element : getStocksList()) {
        output.writeMessage(5, element);
      }
      if (hasDescription()) {
        output.writeString(6, getDescription());
      }
      if (hasModified()) {
        output.writeString(7, getModified());
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      if (hasCode()) {
        size += com.google.protobuf.CodedOutputStream
          .computeStringSize(1, getCode());
      }
      {
        int dataSize = 0;
        for (java.lang.String element : getPhotosList()) {
          dataSize += com.google.protobuf.CodedOutputStream
            .computeStringSizeNoTag(element);
        }
        size += dataSize;
        size += 1 * getPhotosList().size();
      }
      if (hasName()) {
        size += com.google.protobuf.CodedOutputStream
          .computeStringSize(3, getName());
      }
      if (hasOrder()) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(4, getOrder());
      }
      for (net.freeback.entries.store.FBProductProto.FBStock element : getStocksList()) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(5, element);
      }
      if (hasDescription()) {
        size += com.google.protobuf.CodedOutputStream
          .computeStringSize(6, getDescription());
      }
      if (hasModified()) {
        size += com.google.protobuf.CodedOutputStream
          .computeStringSize(7, getModified());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    public static net.freeback.entries.store.FBProductProto.FBProduct parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static net.freeback.entries.store.FBProductProto.FBProduct parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static net.freeback.entries.store.FBProductProto.FBProduct parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static net.freeback.entries.store.FBProductProto.FBProduct parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static net.freeback.entries.store.FBProductProto.FBProduct parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static net.freeback.entries.store.FBProductProto.FBProduct parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static net.freeback.entries.store.FBProductProto.FBProduct parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeDelimitedFrom(input).buildParsed();
    }
    public static net.freeback.entries.store.FBProductProto.FBProduct parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeDelimitedFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static net.freeback.entries.store.FBProductProto.FBProduct parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static net.freeback.entries.store.FBProductProto.FBProduct parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(net.freeback.entries.store.FBProductProto.FBProduct prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> {
      private net.freeback.entries.store.FBProductProto.FBProduct result;
      
      // Construct using net.freeback.entries.store.FBProductProto.FBProduct.newBuilder()
      private Builder() {}
      
      private static Builder create() {
        Builder builder = new Builder();
        builder.result = new net.freeback.entries.store.FBProductProto.FBProduct();
        return builder;
      }
      
      protected net.freeback.entries.store.FBProductProto.FBProduct internalGetResult() {
        return result;
      }
      
      public Builder clear() {
        if (result == null) {
          throw new IllegalStateException(
            "Cannot call clear() after build().");
        }
        result = new net.freeback.entries.store.FBProductProto.FBProduct();
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(result);
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return net.freeback.entries.store.FBProductProto.FBProduct.getDescriptor();
      }
      
      public net.freeback.entries.store.FBProductProto.FBProduct getDefaultInstanceForType() {
        return net.freeback.entries.store.FBProductProto.FBProduct.getDefaultInstance();
      }
      
      public boolean isInitialized() {
        return result.isInitialized();
      }
      public net.freeback.entries.store.FBProductProto.FBProduct build() {
        if (result != null && !isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return buildPartial();
      }
      
      private net.freeback.entries.store.FBProductProto.FBProduct buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        if (!isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return buildPartial();
      }
      
      public net.freeback.entries.store.FBProductProto.FBProduct buildPartial() {
        if (result == null) {
          throw new IllegalStateException(
            "build() has already been called on this Builder.");
        }
        if (result.photos_ != java.util.Collections.EMPTY_LIST) {
          result.photos_ =
            java.util.Collections.unmodifiableList(result.photos_);
        }
        if (result.stocks_ != java.util.Collections.EMPTY_LIST) {
          result.stocks_ =
            java.util.Collections.unmodifiableList(result.stocks_);
        }
        net.freeback.entries.store.FBProductProto.FBProduct returnMe = result;
        result = null;
        return returnMe;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof net.freeback.entries.store.FBProductProto.FBProduct) {
          return mergeFrom((net.freeback.entries.store.FBProductProto.FBProduct)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(net.freeback.entries.store.FBProductProto.FBProduct other) {
        if (other == net.freeback.entries.store.FBProductProto.FBProduct.getDefaultInstance()) return this;
        if (other.hasCode()) {
          setCode(other.getCode());
        }
        if (!other.photos_.isEmpty()) {
          if (result.photos_.isEmpty()) {
            result.photos_ = new java.util.ArrayList<java.lang.String>();
          }
          result.photos_.addAll(other.photos_);
        }
        if (other.hasName()) {
          setName(other.getName());
        }
        if (other.hasOrder()) {
          setOrder(other.getOrder());
        }
        if (!other.stocks_.isEmpty()) {
          if (result.stocks_.isEmpty()) {
            result.stocks_ = new java.util.ArrayList<net.freeback.entries.store.FBProductProto.FBStock>();
          }
          result.stocks_.addAll(other.stocks_);
        }
        if (other.hasDescription()) {
          setDescription(other.getDescription());
        }
        if (other.hasModified()) {
          setModified(other.getModified());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                return this;
              }
              break;
            }
            case 10: {
              setCode(input.readString());
              break;
            }
            case 18: {
              addPhotos(input.readString());
              break;
            }
            case 26: {
              setName(input.readString());
              break;
            }
            case 32: {
              setOrder(input.readInt32());
              break;
            }
            case 42: {
              net.freeback.entries.store.FBProductProto.FBStock.Builder subBuilder = net.freeback.entries.store.FBProductProto.FBStock.newBuilder();
              input.readMessage(subBuilder, extensionRegistry);
              addStocks(subBuilder.buildPartial());
              break;
            }
            case 50: {
              setDescription(input.readString());
              break;
            }
            case 58: {
              setModified(input.readString());
              break;
            }
          }
        }
      }
      
      
      // required string Code = 1;
      public boolean hasCode() {
        return result.hasCode();
      }
      public java.lang.String getCode() {
        return result.getCode();
      }
      public Builder setCode(java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  result.hasCode = true;
        result.code_ = value;
        return this;
      }
      public Builder clearCode() {
        result.hasCode = false;
        result.code_ = getDefaultInstance().getCode();
        return this;
      }
      
      // repeated string Photos = 2;
      public java.util.List<java.lang.String> getPhotosList() {
        return java.util.Collections.unmodifiableList(result.photos_);
      }
      public int getPhotosCount() {
        return result.getPhotosCount();
      }
      public java.lang.String getPhotos(int index) {
        return result.getPhotos(index);
      }
      public Builder setPhotos(int index, java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  result.photos_.set(index, value);
        return this;
      }
      public Builder addPhotos(java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  if (result.photos_.isEmpty()) {
          result.photos_ = new java.util.ArrayList<java.lang.String>();
        }
        result.photos_.add(value);
        return this;
      }
      public Builder addAllPhotos(
          java.lang.Iterable<? extends java.lang.String> values) {
        if (result.photos_.isEmpty()) {
          result.photos_ = new java.util.ArrayList<java.lang.String>();
        }
        super.addAll(values, result.photos_);
        return this;
      }
      public Builder clearPhotos() {
        result.photos_ = java.util.Collections.emptyList();
        return this;
      }
      
      // required string Name = 3;
      public boolean hasName() {
        return result.hasName();
      }
      public java.lang.String getName() {
        return result.getName();
      }
      public Builder setName(java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  result.hasName = true;
        result.name_ = value;
        return this;
      }
      public Builder clearName() {
        result.hasName = false;
        result.name_ = getDefaultInstance().getName();
        return this;
      }
      
      // required int32 Order = 4;
      public boolean hasOrder() {
        return result.hasOrder();
      }
      public int getOrder() {
        return result.getOrder();
      }
      public Builder setOrder(int value) {
        result.hasOrder = true;
        result.order_ = value;
        return this;
      }
      public Builder clearOrder() {
        result.hasOrder = false;
        result.order_ = 0;
        return this;
      }
      
      // repeated .net.freeback.FBStock Stocks = 5;
      public java.util.List<net.freeback.entries.store.FBProductProto.FBStock> getStocksList() {
        return java.util.Collections.unmodifiableList(result.stocks_);
      }
      public int getStocksCount() {
        return result.getStocksCount();
      }
      public net.freeback.entries.store.FBProductProto.FBStock getStocks(int index) {
        return result.getStocks(index);
      }
      public Builder setStocks(int index, net.freeback.entries.store.FBProductProto.FBStock value) {
        if (value == null) {
          throw new NullPointerException();
        }
        result.stocks_.set(index, value);
        return this;
      }
      public Builder setStocks(int index, net.freeback.entries.store.FBProductProto.FBStock.Builder builderForValue) {
        result.stocks_.set(index, builderForValue.build());
        return this;
      }
      public Builder addStocks(net.freeback.entries.store.FBProductProto.FBStock value) {
        if (value == null) {
          throw new NullPointerException();
        }
        if (result.stocks_.isEmpty()) {
          result.stocks_ = new java.util.ArrayList<net.freeback.entries.store.FBProductProto.FBStock>();
        }
        result.stocks_.add(value);
        return this;
      }
      public Builder addStocks(net.freeback.entries.store.FBProductProto.FBStock.Builder builderForValue) {
        if (result.stocks_.isEmpty()) {
          result.stocks_ = new java.util.ArrayList<net.freeback.entries.store.FBProductProto.FBStock>();
        }
        result.stocks_.add(builderForValue.build());
        return this;
      }
      public Builder addAllStocks(
          java.lang.Iterable<? extends net.freeback.entries.store.FBProductProto.FBStock> values) {
        if (result.stocks_.isEmpty()) {
          result.stocks_ = new java.util.ArrayList<net.freeback.entries.store.FBProductProto.FBStock>();
        }
        super.addAll(values, result.stocks_);
        return this;
      }
      public Builder clearStocks() {
        result.stocks_ = java.util.Collections.emptyList();
        return this;
      }
      
      // optional string Description = 6;
      public boolean hasDescription() {
        return result.hasDescription();
      }
      public java.lang.String getDescription() {
        return result.getDescription();
      }
      public Builder setDescription(java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  result.hasDescription = true;
        result.description_ = value;
        return this;
      }
      public Builder clearDescription() {
        result.hasDescription = false;
        result.description_ = getDefaultInstance().getDescription();
        return this;
      }
      
      // required string Modified = 7;
      public boolean hasModified() {
        return result.hasModified();
      }
      public java.lang.String getModified() {
        return result.getModified();
      }
      public Builder setModified(java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  result.hasModified = true;
        result.modified_ = value;
        return this;
      }
      public Builder clearModified() {
        result.hasModified = false;
        result.modified_ = getDefaultInstance().getModified();
        return this;
      }
    }
    
    static {
      net.freeback.entries.store.FBProductProto.getDescriptor();
    }
    
    static {
      net.freeback.entries.store.FBProductProto.internalForceInit();
    }
  }
  
  public static final class FBStock extends
      com.google.protobuf.GeneratedMessage {
    // Use FBStock.newBuilder() to construct.
    private FBStock() {}
    
    private static final FBStock defaultInstance = new FBStock();
    public static FBStock getDefaultInstance() {
      return defaultInstance;
    }
    
    public FBStock getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return net.freeback.entries.store.FBProductProto.internal_static_net_freeback_FBStock_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return net.freeback.entries.store.FBProductProto.internal_static_net_freeback_FBStock_fieldAccessorTable;
    }
    
    // required string Dimension = 1;
    public static final int DIMENSION_FIELD_NUMBER = 1;
    private boolean hasDimension;
    private java.lang.String dimension_ = "";
    public boolean hasDimension() { return hasDimension; }
    public java.lang.String getDimension() { return dimension_; }
    
    // required float Price = 2;
    public static final int PRICE_FIELD_NUMBER = 2;
    private boolean hasPrice;
    private float price_ = 0F;
    public boolean hasPrice() { return hasPrice; }
    public float getPrice() { return price_; }
    
    // required int32 Stocks = 3;
    public static final int STOCKS_FIELD_NUMBER = 3;
    private boolean hasStocks;
    private int stocks_ = 0;
    public boolean hasStocks() { return hasStocks; }
    public int getStocks() { return stocks_; }
    
    public final boolean isInitialized() {
      if (!hasDimension) return false;
      if (!hasPrice) return false;
      if (!hasStocks) return false;
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (hasDimension()) {
        output.writeString(1, getDimension());
      }
      if (hasPrice()) {
        output.writeFloat(2, getPrice());
      }
      if (hasStocks()) {
        output.writeInt32(3, getStocks());
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      if (hasDimension()) {
        size += com.google.protobuf.CodedOutputStream
          .computeStringSize(1, getDimension());
      }
      if (hasPrice()) {
        size += com.google.protobuf.CodedOutputStream
          .computeFloatSize(2, getPrice());
      }
      if (hasStocks()) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(3, getStocks());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    public static net.freeback.entries.store.FBProductProto.FBStock parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static net.freeback.entries.store.FBProductProto.FBStock parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static net.freeback.entries.store.FBProductProto.FBStock parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static net.freeback.entries.store.FBProductProto.FBStock parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static net.freeback.entries.store.FBProductProto.FBStock parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static net.freeback.entries.store.FBProductProto.FBStock parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static net.freeback.entries.store.FBProductProto.FBStock parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeDelimitedFrom(input).buildParsed();
    }
    public static net.freeback.entries.store.FBProductProto.FBStock parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeDelimitedFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static net.freeback.entries.store.FBProductProto.FBStock parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static net.freeback.entries.store.FBProductProto.FBStock parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(net.freeback.entries.store.FBProductProto.FBStock prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> {
      private net.freeback.entries.store.FBProductProto.FBStock result;
      
      // Construct using net.freeback.entries.store.FBProductProto.FBStock.newBuilder()
      private Builder() {}
      
      private static Builder create() {
        Builder builder = new Builder();
        builder.result = new net.freeback.entries.store.FBProductProto.FBStock();
        return builder;
      }
      
      protected net.freeback.entries.store.FBProductProto.FBStock internalGetResult() {
        return result;
      }
      
      public Builder clear() {
        if (result == null) {
          throw new IllegalStateException(
            "Cannot call clear() after build().");
        }
        result = new net.freeback.entries.store.FBProductProto.FBStock();
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(result);
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return net.freeback.entries.store.FBProductProto.FBStock.getDescriptor();
      }
      
      public net.freeback.entries.store.FBProductProto.FBStock getDefaultInstanceForType() {
        return net.freeback.entries.store.FBProductProto.FBStock.getDefaultInstance();
      }
      
      public boolean isInitialized() {
        return result.isInitialized();
      }
      public net.freeback.entries.store.FBProductProto.FBStock build() {
        if (result != null && !isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return buildPartial();
      }
      
      private net.freeback.entries.store.FBProductProto.FBStock buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        if (!isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return buildPartial();
      }
      
      public net.freeback.entries.store.FBProductProto.FBStock buildPartial() {
        if (result == null) {
          throw new IllegalStateException(
            "build() has already been called on this Builder.");
        }
        net.freeback.entries.store.FBProductProto.FBStock returnMe = result;
        result = null;
        return returnMe;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof net.freeback.entries.store.FBProductProto.FBStock) {
          return mergeFrom((net.freeback.entries.store.FBProductProto.FBStock)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(net.freeback.entries.store.FBProductProto.FBStock other) {
        if (other == net.freeback.entries.store.FBProductProto.FBStock.getDefaultInstance()) return this;
        if (other.hasDimension()) {
          setDimension(other.getDimension());
        }
        if (other.hasPrice()) {
          setPrice(other.getPrice());
        }
        if (other.hasStocks()) {
          setStocks(other.getStocks());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                return this;
              }
              break;
            }
            case 10: {
              setDimension(input.readString());
              break;
            }
            case 21: {
              setPrice(input.readFloat());
              break;
            }
            case 24: {
              setStocks(input.readInt32());
              break;
            }
          }
        }
      }
      
      
      // required string Dimension = 1;
      public boolean hasDimension() {
        return result.hasDimension();
      }
      public java.lang.String getDimension() {
        return result.getDimension();
      }
      public Builder setDimension(java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  result.hasDimension = true;
        result.dimension_ = value;
        return this;
      }
      public Builder clearDimension() {
        result.hasDimension = false;
        result.dimension_ = getDefaultInstance().getDimension();
        return this;
      }
      
      // required float Price = 2;
      public boolean hasPrice() {
        return result.hasPrice();
      }
      public float getPrice() {
        return result.getPrice();
      }
      public Builder setPrice(float value) {
        result.hasPrice = true;
        result.price_ = value;
        return this;
      }
      public Builder clearPrice() {
        result.hasPrice = false;
        result.price_ = 0F;
        return this;
      }
      
      // required int32 Stocks = 3;
      public boolean hasStocks() {
        return result.hasStocks();
      }
      public int getStocks() {
        return result.getStocks();
      }
      public Builder setStocks(int value) {
        result.hasStocks = true;
        result.stocks_ = value;
        return this;
      }
      public Builder clearStocks() {
        result.hasStocks = false;
        result.stocks_ = 0;
        return this;
      }
    }
    
    static {
      net.freeback.entries.store.FBProductProto.getDescriptor();
    }
    
    static {
      net.freeback.entries.store.FBProductProto.internalForceInit();
    }
  }
  
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_net_freeback_FBProducts_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_net_freeback_FBProducts_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_net_freeback_FBCategoryProduct_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_net_freeback_FBCategoryProduct_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_net_freeback_FBProduct_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_net_freeback_FBProduct_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_net_freeback_FBStock_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_net_freeback_FBStock_fieldAccessorTable;
  
  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\017FBProduct.proto\022\014net.freeback\032\016FBSyste" +
      "m.proto\"\\\n\nFBProducts\022\014\n\004Code\030\001 \002(\t\022\r\n\005S" +
      "tore\030\002 \002(\t\0221\n\010Products\030\003 \003(\0132\037.net.freeb" +
      "ack.FBCategoryProduct\"P\n\021FBCategoryProdu" +
      "ct\022\020\n\010Category\030\001 \002(\005\022)\n\010Products\030\002 \003(\0132\027" +
      ".net.freeback.FBProduct\"\224\001\n\tFBProduct\022\014\n" +
      "\004Code\030\001 \002(\t\022\016\n\006Photos\030\002 \003(\t\022\014\n\004Name\030\003 \002(" +
      "\t\022\r\n\005Order\030\004 \002(\005\022%\n\006Stocks\030\005 \003(\0132\025.net.f" +
      "reeback.FBStock\022\023\n\013Description\030\006 \001(\t\022\020\n\010" +
      "Modified\030\007 \002(\t\";\n\007FBStock\022\021\n\tDimension\030\001",
      " \002(\t\022\r\n\005Price\030\002 \002(\002\022\016\n\006Stocks\030\003 \002(\005B,\n\032n" +
      "et.freeback.entries.storeB\016FBProductProt" +
      "o"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_net_freeback_FBProducts_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_net_freeback_FBProducts_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_net_freeback_FBProducts_descriptor,
              new java.lang.String[] { "Code", "Store", "Products", },
              net.freeback.entries.store.FBProductProto.FBProducts.class,
              net.freeback.entries.store.FBProductProto.FBProducts.Builder.class);
          internal_static_net_freeback_FBCategoryProduct_descriptor =
            getDescriptor().getMessageTypes().get(1);
          internal_static_net_freeback_FBCategoryProduct_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_net_freeback_FBCategoryProduct_descriptor,
              new java.lang.String[] { "Category", "Products", },
              net.freeback.entries.store.FBProductProto.FBCategoryProduct.class,
              net.freeback.entries.store.FBProductProto.FBCategoryProduct.Builder.class);
          internal_static_net_freeback_FBProduct_descriptor =
            getDescriptor().getMessageTypes().get(2);
          internal_static_net_freeback_FBProduct_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_net_freeback_FBProduct_descriptor,
              new java.lang.String[] { "Code", "Photos", "Name", "Order", "Stocks", "Description", "Modified", },
              net.freeback.entries.store.FBProductProto.FBProduct.class,
              net.freeback.entries.store.FBProductProto.FBProduct.Builder.class);
          internal_static_net_freeback_FBStock_descriptor =
            getDescriptor().getMessageTypes().get(3);
          internal_static_net_freeback_FBStock_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_net_freeback_FBStock_descriptor,
              new java.lang.String[] { "Dimension", "Price", "Stocks", },
              net.freeback.entries.store.FBProductProto.FBStock.class,
              net.freeback.entries.store.FBProductProto.FBStock.Builder.class);
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          net.freeback.entries.FBSystemProto.getDescriptor(),
        }, assigner);
  }
  
  public static void internalForceInit() {}
}
