// Generated by the protocol buffer compiler.  DO NOT EDIT!

package net.freeback.entries.store;

public final class FBStoreDictProto {
  private FBStoreDictProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public static final class FBStoreDict extends
      com.google.protobuf.GeneratedMessage {
    // Use FBStoreDict.newBuilder() to construct.
    private FBStoreDict() {}
    
    private static final FBStoreDict defaultInstance = new FBStoreDict();
    public static FBStoreDict getDefaultInstance() {
      return defaultInstance;
    }
    
    public FBStoreDict getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return net.freeback.entries.store.FBStoreDictProto.internal_static_net_freeback_FBStoreDict_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return net.freeback.entries.store.FBStoreDictProto.internal_static_net_freeback_FBStoreDict_fieldAccessorTable;
    }
    
    // required string Code = 1;
    public static final int CODE_FIELD_NUMBER = 1;
    private boolean hasCode;
    private java.lang.String code_ = "";
    public boolean hasCode() { return hasCode; }
    public java.lang.String getCode() { return code_; }
    
    // required string Store = 2;
    public static final int STORE_FIELD_NUMBER = 2;
    private boolean hasStore;
    private java.lang.String store_ = "";
    public boolean hasStore() { return hasStore; }
    public java.lang.String getStore() { return store_; }
    
    // required int32 VersionValue = 3;
    public static final int VERSIONVALUE_FIELD_NUMBER = 3;
    private boolean hasVersionValue;
    private int versionValue_ = 0;
    public boolean hasVersionValue() { return hasVersionValue; }
    public int getVersionValue() { return versionValue_; }
    
    // repeated .net.freeback.FBIndustry Industires = 4;
    public static final int INDUSTIRES_FIELD_NUMBER = 4;
    private java.util.List<net.freeback.entries.FBSystemProto.FBIndustry> industires_ =
      java.util.Collections.emptyList();
    public java.util.List<net.freeback.entries.FBSystemProto.FBIndustry> getIndustiresList() {
      return industires_;
    }
    public int getIndustiresCount() { return industires_.size(); }
    public net.freeback.entries.FBSystemProto.FBIndustry getIndustires(int index) {
      return industires_.get(index);
    }
    
    // repeated .net.freeback.FBCategory Categories = 5;
    public static final int CATEGORIES_FIELD_NUMBER = 5;
    private java.util.List<net.freeback.entries.FBSystemProto.FBCategory> categories_ =
      java.util.Collections.emptyList();
    public java.util.List<net.freeback.entries.FBSystemProto.FBCategory> getCategoriesList() {
      return categories_;
    }
    public int getCategoriesCount() { return categories_.size(); }
    public net.freeback.entries.FBSystemProto.FBCategory getCategories(int index) {
      return categories_.get(index);
    }
    
    // repeated .net.freeback.FBDimension Dimensions = 6;
    public static final int DIMENSIONS_FIELD_NUMBER = 6;
    private java.util.List<net.freeback.entries.FBSystemProto.FBDimension> dimensions_ =
      java.util.Collections.emptyList();
    public java.util.List<net.freeback.entries.FBSystemProto.FBDimension> getDimensionsList() {
      return dimensions_;
    }
    public int getDimensionsCount() { return dimensions_.size(); }
    public net.freeback.entries.FBSystemProto.FBDimension getDimensions(int index) {
      return dimensions_.get(index);
    }
    
    public final boolean isInitialized() {
      if (!hasCode) return false;
      if (!hasStore) return false;
      if (!hasVersionValue) return false;
      for (net.freeback.entries.FBSystemProto.FBIndustry element : getIndustiresList()) {
        if (!element.isInitialized()) return false;
      }
      for (net.freeback.entries.FBSystemProto.FBCategory element : getCategoriesList()) {
        if (!element.isInitialized()) return false;
      }
      for (net.freeback.entries.FBSystemProto.FBDimension element : getDimensionsList()) {
        if (!element.isInitialized()) return false;
      }
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (hasCode()) {
        output.writeString(1, getCode());
      }
      if (hasStore()) {
        output.writeString(2, getStore());
      }
      if (hasVersionValue()) {
        output.writeInt32(3, getVersionValue());
      }
      for (net.freeback.entries.FBSystemProto.FBIndustry element : getIndustiresList()) {
        output.writeMessage(4, element);
      }
      for (net.freeback.entries.FBSystemProto.FBCategory element : getCategoriesList()) {
        output.writeMessage(5, element);
      }
      for (net.freeback.entries.FBSystemProto.FBDimension element : getDimensionsList()) {
        output.writeMessage(6, element);
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      if (hasCode()) {
        size += com.google.protobuf.CodedOutputStream
          .computeStringSize(1, getCode());
      }
      if (hasStore()) {
        size += com.google.protobuf.CodedOutputStream
          .computeStringSize(2, getStore());
      }
      if (hasVersionValue()) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(3, getVersionValue());
      }
      for (net.freeback.entries.FBSystemProto.FBIndustry element : getIndustiresList()) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(4, element);
      }
      for (net.freeback.entries.FBSystemProto.FBCategory element : getCategoriesList()) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(5, element);
      }
      for (net.freeback.entries.FBSystemProto.FBDimension element : getDimensionsList()) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(6, element);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    public static net.freeback.entries.store.FBStoreDictProto.FBStoreDict parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static net.freeback.entries.store.FBStoreDictProto.FBStoreDict parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static net.freeback.entries.store.FBStoreDictProto.FBStoreDict parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static net.freeback.entries.store.FBStoreDictProto.FBStoreDict parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static net.freeback.entries.store.FBStoreDictProto.FBStoreDict parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static net.freeback.entries.store.FBStoreDictProto.FBStoreDict parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static net.freeback.entries.store.FBStoreDictProto.FBStoreDict parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeDelimitedFrom(input).buildParsed();
    }
    public static net.freeback.entries.store.FBStoreDictProto.FBStoreDict parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeDelimitedFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static net.freeback.entries.store.FBStoreDictProto.FBStoreDict parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static net.freeback.entries.store.FBStoreDictProto.FBStoreDict parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(net.freeback.entries.store.FBStoreDictProto.FBStoreDict prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> {
      private net.freeback.entries.store.FBStoreDictProto.FBStoreDict result;
      
      // Construct using net.freeback.entries.store.FBStoreDictProto.FBStoreDict.newBuilder()
      private Builder() {}
      
      private static Builder create() {
        Builder builder = new Builder();
        builder.result = new net.freeback.entries.store.FBStoreDictProto.FBStoreDict();
        return builder;
      }
      
      protected net.freeback.entries.store.FBStoreDictProto.FBStoreDict internalGetResult() {
        return result;
      }
      
      public Builder clear() {
        if (result == null) {
          throw new IllegalStateException(
            "Cannot call clear() after build().");
        }
        result = new net.freeback.entries.store.FBStoreDictProto.FBStoreDict();
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(result);
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return net.freeback.entries.store.FBStoreDictProto.FBStoreDict.getDescriptor();
      }
      
      public net.freeback.entries.store.FBStoreDictProto.FBStoreDict getDefaultInstanceForType() {
        return net.freeback.entries.store.FBStoreDictProto.FBStoreDict.getDefaultInstance();
      }
      
      public boolean isInitialized() {
        return result.isInitialized();
      }
      public net.freeback.entries.store.FBStoreDictProto.FBStoreDict build() {
        if (result != null && !isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return buildPartial();
      }
      
      private net.freeback.entries.store.FBStoreDictProto.FBStoreDict buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        if (!isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return buildPartial();
      }
      
      public net.freeback.entries.store.FBStoreDictProto.FBStoreDict buildPartial() {
        if (result == null) {
          throw new IllegalStateException(
            "build() has already been called on this Builder.");
        }
        if (result.industires_ != java.util.Collections.EMPTY_LIST) {
          result.industires_ =
            java.util.Collections.unmodifiableList(result.industires_);
        }
        if (result.categories_ != java.util.Collections.EMPTY_LIST) {
          result.categories_ =
            java.util.Collections.unmodifiableList(result.categories_);
        }
        if (result.dimensions_ != java.util.Collections.EMPTY_LIST) {
          result.dimensions_ =
            java.util.Collections.unmodifiableList(result.dimensions_);
        }
        net.freeback.entries.store.FBStoreDictProto.FBStoreDict returnMe = result;
        result = null;
        return returnMe;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof net.freeback.entries.store.FBStoreDictProto.FBStoreDict) {
          return mergeFrom((net.freeback.entries.store.FBStoreDictProto.FBStoreDict)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(net.freeback.entries.store.FBStoreDictProto.FBStoreDict other) {
        if (other == net.freeback.entries.store.FBStoreDictProto.FBStoreDict.getDefaultInstance()) return this;
        if (other.hasCode()) {
          setCode(other.getCode());
        }
        if (other.hasStore()) {
          setStore(other.getStore());
        }
        if (other.hasVersionValue()) {
          setVersionValue(other.getVersionValue());
        }
        if (!other.industires_.isEmpty()) {
          if (result.industires_.isEmpty()) {
            result.industires_ = new java.util.ArrayList<net.freeback.entries.FBSystemProto.FBIndustry>();
          }
          result.industires_.addAll(other.industires_);
        }
        if (!other.categories_.isEmpty()) {
          if (result.categories_.isEmpty()) {
            result.categories_ = new java.util.ArrayList<net.freeback.entries.FBSystemProto.FBCategory>();
          }
          result.categories_.addAll(other.categories_);
        }
        if (!other.dimensions_.isEmpty()) {
          if (result.dimensions_.isEmpty()) {
            result.dimensions_ = new java.util.ArrayList<net.freeback.entries.FBSystemProto.FBDimension>();
          }
          result.dimensions_.addAll(other.dimensions_);
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                return this;
              }
              break;
            }
            case 10: {
              setCode(input.readString());
              break;
            }
            case 18: {
              setStore(input.readString());
              break;
            }
            case 24: {
              setVersionValue(input.readInt32());
              break;
            }
            case 34: {
              net.freeback.entries.FBSystemProto.FBIndustry.Builder subBuilder = net.freeback.entries.FBSystemProto.FBIndustry.newBuilder();
              input.readMessage(subBuilder, extensionRegistry);
              addIndustires(subBuilder.buildPartial());
              break;
            }
            case 42: {
              net.freeback.entries.FBSystemProto.FBCategory.Builder subBuilder = net.freeback.entries.FBSystemProto.FBCategory.newBuilder();
              input.readMessage(subBuilder, extensionRegistry);
              addCategories(subBuilder.buildPartial());
              break;
            }
            case 50: {
              net.freeback.entries.FBSystemProto.FBDimension.Builder subBuilder = net.freeback.entries.FBSystemProto.FBDimension.newBuilder();
              input.readMessage(subBuilder, extensionRegistry);
              addDimensions(subBuilder.buildPartial());
              break;
            }
          }
        }
      }
      
      
      // required string Code = 1;
      public boolean hasCode() {
        return result.hasCode();
      }
      public java.lang.String getCode() {
        return result.getCode();
      }
      public Builder setCode(java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  result.hasCode = true;
        result.code_ = value;
        return this;
      }
      public Builder clearCode() {
        result.hasCode = false;
        result.code_ = getDefaultInstance().getCode();
        return this;
      }
      
      // required string Store = 2;
      public boolean hasStore() {
        return result.hasStore();
      }
      public java.lang.String getStore() {
        return result.getStore();
      }
      public Builder setStore(java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  result.hasStore = true;
        result.store_ = value;
        return this;
      }
      public Builder clearStore() {
        result.hasStore = false;
        result.store_ = getDefaultInstance().getStore();
        return this;
      }
      
      // required int32 VersionValue = 3;
      public boolean hasVersionValue() {
        return result.hasVersionValue();
      }
      public int getVersionValue() {
        return result.getVersionValue();
      }
      public Builder setVersionValue(int value) {
        result.hasVersionValue = true;
        result.versionValue_ = value;
        return this;
      }
      public Builder clearVersionValue() {
        result.hasVersionValue = false;
        result.versionValue_ = 0;
        return this;
      }
      
      // repeated .net.freeback.FBIndustry Industires = 4;
      public java.util.List<net.freeback.entries.FBSystemProto.FBIndustry> getIndustiresList() {
        return java.util.Collections.unmodifiableList(result.industires_);
      }
      public int getIndustiresCount() {
        return result.getIndustiresCount();
      }
      public net.freeback.entries.FBSystemProto.FBIndustry getIndustires(int index) {
        return result.getIndustires(index);
      }
      public Builder setIndustires(int index, net.freeback.entries.FBSystemProto.FBIndustry value) {
        if (value == null) {
          throw new NullPointerException();
        }
        result.industires_.set(index, value);
        return this;
      }
      public Builder setIndustires(int index, net.freeback.entries.FBSystemProto.FBIndustry.Builder builderForValue) {
        result.industires_.set(index, builderForValue.build());
        return this;
      }
      public Builder addIndustires(net.freeback.entries.FBSystemProto.FBIndustry value) {
        if (value == null) {
          throw new NullPointerException();
        }
        if (result.industires_.isEmpty()) {
          result.industires_ = new java.util.ArrayList<net.freeback.entries.FBSystemProto.FBIndustry>();
        }
        result.industires_.add(value);
        return this;
      }
      public Builder addIndustires(net.freeback.entries.FBSystemProto.FBIndustry.Builder builderForValue) {
        if (result.industires_.isEmpty()) {
          result.industires_ = new java.util.ArrayList<net.freeback.entries.FBSystemProto.FBIndustry>();
        }
        result.industires_.add(builderForValue.build());
        return this;
      }
      public Builder addAllIndustires(
          java.lang.Iterable<? extends net.freeback.entries.FBSystemProto.FBIndustry> values) {
        if (result.industires_.isEmpty()) {
          result.industires_ = new java.util.ArrayList<net.freeback.entries.FBSystemProto.FBIndustry>();
        }
        super.addAll(values, result.industires_);
        return this;
      }
      public Builder clearIndustires() {
        result.industires_ = java.util.Collections.emptyList();
        return this;
      }
      
      // repeated .net.freeback.FBCategory Categories = 5;
      public java.util.List<net.freeback.entries.FBSystemProto.FBCategory> getCategoriesList() {
        return java.util.Collections.unmodifiableList(result.categories_);
      }
      public int getCategoriesCount() {
        return result.getCategoriesCount();
      }
      public net.freeback.entries.FBSystemProto.FBCategory getCategories(int index) {
        return result.getCategories(index);
      }
      public Builder setCategories(int index, net.freeback.entries.FBSystemProto.FBCategory value) {
        if (value == null) {
          throw new NullPointerException();
        }
        result.categories_.set(index, value);
        return this;
      }
      public Builder setCategories(int index, net.freeback.entries.FBSystemProto.FBCategory.Builder builderForValue) {
        result.categories_.set(index, builderForValue.build());
        return this;
      }
      public Builder addCategories(net.freeback.entries.FBSystemProto.FBCategory value) {
        if (value == null) {
          throw new NullPointerException();
        }
        if (result.categories_.isEmpty()) {
          result.categories_ = new java.util.ArrayList<net.freeback.entries.FBSystemProto.FBCategory>();
        }
        result.categories_.add(value);
        return this;
      }
      public Builder addCategories(net.freeback.entries.FBSystemProto.FBCategory.Builder builderForValue) {
        if (result.categories_.isEmpty()) {
          result.categories_ = new java.util.ArrayList<net.freeback.entries.FBSystemProto.FBCategory>();
        }
        result.categories_.add(builderForValue.build());
        return this;
      }
      public Builder addAllCategories(
          java.lang.Iterable<? extends net.freeback.entries.FBSystemProto.FBCategory> values) {
        if (result.categories_.isEmpty()) {
          result.categories_ = new java.util.ArrayList<net.freeback.entries.FBSystemProto.FBCategory>();
        }
        super.addAll(values, result.categories_);
        return this;
      }
      public Builder clearCategories() {
        result.categories_ = java.util.Collections.emptyList();
        return this;
      }
      
      // repeated .net.freeback.FBDimension Dimensions = 6;
      public java.util.List<net.freeback.entries.FBSystemProto.FBDimension> getDimensionsList() {
        return java.util.Collections.unmodifiableList(result.dimensions_);
      }
      public int getDimensionsCount() {
        return result.getDimensionsCount();
      }
      public net.freeback.entries.FBSystemProto.FBDimension getDimensions(int index) {
        return result.getDimensions(index);
      }
      public Builder setDimensions(int index, net.freeback.entries.FBSystemProto.FBDimension value) {
        if (value == null) {
          throw new NullPointerException();
        }
        result.dimensions_.set(index, value);
        return this;
      }
      public Builder setDimensions(int index, net.freeback.entries.FBSystemProto.FBDimension.Builder builderForValue) {
        result.dimensions_.set(index, builderForValue.build());
        return this;
      }
      public Builder addDimensions(net.freeback.entries.FBSystemProto.FBDimension value) {
        if (value == null) {
          throw new NullPointerException();
        }
        if (result.dimensions_.isEmpty()) {
          result.dimensions_ = new java.util.ArrayList<net.freeback.entries.FBSystemProto.FBDimension>();
        }
        result.dimensions_.add(value);
        return this;
      }
      public Builder addDimensions(net.freeback.entries.FBSystemProto.FBDimension.Builder builderForValue) {
        if (result.dimensions_.isEmpty()) {
          result.dimensions_ = new java.util.ArrayList<net.freeback.entries.FBSystemProto.FBDimension>();
        }
        result.dimensions_.add(builderForValue.build());
        return this;
      }
      public Builder addAllDimensions(
          java.lang.Iterable<? extends net.freeback.entries.FBSystemProto.FBDimension> values) {
        if (result.dimensions_.isEmpty()) {
          result.dimensions_ = new java.util.ArrayList<net.freeback.entries.FBSystemProto.FBDimension>();
        }
        super.addAll(values, result.dimensions_);
        return this;
      }
      public Builder clearDimensions() {
        result.dimensions_ = java.util.Collections.emptyList();
        return this;
      }
    }
    
    static {
      net.freeback.entries.store.FBStoreDictProto.getDescriptor();
    }
    
    static {
      net.freeback.entries.store.FBStoreDictProto.internalForceInit();
    }
  }
  
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_net_freeback_FBStoreDict_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_net_freeback_FBStoreDict_fieldAccessorTable;
  
  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\021FBStoreDict.proto\022\014net.freeback\032\016FBSys" +
      "tem.proto\"\313\001\n\013FBStoreDict\022\014\n\004Code\030\001 \002(\t\022" +
      "\r\n\005Store\030\002 \002(\t\022\024\n\014VersionValue\030\003 \002(\005\022,\n\n" +
      "Industires\030\004 \003(\0132\030.net.freeback.FBIndust" +
      "ry\022,\n\nCategories\030\005 \003(\0132\030.net.freeback.FB" +
      "Category\022-\n\nDimensions\030\006 \003(\0132\031.net.freeb" +
      "ack.FBDimensionB.\n\032net.freeback.entries." +
      "storeB\020FBStoreDictProto"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_net_freeback_FBStoreDict_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_net_freeback_FBStoreDict_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_net_freeback_FBStoreDict_descriptor,
              new java.lang.String[] { "Code", "Store", "VersionValue", "Industires", "Categories", "Dimensions", },
              net.freeback.entries.store.FBStoreDictProto.FBStoreDict.class,
              net.freeback.entries.store.FBStoreDictProto.FBStoreDict.Builder.class);
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          net.freeback.entries.FBSystemProto.getDescriptor(),
        }, assigner);
  }
  
  public static void internalForceInit() {}
}
