// Generated by the protocol buffer compiler.  DO NOT EDIT!

package net.freeback.entries.store;

public final class FBStoreProto {
  private FBStoreProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public enum StoreState
      implements com.google.protobuf.ProtocolMessageEnum {
    Openning(0, 1),
    Closed(1, 2),
    Frozen(2, 3),
    ;
    
    
    public final int getNumber() { return value; }
    
    public static StoreState valueOf(int value) {
      switch (value) {
        case 1: return Openning;
        case 2: return Closed;
        case 3: return Frozen;
        default: return null;
      }
    }
    
    public static com.google.protobuf.Internal.EnumLiteMap<StoreState>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static com.google.protobuf.Internal.EnumLiteMap<StoreState>
        internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<StoreState>() {
            public StoreState findValueByNumber(int number) {
              return StoreState.valueOf(number)
    ;        }
          };
    
    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      return getDescriptor().getValues().get(index);
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return net.freeback.entries.store.FBStoreProto.getDescriptor().getEnumTypes().get(0);
    }
    
    private static final StoreState[] VALUES = {
      Openning, Closed, Frozen, 
    };
    public static StoreState valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      return VALUES[desc.getIndex()];
    }
    private final int index;
    private final int value;
    private StoreState(int index, int value) {
      this.index = index;
      this.value = value;
    }
    
    static {
      net.freeback.entries.store.FBStoreProto.getDescriptor();
    }
  }
  
  public static final class FBStores extends
      com.google.protobuf.GeneratedMessage {
    // Use FBStores.newBuilder() to construct.
    private FBStores() {}
    
    private static final FBStores defaultInstance = new FBStores();
    public static FBStores getDefaultInstance() {
      return defaultInstance;
    }
    
    public FBStores getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return net.freeback.entries.store.FBStoreProto.internal_static_net_freeback_FBStores_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return net.freeback.entries.store.FBStoreProto.internal_static_net_freeback_FBStores_fieldAccessorTable;
    }
    
    // repeated .net.freeback.FBStore Stores = 1;
    public static final int STORES_FIELD_NUMBER = 1;
    private java.util.List<net.freeback.entries.store.FBStoreProto.FBStore> stores_ =
      java.util.Collections.emptyList();
    public java.util.List<net.freeback.entries.store.FBStoreProto.FBStore> getStoresList() {
      return stores_;
    }
    public int getStoresCount() { return stores_.size(); }
    public net.freeback.entries.store.FBStoreProto.FBStore getStores(int index) {
      return stores_.get(index);
    }
    
    public final boolean isInitialized() {
      for (net.freeback.entries.store.FBStoreProto.FBStore element : getStoresList()) {
        if (!element.isInitialized()) return false;
      }
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      for (net.freeback.entries.store.FBStoreProto.FBStore element : getStoresList()) {
        output.writeMessage(1, element);
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      for (net.freeback.entries.store.FBStoreProto.FBStore element : getStoresList()) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, element);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    public static net.freeback.entries.store.FBStoreProto.FBStores parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static net.freeback.entries.store.FBStoreProto.FBStores parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static net.freeback.entries.store.FBStoreProto.FBStores parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static net.freeback.entries.store.FBStoreProto.FBStores parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static net.freeback.entries.store.FBStoreProto.FBStores parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static net.freeback.entries.store.FBStoreProto.FBStores parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static net.freeback.entries.store.FBStoreProto.FBStores parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeDelimitedFrom(input).buildParsed();
    }
    public static net.freeback.entries.store.FBStoreProto.FBStores parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeDelimitedFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static net.freeback.entries.store.FBStoreProto.FBStores parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static net.freeback.entries.store.FBStoreProto.FBStores parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(net.freeback.entries.store.FBStoreProto.FBStores prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> {
      private net.freeback.entries.store.FBStoreProto.FBStores result;
      
      // Construct using net.freeback.entries.store.FBStoreProto.FBStores.newBuilder()
      private Builder() {}
      
      private static Builder create() {
        Builder builder = new Builder();
        builder.result = new net.freeback.entries.store.FBStoreProto.FBStores();
        return builder;
      }
      
      protected net.freeback.entries.store.FBStoreProto.FBStores internalGetResult() {
        return result;
      }
      
      public Builder clear() {
        if (result == null) {
          throw new IllegalStateException(
            "Cannot call clear() after build().");
        }
        result = new net.freeback.entries.store.FBStoreProto.FBStores();
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(result);
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return net.freeback.entries.store.FBStoreProto.FBStores.getDescriptor();
      }
      
      public net.freeback.entries.store.FBStoreProto.FBStores getDefaultInstanceForType() {
        return net.freeback.entries.store.FBStoreProto.FBStores.getDefaultInstance();
      }
      
      public boolean isInitialized() {
        return result.isInitialized();
      }
      public net.freeback.entries.store.FBStoreProto.FBStores build() {
        if (result != null && !isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return buildPartial();
      }
      
      private net.freeback.entries.store.FBStoreProto.FBStores buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        if (!isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return buildPartial();
      }
      
      public net.freeback.entries.store.FBStoreProto.FBStores buildPartial() {
        if (result == null) {
          throw new IllegalStateException(
            "build() has already been called on this Builder.");
        }
        if (result.stores_ != java.util.Collections.EMPTY_LIST) {
          result.stores_ =
            java.util.Collections.unmodifiableList(result.stores_);
        }
        net.freeback.entries.store.FBStoreProto.FBStores returnMe = result;
        result = null;
        return returnMe;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof net.freeback.entries.store.FBStoreProto.FBStores) {
          return mergeFrom((net.freeback.entries.store.FBStoreProto.FBStores)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(net.freeback.entries.store.FBStoreProto.FBStores other) {
        if (other == net.freeback.entries.store.FBStoreProto.FBStores.getDefaultInstance()) return this;
        if (!other.stores_.isEmpty()) {
          if (result.stores_.isEmpty()) {
            result.stores_ = new java.util.ArrayList<net.freeback.entries.store.FBStoreProto.FBStore>();
          }
          result.stores_.addAll(other.stores_);
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                return this;
              }
              break;
            }
            case 10: {
              net.freeback.entries.store.FBStoreProto.FBStore.Builder subBuilder = net.freeback.entries.store.FBStoreProto.FBStore.newBuilder();
              input.readMessage(subBuilder, extensionRegistry);
              addStores(subBuilder.buildPartial());
              break;
            }
          }
        }
      }
      
      
      // repeated .net.freeback.FBStore Stores = 1;
      public java.util.List<net.freeback.entries.store.FBStoreProto.FBStore> getStoresList() {
        return java.util.Collections.unmodifiableList(result.stores_);
      }
      public int getStoresCount() {
        return result.getStoresCount();
      }
      public net.freeback.entries.store.FBStoreProto.FBStore getStores(int index) {
        return result.getStores(index);
      }
      public Builder setStores(int index, net.freeback.entries.store.FBStoreProto.FBStore value) {
        if (value == null) {
          throw new NullPointerException();
        }
        result.stores_.set(index, value);
        return this;
      }
      public Builder setStores(int index, net.freeback.entries.store.FBStoreProto.FBStore.Builder builderForValue) {
        result.stores_.set(index, builderForValue.build());
        return this;
      }
      public Builder addStores(net.freeback.entries.store.FBStoreProto.FBStore value) {
        if (value == null) {
          throw new NullPointerException();
        }
        if (result.stores_.isEmpty()) {
          result.stores_ = new java.util.ArrayList<net.freeback.entries.store.FBStoreProto.FBStore>();
        }
        result.stores_.add(value);
        return this;
      }
      public Builder addStores(net.freeback.entries.store.FBStoreProto.FBStore.Builder builderForValue) {
        if (result.stores_.isEmpty()) {
          result.stores_ = new java.util.ArrayList<net.freeback.entries.store.FBStoreProto.FBStore>();
        }
        result.stores_.add(builderForValue.build());
        return this;
      }
      public Builder addAllStores(
          java.lang.Iterable<? extends net.freeback.entries.store.FBStoreProto.FBStore> values) {
        if (result.stores_.isEmpty()) {
          result.stores_ = new java.util.ArrayList<net.freeback.entries.store.FBStoreProto.FBStore>();
        }
        super.addAll(values, result.stores_);
        return this;
      }
      public Builder clearStores() {
        result.stores_ = java.util.Collections.emptyList();
        return this;
      }
    }
    
    static {
      net.freeback.entries.store.FBStoreProto.getDescriptor();
    }
    
    static {
      net.freeback.entries.store.FBStoreProto.internalForceInit();
    }
  }
  
  public static final class FBStore extends
      com.google.protobuf.GeneratedMessage {
    // Use FBStore.newBuilder() to construct.
    private FBStore() {}
    
    private static final FBStore defaultInstance = new FBStore();
    public static FBStore getDefaultInstance() {
      return defaultInstance;
    }
    
    public FBStore getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return net.freeback.entries.store.FBStoreProto.internal_static_net_freeback_FBStore_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return net.freeback.entries.store.FBStoreProto.internal_static_net_freeback_FBStore_fieldAccessorTable;
    }
    
    // required string Code = 1;
    public static final int CODE_FIELD_NUMBER = 1;
    private boolean hasCode;
    private java.lang.String code_ = "";
    public boolean hasCode() { return hasCode; }
    public java.lang.String getCode() { return code_; }
    
    // required string Boss = 2;
    public static final int BOSS_FIELD_NUMBER = 2;
    private boolean hasBoss;
    private java.lang.String boss_ = "";
    public boolean hasBoss() { return hasBoss; }
    public java.lang.String getBoss() { return boss_; }
    
    // required string Name = 3;
    public static final int NAME_FIELD_NUMBER = 3;
    private boolean hasName;
    private java.lang.String name_ = "";
    public boolean hasName() { return hasName; }
    public java.lang.String getName() { return name_; }
    
    // required int32 Industry = 4;
    public static final int INDUSTRY_FIELD_NUMBER = 4;
    private boolean hasIndustry;
    private int industry_ = 0;
    public boolean hasIndustry() { return hasIndustry; }
    public int getIndustry() { return industry_; }
    
    // required string Phone = 5;
    public static final int PHONE_FIELD_NUMBER = 5;
    private boolean hasPhone;
    private java.lang.String phone_ = "";
    public boolean hasPhone() { return hasPhone; }
    public java.lang.String getPhone() { return phone_; }
    
    // required string Address = 7;
    public static final int ADDRESS_FIELD_NUMBER = 7;
    private boolean hasAddress;
    private java.lang.String address_ = "";
    public boolean hasAddress() { return hasAddress; }
    public java.lang.String getAddress() { return address_; }
    
    // required .net.freeback.StoreState State = 8;
    public static final int STATE_FIELD_NUMBER = 8;
    private boolean hasState;
    private net.freeback.entries.store.FBStoreProto.StoreState state_ = net.freeback.entries.store.FBStoreProto.StoreState.Openning;
    public boolean hasState() { return hasState; }
    public net.freeback.entries.store.FBStoreProto.StoreState getState() { return state_; }
    
    // required string Description = 9;
    public static final int DESCRIPTION_FIELD_NUMBER = 9;
    private boolean hasDescription;
    private java.lang.String description_ = "";
    public boolean hasDescription() { return hasDescription; }
    public java.lang.String getDescription() { return description_; }
    
    // optional string Modified = 10;
    public static final int MODIFIED_FIELD_NUMBER = 10;
    private boolean hasModified;
    private java.lang.String modified_ = "";
    public boolean hasModified() { return hasModified; }
    public java.lang.String getModified() { return modified_; }
    
    public final boolean isInitialized() {
      if (!hasCode) return false;
      if (!hasBoss) return false;
      if (!hasName) return false;
      if (!hasIndustry) return false;
      if (!hasPhone) return false;
      if (!hasAddress) return false;
      if (!hasState) return false;
      if (!hasDescription) return false;
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (hasCode()) {
        output.writeString(1, getCode());
      }
      if (hasBoss()) {
        output.writeString(2, getBoss());
      }
      if (hasName()) {
        output.writeString(3, getName());
      }
      if (hasIndustry()) {
        output.writeInt32(4, getIndustry());
      }
      if (hasPhone()) {
        output.writeString(5, getPhone());
      }
      if (hasAddress()) {
        output.writeString(7, getAddress());
      }
      if (hasState()) {
        output.writeEnum(8, getState().getNumber());
      }
      if (hasDescription()) {
        output.writeString(9, getDescription());
      }
      if (hasModified()) {
        output.writeString(10, getModified());
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      if (hasCode()) {
        size += com.google.protobuf.CodedOutputStream
          .computeStringSize(1, getCode());
      }
      if (hasBoss()) {
        size += com.google.protobuf.CodedOutputStream
          .computeStringSize(2, getBoss());
      }
      if (hasName()) {
        size += com.google.protobuf.CodedOutputStream
          .computeStringSize(3, getName());
      }
      if (hasIndustry()) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(4, getIndustry());
      }
      if (hasPhone()) {
        size += com.google.protobuf.CodedOutputStream
          .computeStringSize(5, getPhone());
      }
      if (hasAddress()) {
        size += com.google.protobuf.CodedOutputStream
          .computeStringSize(7, getAddress());
      }
      if (hasState()) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(8, getState().getNumber());
      }
      if (hasDescription()) {
        size += com.google.protobuf.CodedOutputStream
          .computeStringSize(9, getDescription());
      }
      if (hasModified()) {
        size += com.google.protobuf.CodedOutputStream
          .computeStringSize(10, getModified());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    public static net.freeback.entries.store.FBStoreProto.FBStore parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static net.freeback.entries.store.FBStoreProto.FBStore parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static net.freeback.entries.store.FBStoreProto.FBStore parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static net.freeback.entries.store.FBStoreProto.FBStore parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static net.freeback.entries.store.FBStoreProto.FBStore parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static net.freeback.entries.store.FBStoreProto.FBStore parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static net.freeback.entries.store.FBStoreProto.FBStore parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeDelimitedFrom(input).buildParsed();
    }
    public static net.freeback.entries.store.FBStoreProto.FBStore parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeDelimitedFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static net.freeback.entries.store.FBStoreProto.FBStore parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static net.freeback.entries.store.FBStoreProto.FBStore parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(net.freeback.entries.store.FBStoreProto.FBStore prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> {
      private net.freeback.entries.store.FBStoreProto.FBStore result;
      
      // Construct using net.freeback.entries.store.FBStoreProto.FBStore.newBuilder()
      private Builder() {}
      
      private static Builder create() {
        Builder builder = new Builder();
        builder.result = new net.freeback.entries.store.FBStoreProto.FBStore();
        return builder;
      }
      
      protected net.freeback.entries.store.FBStoreProto.FBStore internalGetResult() {
        return result;
      }
      
      public Builder clear() {
        if (result == null) {
          throw new IllegalStateException(
            "Cannot call clear() after build().");
        }
        result = new net.freeback.entries.store.FBStoreProto.FBStore();
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(result);
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return net.freeback.entries.store.FBStoreProto.FBStore.getDescriptor();
      }
      
      public net.freeback.entries.store.FBStoreProto.FBStore getDefaultInstanceForType() {
        return net.freeback.entries.store.FBStoreProto.FBStore.getDefaultInstance();
      }
      
      public boolean isInitialized() {
        return result.isInitialized();
      }
      public net.freeback.entries.store.FBStoreProto.FBStore build() {
        if (result != null && !isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return buildPartial();
      }
      
      private net.freeback.entries.store.FBStoreProto.FBStore buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        if (!isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return buildPartial();
      }
      
      public net.freeback.entries.store.FBStoreProto.FBStore buildPartial() {
        if (result == null) {
          throw new IllegalStateException(
            "build() has already been called on this Builder.");
        }
        net.freeback.entries.store.FBStoreProto.FBStore returnMe = result;
        result = null;
        return returnMe;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof net.freeback.entries.store.FBStoreProto.FBStore) {
          return mergeFrom((net.freeback.entries.store.FBStoreProto.FBStore)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(net.freeback.entries.store.FBStoreProto.FBStore other) {
        if (other == net.freeback.entries.store.FBStoreProto.FBStore.getDefaultInstance()) return this;
        if (other.hasCode()) {
          setCode(other.getCode());
        }
        if (other.hasBoss()) {
          setBoss(other.getBoss());
        }
        if (other.hasName()) {
          setName(other.getName());
        }
        if (other.hasIndustry()) {
          setIndustry(other.getIndustry());
        }
        if (other.hasPhone()) {
          setPhone(other.getPhone());
        }
        if (other.hasAddress()) {
          setAddress(other.getAddress());
        }
        if (other.hasState()) {
          setState(other.getState());
        }
        if (other.hasDescription()) {
          setDescription(other.getDescription());
        }
        if (other.hasModified()) {
          setModified(other.getModified());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                return this;
              }
              break;
            }
            case 10: {
              setCode(input.readString());
              break;
            }
            case 18: {
              setBoss(input.readString());
              break;
            }
            case 26: {
              setName(input.readString());
              break;
            }
            case 32: {
              setIndustry(input.readInt32());
              break;
            }
            case 42: {
              setPhone(input.readString());
              break;
            }
            case 58: {
              setAddress(input.readString());
              break;
            }
            case 64: {
              int rawValue = input.readEnum();
              net.freeback.entries.store.FBStoreProto.StoreState value = net.freeback.entries.store.FBStoreProto.StoreState.valueOf(rawValue);
              if (value == null) {
                unknownFields.mergeVarintField(8, rawValue);
              } else {
                setState(value);
              }
              break;
            }
            case 74: {
              setDescription(input.readString());
              break;
            }
            case 82: {
              setModified(input.readString());
              break;
            }
          }
        }
      }
      
      
      // required string Code = 1;
      public boolean hasCode() {
        return result.hasCode();
      }
      public java.lang.String getCode() {
        return result.getCode();
      }
      public Builder setCode(java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  result.hasCode = true;
        result.code_ = value;
        return this;
      }
      public Builder clearCode() {
        result.hasCode = false;
        result.code_ = getDefaultInstance().getCode();
        return this;
      }
      
      // required string Boss = 2;
      public boolean hasBoss() {
        return result.hasBoss();
      }
      public java.lang.String getBoss() {
        return result.getBoss();
      }
      public Builder setBoss(java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  result.hasBoss = true;
        result.boss_ = value;
        return this;
      }
      public Builder clearBoss() {
        result.hasBoss = false;
        result.boss_ = getDefaultInstance().getBoss();
        return this;
      }
      
      // required string Name = 3;
      public boolean hasName() {
        return result.hasName();
      }
      public java.lang.String getName() {
        return result.getName();
      }
      public Builder setName(java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  result.hasName = true;
        result.name_ = value;
        return this;
      }
      public Builder clearName() {
        result.hasName = false;
        result.name_ = getDefaultInstance().getName();
        return this;
      }
      
      // required int32 Industry = 4;
      public boolean hasIndustry() {
        return result.hasIndustry();
      }
      public int getIndustry() {
        return result.getIndustry();
      }
      public Builder setIndustry(int value) {
        result.hasIndustry = true;
        result.industry_ = value;
        return this;
      }
      public Builder clearIndustry() {
        result.hasIndustry = false;
        result.industry_ = 0;
        return this;
      }
      
      // required string Phone = 5;
      public boolean hasPhone() {
        return result.hasPhone();
      }
      public java.lang.String getPhone() {
        return result.getPhone();
      }
      public Builder setPhone(java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  result.hasPhone = true;
        result.phone_ = value;
        return this;
      }
      public Builder clearPhone() {
        result.hasPhone = false;
        result.phone_ = getDefaultInstance().getPhone();
        return this;
      }
      
      // required string Address = 7;
      public boolean hasAddress() {
        return result.hasAddress();
      }
      public java.lang.String getAddress() {
        return result.getAddress();
      }
      public Builder setAddress(java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  result.hasAddress = true;
        result.address_ = value;
        return this;
      }
      public Builder clearAddress() {
        result.hasAddress = false;
        result.address_ = getDefaultInstance().getAddress();
        return this;
      }
      
      // required .net.freeback.StoreState State = 8;
      public boolean hasState() {
        return result.hasState();
      }
      public net.freeback.entries.store.FBStoreProto.StoreState getState() {
        return result.getState();
      }
      public Builder setState(net.freeback.entries.store.FBStoreProto.StoreState value) {
        if (value == null) {
          throw new NullPointerException();
        }
        result.hasState = true;
        result.state_ = value;
        return this;
      }
      public Builder clearState() {
        result.hasState = false;
        result.state_ = net.freeback.entries.store.FBStoreProto.StoreState.Openning;
        return this;
      }
      
      // required string Description = 9;
      public boolean hasDescription() {
        return result.hasDescription();
      }
      public java.lang.String getDescription() {
        return result.getDescription();
      }
      public Builder setDescription(java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  result.hasDescription = true;
        result.description_ = value;
        return this;
      }
      public Builder clearDescription() {
        result.hasDescription = false;
        result.description_ = getDefaultInstance().getDescription();
        return this;
      }
      
      // optional string Modified = 10;
      public boolean hasModified() {
        return result.hasModified();
      }
      public java.lang.String getModified() {
        return result.getModified();
      }
      public Builder setModified(java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  result.hasModified = true;
        result.modified_ = value;
        return this;
      }
      public Builder clearModified() {
        result.hasModified = false;
        result.modified_ = getDefaultInstance().getModified();
        return this;
      }
    }
    
    static {
      net.freeback.entries.store.FBStoreProto.getDescriptor();
    }
    
    static {
      net.freeback.entries.store.FBStoreProto.internalForceInit();
    }
  }
  
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_net_freeback_FBStores_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_net_freeback_FBStores_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_net_freeback_FBStore_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_net_freeback_FBStore_fieldAccessorTable;
  
  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\rFBStore.proto\022\014net.freeback\"1\n\010FBStore" +
      "s\022%\n\006Stores\030\001 \003(\0132\025.net.freeback.FBStore" +
      "\"\265\001\n\007FBStore\022\014\n\004Code\030\001 \002(\t\022\014\n\004Boss\030\002 \002(\t" +
      "\022\014\n\004Name\030\003 \002(\t\022\020\n\010Industry\030\004 \002(\005\022\r\n\005Phon" +
      "e\030\005 \002(\t\022\017\n\007Address\030\007 \002(\t\022\'\n\005State\030\010 \002(\0162" +
      "\030.net.freeback.StoreState\022\023\n\013Description" +
      "\030\t \002(\t\022\020\n\010Modified\030\n \001(\t*2\n\nStoreState\022\014" +
      "\n\010Openning\020\001\022\n\n\006Closed\020\002\022\n\n\006Frozen\020\003B*\n\032" +
      "net.freeback.entries.storeB\014FBStoreProto"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_net_freeback_FBStores_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_net_freeback_FBStores_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_net_freeback_FBStores_descriptor,
              new java.lang.String[] { "Stores", },
              net.freeback.entries.store.FBStoreProto.FBStores.class,
              net.freeback.entries.store.FBStoreProto.FBStores.Builder.class);
          internal_static_net_freeback_FBStore_descriptor =
            getDescriptor().getMessageTypes().get(1);
          internal_static_net_freeback_FBStore_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_net_freeback_FBStore_descriptor,
              new java.lang.String[] { "Code", "Boss", "Name", "Industry", "Phone", "Address", "State", "Description", "Modified", },
              net.freeback.entries.store.FBStoreProto.FBStore.class,
              net.freeback.entries.store.FBStoreProto.FBStore.Builder.class);
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }
  
  public static void internalForceInit() {}
}
